seL4/seL4

src/arch/x86/32/kernel/vspace_pae.c
When configuring with both CONFIG_PAE and CONFIG_PRINTING,
this needed to be declared (I didn't implement the function however, just added a stub)
=> add stub Arch_userStackTrace for x86 PAE

libsel4/tools/syscall_stub_gen.py
* `syscall_stub_gen.py` now works on x86_64 without passing `--buffer`
* *All is well in the universe* with x86_64 in qemu if I remove `--buffer` from the `libsel4` Makefile
=> Let x86_64 CallWithMRs

libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/syscalls.h
* Initialise the message variables (as per ia32 and x86_64)
* `libsel4` now builds when `syscall_stub_gen.py` is run without `--buffer`
* While simple things appear to work, `sel4test` with aarch32 in qemu is *not* happy:
```
Bootstrapping kernel
Warning: using printf before serial is set up. This only works as your
printf is backed by seL4_Debug_PutChar()
sel4utils_create_object_at_level@mapping.h:22 Should not be called
Ignoring call to sys_rt_sigprocmask
Ignoring call to sys_gettid
sys_tkill assuming self kill
```
=> Let aarch32 CallWithMRs

libsel4/tools/syscall_stub_gen.py
- passes the sabre/qemu test suite :-)
- this assumes we want to retain the same number of registers as we
have input parameters, which on reflection makes no sense at all
=> Retain register values when not using IPC buffer

libsel4/Kconfig, libsel4/arch_include/arm/sel4/arch/functions.h, libsel4/arch_include/arm/sel4/arch/syscalls.h, libsel4/arch_include/x86/sel4/arch/functions.h, libsel4/arch_include/x86/sel4/arch/syscalls.h, libsel4/include/sel4/faults.h, libsel4/include/sel4/macros.h, libsel4/include/sel4/syscalls.h, libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/faults.h, libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/mapping.h, libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/syscalls.h, libsel4/sel4_arch_include/ia32/sel4/sel4_arch/faults.h, libsel4/sel4_arch_include/ia32/sel4/sel4_arch/mapping.h, libsel4/sel4_arch_include/ia32/sel4/sel4_arch/syscalls.h, libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/faults.h, libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/mapping.h, libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/syscalls.h, tools/bitfield_gen.py
`CONFIG_LIB_SEL4_INLINE_INVOCATIONS=n` will now disable inlining for all external interfaces (except deprecated functions).
=> Optional inlining of functions and syscalls

src/arch/x86/64/head.S
It appears to be somewhat more correct to flip SCE after entering long mode, as per other operating systems (including Linux).
c.f. [Linux 4.8's head_64.S](http://lxr.free-electrons.com/source/arch/x86/kernel/head_64.S?v=4.8#L210), which is executed in long mode.
=> Enable SYSCALL (SCE) after entering long mode

manual/parts/bootup.tex, manual/parts/cspace.tex, manual/parts/ipc.tex
Notes:
- In Faults 6.2.3, IA-32 appears under the table in the PDF… not sure how to fix.
- Is there something wrong with the `_service` descriptions in 10.3.x?
- Some of the functions in the manual are `LIBSEL4_INLINE_FUNC`, some are `static inline`.
- My understanding is that a VSpace capability represents the highest level paging structure, e.g. PML4 on x86_64. If that's correct, it'd be worth mentioning it. If not, clarifying the documentation. :-)
Hmm, but oh:
```c
/* Legacy code will have assumptions on the vspace root being a Page Directory
* type, so for now we define one to the other */
#define seL4_CapInitThreadPD seL4_CapInitThreadVSpace
```
So, there's a second commit to make the manual reflect the current init cap list, but clearly my understanding of what's going on with …
=> Minor fixes from quick proof read of 4.0 manual

src/plat/pc99/machine/pit.c
This value is taken from the Linux kernel. I've been unable to find
a canonical source specifying this value. The PIT isn't even
acknowledged to exist in the Intel SDM or AMD BKDG. There are some
numbers about the *input* to the circuit that emulates the PIT on
modern Intel PCH's, 14.31818MHz, but nothing about the output. Doing
some math on the NTSC subcarrier frequency as mentioned in the
wikipedia article arrives at 1193181.6Hz, which rounds up to
1193182.
This value influences the measured frequency of the TSC, which is
later used in the RT kernel and elsewhere for determining how to
program the deadline timer, or other time-sensitive things.
=> Change PIT_HZ to 1193182

Makefile
This causes the first (and last) component of PATH to include a quote
character. This is obviously wrong. It manifested on my system as not
being able to find mkdir or anything else in /usr/bin since that was
the last entry in my own PATH
=> Remove extraneous quotes from PATH setting

include/api/debug.h, include/plat/pc99/plat/machine/interrupt.h, src/plat/pc99/machine/intel-vtd.c
As far as I can see this does not touch any verified code.
Passes all tests in sel4test with configuration x64_simulation_debug_xml_defconfig.
Compiles all targets in the compile-all make target, except kzm_simulation_debug_xml_defconfig which fails for me without patches.
=> Clang warnings

src/arch/arm/machine/gic_pl390.c
Removed commit invalidateByWSL, only removing set_irq_active. Reference: https://github.com/seL4/seL4/pull/64
make compile-all passes all targets. make simulate-x86_64 passes all tests in sel4test.
=> Removed unused static function set_irq_active

src/api/syscall.c
This will make it easier to understand which tread that triggered these debugging syscalls. Similar to the print in kernel/src/kernel/faulthandler.c. I've run sel4test on config x64_simulation_debug_xml_defconfig with all tests passing.
```
Starting test 102: Test all tests ran
Test suite passed. 102 tests passed. 46 tests disabled.
All is well in the universe
```
=> Add thread name to debug info for SysDebugHalt and SysDebugSnapshot

include/plat/spike/plat/machine/hardware.h, src/arch/riscv/Kconfig, src/arch/riscv/config.cmake
Small changes to get sel4test to boot on riscv32.  Not completely sure if this is the right way to do this, but it works.
=> Riscv32 Boot Fixes

include/plat/zynqmp/plat/machine/devices.h, src/arch/arm/config.cmake, src/plat/zynqmp/config.cmake
Add Ultra96 platform, which is based on the zynqmp SoC
=> zynqmp: add Ultra96 platform

include/arch/riscv/arch/machine.h, src/plat/spike/config.cmake, src/plat/spike/instance/freedom/config.cmake, src/plat/spike/instance/qemu/config.cmake, src/plat/spike/instance/rocket-chip/config.cmake, src/plat/spike/machine/hardware.c
During the last pull request, there were some comments about the Rocket-Chip sharing a bunch of code with the Spike platform. We updated cmake a little bit to allow for different instances of Spike, since platforms will have hardware specific options, like the timebase clock used for the scheduling tick. 
The other big change is moving the `sfence` call after `sptbr` has been updated. This wasn't an issue while running seL4test on the zedboard, but it became an issue when developing other applications, since there would be VM faults on context switches. This order is also how Linux does it, so it is either an ISA issue or a Rocket-Chip issue.
=> More RISC-V Changes

include/plat/exynos5/plat/machine/devices.h, include/plat/imx6/plat/machine/devices.h, include/plat/zynqmp/plat/machine/devices.h
These files contain conditional parts which depends on `CONFIG_PLAT_xxx` being set, thus they must include `config.h`. Currently it works, because the files including these headers already have included `config.h` before.
=> add missing include for config.h

libsel4/arch_include/riscv/sel4/arch/functions.h, libsel4/arch_include/riscv/sel4/arch/syscalls.h, libsel4/sel4_arch_include/riscv32/sel4/sel4_arch/mapping.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/mapping.h, libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/syscalls.h
Correct exported functions that were still defined as 'static inline' to
use LIBSEL4_INLINE_FUNC so that they can be controlled by
LibSel4FunctionAttributes.
This is important to other languages that want to bind to the libsel4
static library instead of using the inline C functions.
=> [libsel4] fix building with LibSel4FunctionAttributes

manual/parts/api.tex, manual/parts/ipc.tex
"Transfer" kind of sounds like it has move semantics.
=> manual: ipc: clarify sending caps is a copy

manual/parts/cspace.tex, manual/parts/objects.tex
It is 16 bytes on 32-bit systems and 32 bytes on 64-bit systems
=> manual: Correct CNode slot size in bytes

CMakeLists.txt, config.cmake, libsel4/CMakeLists.txt, libsel4/tools/__init__.py, libsel4/tools/syscall_stub_gen.py, manual/Makefile, manual/tools/gen_env.py, manual/tools/gen_invocations.py, manual/tools/parse_doxygen_xml.py, tools/bitfield_gen.py, tools/circular_includes.py, tools/hardware_gen.py, tools/helpers.cmake, tools/internal.cmake, tools/invocation_header_gen.py, tools/python-deps/setup.py, tools/syscall_header_gen.py, tools/umm.py
Update all scripts and build system to call python3, given python2's
upcoming doom. Use sys.maxsize instead of sys.maxint in one script
(maxint does not exist in python3).
=> python2 --> python3

src/arch/arm/64/machine/fpu.c
Prior to this commit this check was invalid for aarch64.
On aarch64 a value the values of the AdvSIMD/FP bits in ID_AA64PFR0_EL1
are as follows:
- 0b1111 means FPU/SIMD is not supported.
- 0b0000 means FPU/SIMD is supported except for half-precision floating
point arithmetic.
- 0b0001 means FPU/SIMD is supported including half-precision floating
point arithmetic.
See the ARMv8 manual for more detail.
=> aarch64: fix fpsimd_HWCapTest

src/arch/x86/kernel/vspace.c
As reported on the mailing list, the x86 version of the seL4 kernel does not flush the TLB in SMP setups correctly when the PCID features is not available by the target CPUs.
https://www.mail-archive.com/devel@sel4.systems/msg02245.html
https://www.mail-archive.com/devel@sel4.systems/msg02247.html
The following line seems to skip the proper flushing:
https://github.com/seL4/seL4/blob/master/src/arch/x86/kernel/vspace.c#L762
The commit seems to fix the issue as far as we can tell.
=> x86: ever invalidate TLB during unmapPage

libsel4/include/sel4/types.h
Relates to #168. The definition for `seL4_UntypedRetypeMaxObjects` lives
in the UAPI `types.h` but appears to have no link to the value actually
used by the kernel, which is configurable. This change sets the UAPI
definition to the generated definition from the kernel config steps and
defaults to the previous fixed value if, for some reason, the configured
definition is not available.
=> Use autoconf definition for `RetypeMaxObjects` def

gcc.cmake
This change introduces a `gcc` hunting helper function to `gcc.cmake` in
order to help us find an appropriately prefixed `gcc` for the target
being built for. We use this helper to find 32b ARM cross-compiling
`gcc`s for both Debian and Red Hat based distros.
=> Add support for ARM cross-compilers on Red Hat distros

tools/dts/hifive.dts
This sets the first UART as the stdout-path dts setting in the
"chosen" node in the HiFive device tree.
Change-Id: Icb6b9abf999bdd8a278df5a2ba73ad492af06a24
=> RISCV: Added stdout-path to hifive dts

libsel4/arch_include/arm/interfaces/sel4arch.xml, libsel4/sel4_arch_include/aarch32/interfaces/sel4arch.xml, libsel4/sel4_arch_include/aarch64/interfaces/sel4arch.xml
- Fill in some missing object and parameter descriptions
- Vspace mapping functions always take the vspace root as the argument
- Document more error conditions in vspace mapping functions
=> Expand and fix arm architecture-specific object method documentation

include/arch/arm/armv/armv8-a/64/armv/vcpu.h
Fixes a bug where `writeELR_EL1` was reading from `ELR_EL1` instead of writing to it.
=> aarch64: fix MRS/MSR in writeELR_EL1

include/arch/arm/armv/armv8-a/64/armv/vcpu.h
Fixes a bug where `writeFAR` was only writing to the low 32 bits of the 64-bit `FAR_EL1` register.
=> aarch64: fix FAR_EL1 width in writeFAR

gcc.cmake
This fixes an issue passing -DCROSS_COMPILER_PREFIX to cmake. Cache
variables (like CROSS_COMPILER_PREFIX) are not consistently accessible
from the toolchain file (gcc.cmake). Theu toolchain file is run several
times in different contexts, and when run in a context without access
to the cache, an incorrect (or no) c compiler is identified, as
CROSS_COMPILER_PREFIX appears to be unset.
To reproduce:
Checkout sel4test with repo. Be in an environment where the default arm toolchain "arm-linux-gnueabi-" or "arm-linux-gnu-" are not in your path.
```
../init-build.sh -DPLATFORM=am335x-boneblack -DAARCH32=1 -DCROSS_COMPILER_PREFIX=arm-none-eabi-
```
(substituting arm-none-eabi- with a cross compiler prefix that is in your path).
When I do this I see:
```
-- Found seL4: …
```
=> Set CROSS_COMPILER_PREFIX in gcc.cmake template

libsel4/tools/syscall_stub_gen.py
The "is" keyword compares addresses. "==" compares values.
```
+>>> a = 1000
+>>> b = a + 1
+>>> b == 1001
True
+>>> b is 1001
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
False
```
=> Fix python warning in syscall stub generator

include/arch/arm/arch/64/mode/object/structures.h
Adds missing vcpu cases for some aarch64-specific functions on capabilities.
=> aarch64: add missing vcpu cases

src/arch/x86/kernel/apic.c
This PR is a copy of #181, but with a sign-off message and rebased against master.
The first two data arguments used for the printf don't match what's
expected in the format string and are reversed.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> x86: Fix printf typo in apic_init()

include/arch/arm/arch/model/smp.h, include/arch/riscv/arch/model/smp.h, include/arch/x86/arch/model/smp.h, include/smp/lock.h, src/arch/x86/64/head.S
The PCID feature is the 17th bit in ECX when CPUID is called with
EAX=1. The constant for testing the feature should be 0x20000.
=> x64: Fix Github issue #174

include/arch/arm/arch/model/smp.h, include/arch/riscv/arch/model/smp.h, include/arch/x86/arch/model/smp.h, include/smp/lock.h
The implementation of try_arch_atomic_exchange does not correctly pass
RELEASE memory ordering (or stronger) to the exchange operation.
To acknowledge this, try_arch_atomic_exchange is replaced by a relaxed
try_arch_atomic_exchange_rlx which does not apply any memory ordering.
Instead, the memory ordering is now added manually by
sel4_atomic_exchange. This provides better latency for interrupts as no
barriers are evoked inside the loop which performs the relaxed exchange
and checks for interrupts.
Furthermore, the new manual application of barriers ensures the memory
ordering passed to sel4_atomic_exchange.
Signed-off-by: jonas <s9joober@gmail.com>
This pull request is an alternative to #205. It should provide better interrupt latency than #205 but is slightly more invasive.
=> Repair barriers in sel4_atomic_exchange

include/arch/arm/arch/model/smp.h, include/arch/riscv/arch/model/smp.h, include/arch/x86/arch/model/smp.h, include/smp/lock.h
Strengthen the clh_lock_acquire to use release on the atomic_exchange that makes the node public. Otherwise (on ARM & RISCV), the store to the node value which sets its state to CLHState_Pending can become visible some time after the node is visible.
In that window of time, the next thread which attempts to acquire the lock will still see the old state (CLHState_Granted) and enters the critical section, leading to a mutual exclusion violation.
See also: https://gist.github.com/JonasOberhauser/6198862f0c47f68040369787f131248f which is a test written by Diogo Behrens that can reproduce the mutual exclusion violation on some ARM servers (Taishan 2280)
The PR should be ready to merge.
Signed-off-by: jonas <s9joober@gmail.com>
=> Repair barriers in clh_lock_acquire

src/arch/riscv/traps.S
Tested via `-DPLATFORM=spike` build and `./simulate`.
=> riscv: Use full width of scause

src/arch/arm/machine/gic_v3.c
The MPIDR_AFFI1 field is included when sending IPIs, since cores
for IPI targets can be in a different cluster.
Signed-off-by: Yanyan Shen <yshen@cog.systems>
=> gicv3: Include cluster ID when sending IPIs

.github/workflows/compilation-checks.yml
On a PR, compile all verified configs of seL4.
I put it in its own yml file, so we can better sort through the results, using the GitHub GUI.
=> CI: Add a PR check to do a stand-alone kernel compilation 

include/object/notification.h
This is my first PR onto seL4, and is therefore somewhat exploratory.
The current state of MCS seL4 verification makes use of an invariant that whenever the scheduler action is set to "resume current thread" then the current thread and the current sc are bound together (point to each other). Since maybeReturnSchedContext may unbind a thread from a scheduling context, it should perform a check on whether it is unbinding from the current thread, and in that case call rescheduleRequired which will (among other things) change the scheduler action.
=> Check for reschedule on sched context return.

manual/parts/threads.tex
The concept of system criticality has been removed from the kernel, this
commit removes a last remnant of it from the manual.
Fixes github issue #240
=> manual: remove mention of system criticality

include/kernel/sporadic.h, include/kernel/thread.h, libsel4/CMakeLists.txt, libsel4/arch_include/riscv/sel4/arch/objecttype.h, libsel4/arch_include/riscv/sel4/arch/simple_types.h, libsel4/arch_include/riscv/sel4/arch/syscalls.h, libsel4/arch_include/riscv/sel4/arch/types.h, libsel4/include/sel4/functions.h, libsel4/sel4_arch_include/riscv32/sel4/sel4_arch/constants.h, libsel4/sel4_arch_include/riscv32/sel4/sel4_arch/faults.h, libsel4/sel4_arch_include/riscv32/sel4/sel4_arch/types.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/constants.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/faults.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/mapping.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/objecttype.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/types.h, src/api/syscall.c, src/kernel/boot.c, src/kernel/sporadic.c, src/kernel/thread.c, src/object/tcb.c
#245 points out that some GPL tags crept into libsel4.
This seems to have happened for cmake (where most of the other CMakeList files are GPL), and the RISCV release, which has the license correct for the kernel files, but just used the same tag for libsel4 instead of BSD as it should have. All affected files are copyright D61, so we are free to just update the tag.
=> fix license to BSD for libsel4 files

include/kernel/thread.h
It is possible for consumed time to be larger than domain time.
Signed-off-by: Mitchell Buckley <mitchell.buckley@data61.csiro.au>
=> mcs: update commitTime

src/arch/riscv/c_traps.c
For those wondering, this code was correct when it was written as trap-return instructions were originally specified to clear reservations.  riscv/riscv-isa-manual@03a5e722 broke the link between the privileged architecture and the memory model as part of RVWMO pre-ratification improvements.
=> riscv: Clear reservation state on slowpath exit

src/plat/rockpro64/config.cmake
**Disposition**: Ready to merge.
Allow rockpro64 to be built with MCS. Sets the kernel WCET to 10u.
Sel4test passes when running on a pinebook pro.
CLK_MAGIC and CLK_SHIFT were not set as this platform is not enabled for
32-bit arm.
Sel4test was built and executed using this procedure (this patch was applied on top of the master kernel):
```
mkdir sel4test
cd sel4test
repo init -u https://github.com/seL4/sel4test-manifest.git -b refs/tags/11.0.0
repo sync
cd kernel
git checkout master
cd ../tools/seL4
git checkout master
cd ../..
mkdir build
cd build
../init-build.sh -DPLATFORM=rockpro64 -DSIMULATION=false -DSMP=on -DNUM_NODES=6 -DMCS=on -DLibUtilsDefaultZfLogLevel=0
ninja
cd images
../../tools/seL4/cmake-tool/helpers/make-uimage /usr/bin/aarch64-linux-gnu-objcopy ../elfloader/elfloader …
```
=> rockpro64: Enable MCS

manual/parts/bootup.tex, manual/parts/objects.tex
**Disposition**: Ready to merge.
**Testing performed**: Built the manual and visually inspected it.
I had previously added it to the table but it should be in the
discussion too.
The initial thread's CNode guard size is calculated so that the CNode
resolves the number of bits in the architecture word size.
- Show fields in same order as struct
- Fix name of schedcontrol field
- Fix nodeID field type
=> Manual fix and addition

include/object/reply.h, src/kernel/thread.c, src/object/endpoint.c, src/object/objecttype.c, src/object/reply.c
reply_unlink takes a reply and remove the link between that reply
and its tcb. This link always exists at the call site and the tcb
information is always avaialble, or can be made available.
This commit adds this tcb as an extra argument to aid varification.
Signed-off-by: Miki Tanaka <miki.tanaka@data61.csiro.au>
=> mcs: add tcb argument to reply_unlink

CHANGES, libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h
This ensures that no frames can be mapped that would overwrite the
currently stored VMID for the vspace.
=> aarch64,cortex-a53,hyp: Reduce seL4_UserTop value

libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h
A slot in the top level VSpace page table is used to hold the number of
SMMUv2 ContextBanks that are assigned to a VSpace. This means a
reduction of available virtual addresses at userlevel as the slot cannot
be used for holding regular mappings.
=> smmuv2: Reserve VSpace slot for holding CB count

include/arch/riscv/arch/32/mode/machine.h, include/arch/riscv/arch/64/mode/machine.h
With this and seL4/seL4_tools#41, I can build riscv32 and riscv64 `-DSMP=ON -DPLATFORM=spike -DSIMULATION=ON` and run the subset of non-timer tests with `./simulate -M virt -b 'qemu-system-riscvNN -smp 4'`, although there are a few "Spurious interrupt" messages.
=> riscv/smp: Add missing include

README.md
The GitHub action complain about a 404 error when I push something in my fork. Seems the mailinglist link have changed recently. I think I read something that you updated you servers, so it might be related to this
=> README.md: update links to mailinglists

include/arch/arm/arch/64/mode/machine.h
When running in EL2 the physical counter is in register cntpct_el0, not cntvct_el0
=> Fix MCS+EL2

tools/bitfield_gen.py
This is necessary for the upcoming Isabelle2021 release, but also works with Isabelle2020.
Isabelle2021 sometimes gets further with mask_simps, so this commit
makes them optional. Also removes a duplicate simp-rule warning.
=> bitfield_gen: prep for Isabelle2021

src/kernel/sporadic.c, src/object/schedcontrol.c
This PR is a reduced variant of the larger `Synchronise master kernel and abstract model` PR  from https://github.com/seL4/seL4/pull/256.
It is expected that each commit is addressing a single requirement raised during the verification process.
Based on: 
1199bee: mcs: Fix refill overlap check
ed95cab: mcs: Always use refill_new for round-robin
3a42256: mcs: invokeSchedControl_Configure successful
e91698c: mcs: check lower bounds in ticks
=> Sub PR1 (Synchronise master kernel and abstract model)

include/kernel/sporadic.h, src/object/schedcontext.c, src/object/tcb.c
This PR adds a check to SchedContext_Bind and TCB_SetSchedParams that prevents binding an SC to a thread if the SC is not released and the thread is blocked (On an endpoint, notification or reply object). 
So as to ensure that all TCBs in queues are either faulted, passive, or
have schedulable SCs we cannot allow arbitrary SCs to be bound to TCBs
that are already in queues.
If a TCB is in a queue it should first be removed before having an SC
bound to it.
=>  Sub PR3 (Synchronise master kernel and abstract model)

configs/seL4Config.cmake, libsel4/arch_include/arm/sel4/arch/simple_types.h, libsel4/arch_include/riscv/sel4/arch/simple_types.h, libsel4/include/sel4/simple_types.h, libsel4/include/sel4/types.h, libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/simple_types.h, libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/types.h, libsel4/sel4_arch_include/ia32/sel4/sel4_arch/simple_types.h, libsel4/sel4_arch_include/ia32/sel4/sel4_arch/types.h, libsel4/sel4_arch_include/riscv32/sel4/sel4_arch/simple_types.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/simple_types.h, libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/types.h, libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/simple_types.h, libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/types.h, src/plat/allwinnerA20/config.cmake, src/plat/apq8064/config.cmake, tools/helpers.cmake
This avoids warnings that the files are included multiple times. Currently such warnings are shown for:
- camkes-tool/libsel4camkes/gen_config/sel4camkes/gen_config.h
- kernel/gen_config/kernel/gen_config.h
- libsel4/gen_config/sel4/gen_config.h
=> use include guards for auto generated files

libsel4/include/sel4/config.h
This option was legacy from when autoconf.h wasn't always present in the
include path. Now it causes incorrect configuration options.
=> Remove HAVE_AUTOCONF guard in sel4/config.h

manual/parts/cspace.tex
A CPointer addressing a CNode is accompanied by a depth limit. The manual describes the depth limit as the length of a big-endian prefix of the CPointer, whereas the specification and implementation treat the depth limit as the length of a big-endian suffix.
This commit corrects the manual to match the specification.
[1] https://github.com/seL4/l4v/blob/dd6529f520a25328469fc44cfd54f3b29ffd75cc/spec/abstract/CSpace_A.thy#L243
[2] https://github.com/seL4/l4v/blob/dd6529f520a25328469fc44cfd54f3b29ffd75cc/spec/haskell/src/SEL4/Kernel/CSpace.lhs#L128
[3] https://github.com/seL4/seL4/blob/d6b83163b55c20ad146620fe82e261221d321316/src/kernel/cspace.c#L126
=> manual: Correct description of CNode addressing

src/plat/pc99/config.cmake, src/plat/pc99/machine/hardware.c
This option allows a static definition of the TSC frequency. This allows
a kernel to use a known value if the platform doesn't provide access to
an appropriate MSR for reading it during startup. If this config is set,
the kernel won't try and estimate the TSC frequency by running the PIT
for 200ms during startup.
=> pc99: Add CONFIG_PC99_TSC_FREQUENCY config option

src/plat/zynqmp/overlay-zynqmp.dts, src/plat/zynqmp/overlay-zynqmp32.dts
The Linux drivers use duplicate interrupts in the device tree; however,
seL4 drivers do not. The duplicate interrupts cause issues while using
templates in CAmkES applications. This commit adds an overlay which
overwrites the duplicate ethernet interrupts.
=> zynqmp: update ethernet interrupts in overlay

config.cmake, include/util.h, src/arch/riscv/config.cmake, src/util.c
A previous commit (9ec5df5f) to provide more efficient CLZ (count leading zeros) and CTZ (count trailing zeros) removed the `__clzsi2` and `__ctzsi2` symbols, due to a misunderstanding of the types of these and other library functions expected by GCC's intrinsics. 9ec5df5f broke the riscv32 build.
This commit corrects the misunderstanding:
- `__clzsi2` and `__ctzsi2` are reinstated with correct types.
- The types of `__clzdi2` and `__ctzdi2` are corrected.
- `__clzti2` and `__ctzti2` are removed, since seL4 contains no compiler intrinsics that would require them.
- `clzl` and `ctzl` dispatch to the appropriate library functions based on the size of `unsigned long`.
- Configuration options are updated to ensure that the library functions are included in the kernel binary only when needed.
=> riscv: fix CLZ and CTZ for riscv32 builds

src/arch/arm/machine/l2c_310.c, src/drivers/serial/config.cmake, src/plat/imx6/config.cmake, src/plat/imx6/overlay-nitrogen6sx.dts, tools/dts/nitrogen6sx.dts, tools/hardware.yml, tools/hardware/irq.py
Patch is part of a series of patches to add support for the i.MX6 Nitrogen6_SoloX board
* https://github.com/seL4/camkes-tool/pull/57
* https://github.com/seL4/seL4_tools/pull/53
* https://github.com/seL4/util_libs/pull/69
In addition to `CONFIG_PLAT_NITROGEN6SX` this also adds `CONFIG_PLAT_IMX6DQ` and `CONFIG_PLAT_IMX6SX` internally depending on the i.MX6 board target. This allows differentiating between the SOCs  i.MX Double/Quad and i.MX SoloX, which makes much more sense in some cases than using a board selector like `CONFIG_PLAT_NITROGEN6SX`, just because this happens to be a board using this SOC.
=> Add i.MX6 Nitrogen6_SoloX board

config.cmake, src/object/schedcontext.c, src/plat/odroidc2/config.cmake
Fixes for the `TIMER_PRECISION` and consumed time returned via the syscalls reporting consumed time.
=> Fixes for accounting time in MCS

src/plat/imx6/config.cmake
Unfortunately, the "6" in platform name's C define name got lost somewhere in some merges. This create a nasty misalignment in the names now. So far, this is not used anywhere in the seL4 codebase, but for merging https://github.com/seL4/util_libs/pull/78 the name must be fixed.
=> Nitrogen6SX: align name C define name

src/object/schedcontext.c
This is makes it easier to avoid undefined behaviour in the proofs.
=> Move null check to start of schedcontext decode

include/arch/arm/arch/64/mode/machine/timer.h
Actually divide by KHz frequency when on a platform that uses a clock that does not have an integer MHz frequency for aarch64.
=> mcs: Fix conversion of ticks to us on aarch64

src/arch/riscv/traps.S
Move syscall and fastpath checks after interrupt and exceptions.
Exceptions were being interpreted as null-syscalls.
Remove duplication for return address.
Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>
=> risc-v: reorganise traps.S

src/object/schedcontext.c
If one thread replies on behalf of the a thread to which an SC is donated and that thread is in the release queue, that thread must be removed from the release queue when the SC is returned.
=> mcs: removed donator from release queue

CHANGES, include/kernel/sporadic.h, include/object/structures.h, libsel4/include/interfaces/sel4.xml, libsel4/include/sel4/constants.h, libsel4/include/sel4/sel4.h, libsel4/include/sel4/virtual_client.h, manual/parts/threads.tex, src/kernel/thread.c, src/object/endpoint.c, src/object/notification.c, src/object/schedcontext.c, src/object/schedcontrol.c
This PR is a variant of https://github.com/seL4/seL4/pull/312 that only focuses on the changes to introduce a flag on scheduling context objects to control sporadic refill behavior.  The new option allows a sporadic SC to accumulate any time missed while it is preempted by a higher priority task.
=>  Sub PR2.1 (Synchronise master kernel and abstract model)

libsel4/include/sel4/simple_types.h
Turns out we need a  `SEL4_PRIx_word` also to print values in hex. So this adds it and makes `SEL4_PRI_word` use "SEL4_PRIu_word" then. Furthermore there is `_seL4_word_fmt`, which can be used to define further custom types.
=> allow specific printf() formatting for seL4_Word

include/arch/arm/arch/64/mode/machine.h
See: [SELFOUR-2830] for details.
On SMP configuration the `ic ialluis` instruction must be used
to ensure the I-cache on all cores is invalidated.
[SELFOUR-2830]: https://sel4.atlassian.net/browse/SELFOUR-2830
=> Correctly invalidate I-cache on aarch64 SMP [SELFOUR-2830]

src/object/notification.c
This should not change the behavior of this function in any way but makes the order of operations more similar to other locaitons in the code in a manner that eases verification.
Original PR by @michaelmcinerney
=> mcs: move maybeReturnSc to end of receiveSignal

include/object/notification.h
When determining whether a SC donated from the notification should be
returned, we must ensure not to try and return a NULL SC to a
notification with not bound SC.
This could occur when a passive server performs a NBSendWait/NBSendRecv
with a notification in the receive phase, where the SC for the receiver
was returned in the send phase and the notification has no bound SC.
Signed-off-by: Curtis Millar <curtis.millar@data61.csiro.au>
=> mcs: Only unbind extant donated ntfn sc

src/object/schedcontext.c
We must ensure that the current thread is not already yielding to another thread when it makes a YieldTo invocation. This should never happen as we should always cancel any YieldTo before returning to user-level, however we cannot prove this invariant at this time.
@MitchellBuckley and @michaelmcinerney may have some input on the need for this change.
=> Current thread must not yield to multiple threads

include/kernel/thread.h, src/api/syscall.c, src/model/preemption.c
This introduces a fix from verification, ensuring that we don't charge time to an unconfigured SC, and a change to ease verification efforts.
Rather than perform an `checkBudget` inside a preemption point, we only check whether `checkBudget` would fail and raise an exception if it would. To ensure the check is the same in both `preemptionPoint` and `checkBudget`, the check has been moved to its own function.
If we do move ahead with #312, which would employ only tail merging for splitting rather than merging at the head in some cases, the need to check for a head split would be removed and `isSufficientAndSplittable` can be replaced with a `refill_sufficient` check in both locations.
=> Defer charging budget after preemption points

src/object/objecttype.c
Deleting a reply object that is linked to a `BlockedOnReceive` thread is unusual behaviour and it's not clear what the expected behaviour should be. Previously, `finaliseCap` called `replyUnlink` but this sets the thread to `Inactive` while leaving it in the endpoint's queue, which breaks the invariants. Calling `cancelIPC` at least guarantees that the system ends up in a consistent state.
There are potentially other options here, but it is strongly preferred that we take this approach during the current verification work. We'll be happy to come back to this decision if necessary once we're finished.
=> mcs: cancel IPC when finalising reply caps

src/object/objecttype.c
Fix issues where scheduling context is dereferenced after it is removed
from the associated TCB.
=> mcs: Fix derefrence of scheduling context

.github/workflows/pr.yml
This extends the matrix to use the now-enabled `L4V_FEATURES` input.
=> Add MCS to the preprocess check

include/arch/arm/arch/machine/capdl.h, include/arch/riscv/arch/machine/capdl.h, include/arch/x86/arch/machine/capdl.h, include/machine/capdl.h, src/api/syscall.c, src/arch/arm/32/config.cmake, src/arch/arm/32/machine/capdl.c, src/arch/arm/64/config.cmake, src/arch/arm/64/machine/capdl.c, src/arch/riscv/config.cmake, src/arch/riscv/machine/capdl.c, src/arch/x86/32/machine/capdl.c, src/arch/x86/64/config.cmake, src/arch/x86/64/machine/capdl.c, src/arch/x86/config.cmake, src/arch/x86/machine/capdl.c, src/config.cmake, src/machine/capdl.c
Replace capDL() by a generic debug_capDL() where all architectures are supposed to provide an implementation or print an error.
=> define generic debug_capDL() function

src/arch/riscv/head.S
An aditional two parameters for the dtb were added to the init_kernel
function call in the elfloader. The corresponding _start entry
in the kernel was never updated.
Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>
=> risc-v: fix register bug

src/arch/x86/32/config.cmake, src/arch/x86/32/machine/capdl.c
This is a quick bug-fix to fix a red build in CI.
Although the functions aren't implemented properly, this is a stop gap
issue to prevent the linker from raising problems about missing
references to various platform-specific capDL printing functions.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> ia32: Fix linker errors with capDL printing

include/arch/arm/armv/armv8-a/64/armv/vcpu.h
Like `SCTLR`, `CNTV_CTL` is switched to/from hardware when we enable/disable the VCPU, so it must be read from a saved VCPU context when that VCPU isn't active.
`CNTV_CTL` is switched to/from hardware by `{save,restore}_virt_timer`.
=> arm-hyp: read cntv_ctl from saved context when necessary

src/arch/arm/32/kernel/vspace.c, src/arch/arm/64/kernel/vspace.c
A previous update added a disjunct to an `if` condition outside the
existing `unlikely` branch hint. This commit extends the hint to the
full `if` condition.
=> arm: fix `decodeARMMMUInvocation` branch hint

src/plat/pc99/linker.lds
This is to work around an issue in a variant of syslinux that treats a
PHDR segment as distinct from a PT_LOAD segment and rejects an ELF if
the two segments are overlapping.
=> pc99: Remove PT_PHDR segment from linker script

src/drivers/serial/config.cmake, src/drivers/serial/imx-lpuart.c, tools/hardware.yml
Add support the i.MX low-power UART. This is available on
chipsets such as i.MX8QXP.
Note: This is a preliminary patch in advance of providing
full support for the i.MX8QXP platform.
=> Add support for iMX LP UART

libsel4/include/sel4/constants.h
The scheduler context flags enum should not be inside assembler-related
files.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> trivial: Extend !__ASSEMBLER__ preprocessor flag

configs/seL4Config.cmake, src/arch/arm/config.cmake
- Don't create `CONFIG_ARCH_AARCH32` on every platform and architecture (even if it is off, it is quite confusing to see it)
- Remove `KernelSel4ArmHypAarch32`, seems there is no special need for it and `KernelSel4ArchArmHyp` can also be used
=> CMake: cleanup KernelSel4ArchArmHyp

configs/seL4Config.cmake
KernelAArch64SErrorIgnore needs to be saved into the cache in
seL4Config.cmake if it is set by any platform's config.cmake.
=> cmake: Apply KernelAArch64SErrorIgnore setting

.github/workflows/manual.yml
This will build a PDF of the reference manual in draft mode
and upload that PDF as a build artifact.
(expected to fail currently on master, but to work after #395)
=> github: add a GitHub action to build the manual

config.cmake
Enforcing the std channels seems to conflict with Jenkins CI, we don't see any error messages then. I remember that we had a discussion here before that on some other systems this enforced redirectin is needed - but this make me wonder why the std channels do not work there and if this is the issue to be resolved then.
=> CMake: don't enforce std channels

.github/workflows/xml_lint.yml
This will lint everything called `sel4*.xml` in `libsel4` and should trigger only on changes to those files.
Closes seL4/ci-actions#70
=> github: CI action to lint seL4 IDL files

include/arch/arm/armv/armv7-a/armv/context_switch.h, include/arch/riscv/arch/machine.h, include/machine.h, include/plat/pc99/plat/32/plat_mode/machine/hardware.h, include/plat/pc99/plat/64/plat_mode/machine/hardware.h, src/arch/arm/32/kernel/vspace.c, src/arch/arm/32/object/objecttype.c, src/arch/arm/64/kernel/thread.c, src/arch/arm/64/kernel/vspace.c, src/arch/x86/32/kernel/vspace.c, src/plat/tk1/machine/smmu.c
This updates the code such that it assumes that the kernel ELF is not accessed via the physical memory window and instead has a dedicated region into which it is mapped. This has the most noticeable impact for aarch32 which has a verified configuration that *does* access the kernel via the physical memory window.
This will allow configurations with the kernel imaging API to function correctly but will not allow the API to be configured without a dedicated mapping window.
=> Assume seperate distinct kernel ELF mapping on all platforms

.github/workflows/cparser.yml
This action runs the verification C parser on the main kernel
configurations to check that the code is in the C verification subset.
=> github: run C parser on push/PR

README.md, SECURITY.md
This adds a simple vulnerability disclosure policy, loosely based on:
- Disclose.io materials.
- The OWASP Vulnerability Disclosure Cheat Sheet.
I didn't include the typical safe harbour provisions, since I guess that might need legal advice and/or board approval.
Once we agree on the content, I'll make similar pull requests in whichever other repositories we want this to cover.
=> meta: add vulnerability disclosure policy

src/object/schedcontrol.c
The flags argument means that the call requires 2 time args (period, budget) and 3 words (extra refills, badge, flags).
=> SchedControl_ConfigureFlags requires 3 + 2 args

src/arch/riscv/kernel/boot.c
=> trivial: use proper naming in comment

README.md
The CII best practise badge must be displayed for the crowd funding platform.
The other badges are there to make CI status easier to see at a glance. They will become more useful once more test are on GitHub Actions.
=> add CII badge + CI badges + some README cleanup

.github/workflows/sel4test-sim.yml
This is a slight superset of the simulations that Bamboo runs (adds armv8a).
See https://github.com/seL4/ci-actions/blob/master/sel4test-sim/builds.yml for what actually gets tested. The matrix in the GitHub action selects subsets of these to run in parallel.
=> Add GitHub action for sel4test simulation runs

CHANGES, configs/seL4Config.cmake, libsel4/sel4_plat_include/odroidc4/sel4/plat/api/constants.h, src/arch/arm/config.cmake, src/plat/odroidc4/config.cmake, src/plat/odroidc4/overlay-odroidc4.dts, tools/dts/odroidc4.dts, tools/dts/update-dts.sh
This adds support for the ODroidC4. The ODroidC4 is just a beefier ODroidC2 with some bits moved around. The devices we care about here are all essentially the same.
Related: https://github.com/seL4/util_libs/pull/97 and https://github.com/seL4/seL4_tools/pull/95
=> Adds support for the arm Cortex A55 and ODroid C4

src/arch/riscv/config.cmake
The top phys addr is exclusive, not inclusive. On 64-bit platforms there is a trivial way to fix this as long as the whole address space is never used. For 32-bit platforms the fix will be more complicated, so this is postponed.
See also https://github.com/seL4/seL4/pull/376 where this got fixed on ARM platforms.
=> Set KernelPaddrUserTop correctly on RISC-V platforms

src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c
Log an explicit error message for everything that can fail during boot. This is helpful for debugging, e.g. when porting the kernel to a new platform or changing the system configuration.
=> risc-v/boot: verbosely log boot errors

.github/workflows/proof.yml
This action will run the C proofs when the label `proof-test` is added to a pull request. Intended to be used when the preprocess test has failed and the PR is ready to check proofs.
The idea is that this replaces the ssrg-bamboo bot for proofs.
This test should run much faster than a full proof test board, with the same predictive power. It will likely need a bit longer on the first run, but after that use cached proof images for things that have not changed.
=> C proof check for labelled PR

.github/workflows/proof.yml
The SimplExportAndRefine session is one of the steps of binary verification and only available for ARM and RISCV64.
=> github: run SimplExportAndRefine conditionally

include/kernel/boot.h
These defines seem redundant, they exist the architecture specific `bootinho.h` already and this seems the better place due to the subtle differences
=> remove redundant defines

README.md
The badge name shows as `seL4Test`, which would imply also the hardware tests. We do intend to include them in that job group in the future, so I'd say it's fine to leave as is for a few weeks until that is done.
=> README: add badge for simulation test

.github/workflows/proof.yml, .github/workflows/sel4test-sim.yml
The action builds `sel4test` for all hardware platforms currently tested in bamboo, and leaves generated images as artifacts that a later test run stage can pick up.
As for the other sel4test actions, the main configuration is in [seL4/ci-actions](https://github.com/seL4/ci-actions/blob/master/seL4-platforms/platforms.yml), that build matrix in here only determines what gets built in parallel, and potentially which combinations to leave out completely.
At the moment, we do all armv8 in one sequential run, which takes about 30min. If that is too annoying in the longer run, I can look at splitting these up as we have on Bamboo into 2 or three parallel runs. This is not necessarily faster, since GH is currently restricted to 20 parallel builds per repo.
The action  is triggered on push to …
=> add GitHub action for hardware builds

include/kernel/boot.h, src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c, src/arch/x86/kernel/boot.c, src/kernel/boot.c
- move `create_untypeds()` to generic code.
- merge `create_device_untypeds()` and `create_kernel_untypeds()` into `create_untypeds()` to simplify the code.
=> boot: move create_untypeds() to generic code

.github/workflows/sel4test-hw.yml, README.md
This PR adds the trigger that replaces Bamboo hardware tests. It runs the same general sel4test setup with the UNSW machine queue, just triggered from GitHub.
The current set of available boards is fairly small, more boards will come online over time.
The test runs on push to the `master` branch or on PR when explicitly labeled with `hw-test`.
See also seL4/ci-actions#135
=> Hardware tests triggered from GitHub

src/arch/riscv/kernel/boot.c, src/arch/x86/kernel/boot.c, src/kernel/boot.c
Align the parameter naming within each architecture's file and also across architectures.
=> clarify that parameter is initial thread's region

include/arch/arm/arch/machine.h, src/arch/arm/32/kernel/vspace.c, src/arch/arm/64/kernel/vspace.c
This fixes a correctness and security issue where uncached user mappings might see old data from before the clearMemory operation.
See also the discussion on GitHub issue #481 and corresponding seL4/sel4test#45
=> arm: flush cache to RAM on retype reset

include/api/types.h, include/arch/arm/arch/32/mode/machine/fpu.h, include/arch/arm/arch/64/mode/machine/fpu.h, include/arch/riscv/arch/machine/fpu.h, include/arch/x86/arch/32/mode/machine.h, include/arch/x86/arch/64/mode/machine.h, include/arch/x86/arch/kernel/traps.h, include/basic_types.h, include/model/statedata.h, src/arch/arm/c_traps.c, src/arch/arm/kernel/boot.c, src/arch/arm/machine/gic_v3.c, src/arch/x86/c_traps.c, src/arch/x86/object/vcpu.c
- Replace the macro `SMP_TERNARY(getCurrentCPUIndex(), 0)` by the much simpler macro `CURRENT_CPU_INDEX()` that does the same.
- define macro `SEL4_WORD_CONST()`. `CURRENT_CPU_INDEX()` is supported to return a `word_t`. The C parser from the verification toolchain requires declaring `word_t` constants without casting integer values to `word_t`.
- The field `ksKernelEntry.core` always exists, ensure it is properly set on non-SMP configurations also.
=> prefer macro CURRENT_CPU_INDEX()

include/kernel/boot.h, src/kernel/boot.c
`insert_region()` is not use outside of `boot.c`.
=> boot: make insert_region() static

include/arch/arm/arch/machine.h, include/arch/riscv/arch/kernel/traps.h, include/arch/riscv/arch/machine.h, src/kernel/boot.c
Some code clenup:
- trivial: add comments about empty functions: Add a comment to clearly state the functions are empty on purpose, but they still need to be provided to support the generic code flow.
- arm: remove obsolete function setInterruptMode(). The function setInterruptMode() is no longer in use, setIRQTrigger() is used instead.
- trivial: remove superfluous empty lines
=> cleanup: comment empty functions, remove obsolete functions

CMakeLists.txt, src/arch/arm/common_arm.lds, src/arch/riscv/common_riscv.lds, src/plat/pc99/linker.lds
Follow up from a comment from @kent-mcleod at https://github.com/seL4/seL4/pull/421#issuecomment-874375725
With gcc < v10, global variables defined but not initialized get put into the COMMON section. If this section is not declared explicitly, these variables end up at the end of the .bss, which wasts a page.
=> risc-v: add COMMON section to linker script

.github/workflows/preprocess-deploy.yml, README.md
Automatically keep verification-manifest in sync with preprocess-equivalent changes.
See also seL4/ci-actions#144
=> github: deploy verification-manifest on preprocess

src/arch/arm/32/head.S, src/arch/arm/64/head.S, src/arch/riscv/head.S, src/arch/riscv/traps.S
* remove unused references
* don't return to asm code during boot
=> ARM/RISC-V: boot documentation improvements and cleanup

.github/workflows/sel4test-deploy.yml, .github/workflows/sel4test-sim.yml
This commit pulls out a separate workflow for sel4test (simulation + hardware runs) on pushes to master, and deploys a new default.xml to sel4test-manifest when the test is successful.
Also puts the machine queue run into a concurrency group, which means only one of these will run at the same time. This should reduce contention on the the machine queue and finish individual tests more quickly. If a test is already running, new tests will remained in "queued" state until the running one is done. If there is already a queued test, the previously queued test is cancelled and the latest one is queued. This means only the most recent commit will be deployed to the manifest if previous tests haven't started yet (but previous tests will finish and deployed if they have already started).
This …
=> github: separate sel4test for deployment on master

include/kernel/sporadic.h
Easier to check this explicitly than prove the invaraint.
=> mcs: Explicitly check that sporadic scs are active

include/kernel/sporadic.h
Turns out the invariant 17109eb8c986cd0ac refers to (discussed in #476) is hard to prove because it is not true, and the runtime check is necessary. This assertion fails in sel4test SCHED_CONTEXT_0003 (Basic api_sc_bind/UnbindObject testing).
=> mcs: sc_active not always true in sc_sporadic

include/arch/riscv/arch/machine.h, src/arch/riscv/machine/hardware.c
The L2 cache handling functions were copied from the ARM code in the initial port,but they are not used on RISC-V. Remove them from the code base, they can be brought back if a platform has an L2 cache that needs to be maintained.
Is there any seL4 RISC-V code lurking in private repos that uses this, e.g. for HiFive/Polarfire?
=> risc-v: remove unused L2 cache functions

src/arch/riscv/common_riscv.lds
Is there any explanation what this is for?
=> risc-v: don't add 8 bytes space at end of bss

include/kernel/thread.h, src/kernel/thread.c
As Curtis said: this removes the operations that trigger a reschedule or reprogram the timer from `preemptionPoint` to ensure the relevant state updates in the proof occur where they are easier to verify.
This simplifies and supersedes #480. The idea is that it is simpler and easier in both proof and code to do the check once after the main kernel event is finished, and on the path that has to deal with checking time and scheduling anyway.
The preemption point and all other places that call `updateTimestamp` now just flag that the domain will have to be changed (`ksDomainTime = 0`) and don't change the scheduler action/timer directly, so the proofs that depend on the scheduler action only have to deal with that state update once, but still before anything that depends on it.
=> mcs: Remove domain time check from preemptionPoint (v2)

include/arch/arm/arch/machine.h, include/arch/riscv/arch/machine.h, src/arch/arm/kernel/boot.c, src/arch/arm/machine/hardware.c, src/arch/riscv/kernel/boot.c, src/arch/riscv/machine/hardware.c
* The python code generator ensures avail_p_regs always exists, so it can be used directly.
* `dev_p_regs` does not exist anymore, so there is no need for the helper functions.
=> boot: reduce amount of helper functions

src/kernel/boot.c
`MAX_NUM_FREEMEM_REG` is used to define the number of elements of the `array ndks_boot.freemem[]`. However, in the code iterating over the elements, using the macro `ARRAY_SIZE()` is more straight forward and avoids pulling in unnecessary dependencies.
=> use ARRAY_SIZE to avoid implicit assumptions

tools/cpp_gen.sh, tools/dts/update-dts.sh, tools/kernel_pylint.sh, tools/kernel_xmllint.sh, tools/xmllint.sh
This implements GitHub PR #115 on the current repo state. `/usr/bin/env` is already used for other (cmake/python/etc) invocations, and this PR brings bash/sh into line with that for slightly improved portability.
=> tools: use /usr/bin/env for bash/sh invocation

src/kernel/boot.c
Print reserved and available memory regions during boot, this makes porting and debugging a bit easier.
=> boot: print reserved and available memory regions

src/fastpath/fastpath.c
clang-11 warns "converting the enum constant to a boolean". The comparison generates the same code, since the expression can be evaluated at compile time (I checked the objdump).
This is in preparation for upgrading the docker containers to clang-11 and gcc-10 (see initial discussion on seL4/seL4-CAmkES-L4v-dockerfiles#39 -- debian bullseye is released, which means our docker build no longer works).
=> fastpath: placate clang-11

src/arch/x86/idle.c
The idle_thread() cannot perform any stack manipulations since it runs in the idle thread TCB context. Declare the function with the naked attribute, to ensure that the compiler always eliminates the function prologue. Previously we rely on the -O2 optimization flag for this, which on certain compilers may not guarantee that the function prologue gets eliminated.
This is in response to a kernel crash on ia32 when compiled with clang 12.0.1. See  https://sel4.discourse.group/t/kernel-crash-on-x86-but-not-on-x86-64/398
=> x86: Always eliminate function prologue for idle_thread()

libsel4/sel4_plat_include/tqma8xqp1gb/sel4/plat/api/constants.h, src/plat/tqma8xqp1gb/config.cmake, src/plat/tqma8xqp1gb/overlay-tqma8xqp1gb.dts, tools/dts/tqma8xqp1gb.dts
TQ Group produces a system-on-module family called TQMa8Xx.
The user manual for this SoM is available here:
https://www.tq-group.com/filedownloads/files/products/embedded/manuals/arm/embedded-modul/TQ-Socket/TQMa8Xx/TQMa8Xx.UM.0104.pdf
This SoM comes in a number of different configurations.
The specific NXP SoC used, and the amount of memory are both configurable.
The TQMa8XQP is the part number for the TQMa8Xx family configured with
the i.MX 8QuadXPlus SoC.
The datasheet for the SoC is available here:
https://www.nxp.com/docs/en/data-sheet/IMX8QXPAEC.pdf
In addition to the SoC being configurable the amount of SDRAM
on the SoM is also configurable.
The support provided in this PR is specifically for the TQMa8XQP
configured for 1GiB of memory. Note: Actual usable memory available
to the …
=> Add support for the TQMa8XQP 1GiB module

libsel4/sel4_plat_include/tqma8xqp1gb/sel4/plat/api/constants.h
`#if` fails if the symbol is not defined, at least for the older tool chain currently in docker.
=> trivial: use #ifdef instead of #if

LICENSE.md, README.md
Adding a link to Gernot's blog post that explains what GPL on seL4
means for other code. This is mainly intended for people who aren't
that familiar with what all of these licenses mean.
Closes #524
=> docs: add link explaining license implications

src/arch/x86/kernel/ept.c
Credits for this one should go to clang-11, which correctly flags that the big `||` always yielded true and was not doing what was intended.
This means, previously the only possible cache attribute for EPT was `EPTWriteBack`.
=> vtx: fix EPT cache attribute setting

src/plat/pc99/machine/ioapic.c
CONFIG_MAX_NUM_IOAPIC can end up being 0 when the kernel is configured as PIC-only. This code is then unreachable, but gcc-10 can't figure that out and fails on array-out-of-bounds access (which would be correct if the code were reachable).
=> x86 ioapic: make sure array is non-empty

include/kernel/boot.h, src/kernel/boot.c
- The field `slot_pos_max` from `ndks_boot` is not needed, the value stored there is the constant `BIT(CONFIG_ROOT_CNODE_SIZE_BITS)`.
- Improve the error message if the limit has been reached
=> boot: remove ndks_boot.slot_pos_max

CMakeLists.txt, gcc.cmake
When using CMake to only build the kernel, an install target is now
provided to copy important outputs into an installation directory.
Currently only the following files are installed:
- ./bin/kernel.elf: Location of kernel.elf binary
- ./kernel_Config/include: The include root for the kernel_Config
interface library
- ./libsel4/include: The include root for libsel4
- ./libsel4/src: The c source files for the libsel4 library
- ./libsel4/sel4_Config/include: The include root for the sel4_Config
interface library
- ./libsel4/autoconf/include: The include root for the autoconf interface
library
To build and install this project to an installation directory should
now only require the following from a clean build directory:
```
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=<path-to-install> …
```
=> CMake: Add support for `cmake install <dir>` cmd

include/bootinfo.h, src/kernel/boot.c
- simplify the boot code by removing the trivial macros BI_PTR() and BI_REF().
- clarify assumptions that boot info is one page
=> cleanup code using BI_PTR(), use BI_FRAME_SIZE_BITS instead of seL4_PageBits

configs/seL4Config.cmake
Verify that KernelArch and KernelWordSize have been correctly
set after including the platform cmake files.
=> Add additional cmake checks

src/arch/arm/64/idle.c, src/drivers/serial/meson-gx-uart.c
This ensures the hardware reset is triggered when the kernel faults ensuring that the hardware is rebooted rather than causing the hardware to hang requiring a full power down (which can't currently be performed remotely).
This only needs to be added to the AOS branch of the kernel.
Signed-off-by: Curtis Millar <curtis@curtism.me>
=> Reset SBC on kernel fault for AOS

libsel4/arch_include/x86/sel4/arch/types.h, src/arch/x86/kernel/ept.c
In x86, EPT and normal mappings have different cache attributes. This
commit adds an enum for the EPT attributes.
Signed-off-by: Chris Guikema <chris.guikema@dornerworks.com>
=> libsel4: add EPT attributes

include/arch/riscv/arch/machine.h
This fixed that issue that if `KernelSetTLSBaseSelf` is enabled on RISC-V, the compilation fails with 
```
...src/api/syscall.c:320:20: error: void value not ignored as it ought to be
320 |             return Arch_setTLSRegister(tls_base);
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> risc-v: fix signature for Arch_setTLSRegister()

src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c
Addresses parts of https://github.com/seL4/seL4/issues/540
- On ARM systems, the UART must be set up first before any error messages are visible. Move the user image location check after the platform init that brings up the UART.
- Add the user image location check on RISC-V systems also.
- Make the error message more verbose to clearly show the problem.
=> boot: improve user image location check

manual/parts/threads.tex, src/object/schedcontext.c
Before, binding a scheduling context to a TCB was not allowed if the
SC was bound to a notification object. Also, binding a SC to a NF was
not allowed if that scheduling context was already bound to a TCB.
Without these restriction it is much easier to move scheduling contexts
around: In effect having a SC bound on both the TCB and a NF acts as if
the thread is running on a donated SC which will be returned when the
tasks calls Recv/Wait, which is done by maybeReturnSchedContext().
This greatly simplifies startup and time-out exception handling for
passive threads having a NF with a SC bound to it.
Signed-off-by: Indan Zupancic <Indan.Zupancic@mep-info.com>
[Edit for test:
Test with seL4/seL4test#50 ]
=> Allow Lazy SC Rebind

.github/workflows/compilation-checks.yml
Since the build system defaults to python3 now, these have not worked as advertised in a while now (they have test py3 twice).
Needs to be merged after seL4/ci-actions#153
=> github: drop python2 tests

include/object/structures.h
Since commit e18e32e2, "Allow Lazy SC Rebind", this is not true anymore.
Signed-off-by: Indan Zupancic <Indan.Zupancic@mep-info.com>
=> Trivial: Remove now incorrect comment

src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c
Comparing the RISC-V and ARM code, it seems on RISC-V the BKL should also be taken once all cores are up - just to play safe.
=> boot/risc-v: grab BKL on primary core for SMP

config.cmake, src/plat/qemu-arm-virt/config.cmake
Check the return value from execute_process calls and fail
with an appropriate message.
This makes debugging of cmake failures much easier.
=> Ensure execute_process is error checked

CMakeLists.txt
python2 is not used in the kernel build anymore so the tool
definition is unnecessary.
python2 is also end-of-line so there is no reason to think
we would ever depend on it again.
=> Remove unused PYTHON tool definition

src/arch/x86/kernel/boot_sys.c
In x86/boot_sys.c, we output a warning when `multiboot_mmap_length`
exceed limit. So we should correct its value after the `printf`.
close: #177 
Signed-off-by: laokz <laokz@foxmail.com>
=> trivial: fix warning of `multiboot_mmap_length`

src/plat/qemu-arm-virt/config.cmake
Low version QEMU dump dts not have intc location information
and make subsequent generate dtb failed.
Error information:
Reference to non-existent node or label "/intc@8000000"
So when the QEMU version does not meet the requirements there
should be FATAL_ERROR to notice user early and immediately exit
Signed-off-by: Qiao Yongchang <qiaoyongchang@gmail.com>
=> Change QEMU version check to FATAL_ERROR

include/arch/arm/arch/bootinfo.h, include/arch/riscv/arch/bootinfo.h, include/arch/riscv/arch/machine/hardware.h, src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c
On AARCH32 there is a special need for an ASID region. Since no other architecture needs this mechanism, handle this within the AARCH32 specific code and keep the generic code clean.
=> boot: don't enforcing defining MODE_RESERVED

src/kernel/boot.c
Previously, the case where there was no memory region large enough for
the root server objects was unhandled. The loop termination condition
(i>=0) was trivially true for all values of the loop variable. This
commit fixes this by making the loop variable signed, and adding a
failure case.
It also simplifies away some conditionals that were guaranteed to be
true, and adds some clarifying comments.
Co-authored-by: Axel Heider <axelheider@gmx.de>
Signed-off-by: Matthew Brecknell <matthew@brecknell.net>
=> boot: handle failure to find root server memory

include/arch/arm/arch/32/mode/types.h, include/arch/arm/arch/64/mode/types.h, include/arch/arm/arch/types.h, include/arch/x86/arch/32/mode/types.h, include/arch/x86/arch/64/mode/types.h, include/arch/x86/arch/types.h
Moving the type checks avoid the need for conditional compilation. This also allows simplifying some include file dependencies.
=> move type checks to mode/types.h

src/arch/riscv/kernel/boot.c
The cast does not exist in the ARM version of this code either. Both `vptr_t` and `paddr_t` ars aliases for `word_t`, so this is safe at the moment. If this ever changes and `vptr_t` gets a smaller size than `paddr_t`then I'd expect the compiler to issue a warning here without the cast, so we will catch this. With the cast in the code we silence such a compiler warning, which seems undesired.
=> boot: remove unnecessary cast

src/plat/rockpro64/config.cmake
`KernelArmPASizeBits40` is enabled by the generic code automatically if `KernelArmCortexA53` is set.
=> cmake/rockpro64: remove unnecessary configuration

.github/workflows/proof.yml
The proofs have switched to a new Isabelle version.
=> github/proofs: update to Isabelle2021

include/arch/arm/arch/machine.h, include/arch/riscv/arch/machine.h, include/arch/x86/arch/machine.h, include/plat/pc99/plat/machine/interrupt.h, src/api/syscall.c
PC99 is the only platform that uses `Arch_finaliseInterrupt()`. There seems no need to have this explicit function, the necessary things can be done in `ackInterrupt()` also, which is architecture or platform specific anyway.
=> cleanup explicit function Arch_finaliseInterrupt()

CHANGES, src/arch/arm/armv/armv7-a/user_access.c
The KernelArmExportPTMRUser and KernelArmExportVTMRUser options for
enabling user access to the generic timer were previously only supported
on aarch64 but are now supported on aarch32 also.
=> arm,generic_timer: Add config user access on 32bit

src/arch/arm/kernel/boot.c, src/arch/x86/kernel/boot.c, src/arch/x86/kernel/boot_sys.c, src/kernel/boot.c, tools/hardware/config.py, tools/hardware/utils/memory.py
- On x86 there was some device UT being created for a region that was intended to be reserved because of an incorrect extra call to `reserve_region()`
- On aarch32 if the user image was loaded into a region outside of the kernel memory window, then the kernel would create device untypeds as well as frame objects for the same memory.
- The last page of memory in the kernel window was being rounded off and not given to user level. It's possible to give smaller UT instead though. (It may even be possible to just allow the last page to be given anyway, but that could be a future change).
- A PPTR_TOP restriction in create_untypeds doesn't make sense as the bitfield code would only error if the address was non-canonical which wouldn't be a valid region and have been excluded before hand …
=> Tidy up some untyped creation edge cases in boot code.

src/plat/qemu-arm-virt/config.cmake
Check if QEMU_OUTPUT_MESSAGE is empty before the STRIP
If no error in the previous qemu test command, the output
message is empty (QEMU_OUTPUT_MESSAGE), then the STRIP
will fail on empty input. Then, if it is empty do not
run STRIP.
Signed-off-by: Juan Pablo Ruiz <juanpablo@ssrc.tii.ae>
=> qemu-arm-virt: fix in cmake for STRIP

src/kernel/boot.c
Print detailed error messages to make porting and debugging easier.
=> boot: add more error messages

.github/workflows/sel4test-deploy.yml, .github/workflows/sel4test-hw.yml
This uses the corresponding action for seL4/ci-actions#170 to generate the matrix for sel4test hardware runs centrally instead of replicating it over multiple workflows.
=> generate test hardware matrix

include/stdint.h, src/machine/io.c
`PRIu64`/`PRIx64` were only printing the lower 32 bits of the value on 32-bit systems.
Found while experimenting with the system time for https://github.com/seL4/seL4/pull/657
=> print 64-bit integers on 32-bits systems fully

CMakeLists.txt, llvm.cmake
This will require: https://github.com/seL4/sel4runtime/pull/15 and https://github.com/seL4/musllibc/pull/14
Also will need to see if all the configurations compile and run because there tends to be a ton of edge cases when altering these flags.
- `-fno-integrated-as` prevents the llvm assembler from being.  The reason for this historically was because using llvm-as caused assembly errors.  Hopefully https://github.com/seL4/musllibc/pull/14/commits/8b644601dc98592817c5b3e09c6c0d26539ff961 is the only one left now.
- `-Wno-unused-command-line-argument` and `-Qunused-arguments` suppressed warnings about unused command line arguments. https://github.com/seL4/musllibc/pull/14/commits/88403f7404bbf79dff470cc771b6dba31d63b4b1 suppresses these warnings for muslc and …
=> Remove llvm toolchain supplied compiler options

libsel4/arch_include/arm/sel4/arch/syscalls.h, libsel4/include/api/syscall.xml
Align the API wrapper guards with the kernel syscall implementation, the function is available if `CONFIG_ENABLE_SMP_SUPPORT` is set instead of depending on `CONFIG_MAX_NUM_NODES`.
=> align include guards for seL4_DebugSendIPI()

libsel4/include/sel4/syscalls_master.h, src/api/syscall.c
Remove a userError that is present on mainline kernel but not on MCS.
seL4_ReplyRecv is often used in a loop to create an event handler. When
first entering this loop, or when handling signals from notifications,
there won't already be a pending caller blocked on the reply object. In
this case the kernel doesn't perform a reply transfer and continues with
the receive operation. This is a common operation and shouldn't result
in a userError being printed by the kernel each time the reply phase
ends up as a no-op.
=> Remove userError from seL4_ReplyRecv path

include/arch/riscv/arch/benchmark.h
Compilation on RISC-V with `set(KernelBenchmarks "track_utilisation" CACHE STRING "" FORCE)` fails because `benchmark_arch_utilisation_reset()`is missing.
=> riscv: add missing benchmark function

src/api/syscall.c
make `SysBenchmarkSetLogBuffer` a no-op if `CONFIG_KERNEL_LOG_BUFFER` is not set instead of invoking the scheduler. That aligns the behavior with the other benchmarking syscalls that also return in their dedicated handler.
I've found this while taking over https://github.com/seL4/seL4/pull/298 and I'm not sure if `setRegister(NODE_STATE(ksCurThread), capRegister, seL4_NoError)` is a goot idea if `CONFIG_KERNEL_LOG_BUFFER` is not set. It could set `seL4_IllegalOperation` instead to tell the user that the syscall does not work in this case. Halting the kernel with an error might also be an option, as this is likely a misconfiguration and there is no point in continuing.
On a similar case, `SysBenchmarkFinalizeLog` also leaves `capRegister` then, maybe `0` or `-1` should be set in this case …
=> avoid invoking scheduler when setting log buffer

src/arch/riscv/smp/ipi.c
Avoid using assembly code and use the provided wrapper function instead.
=> riscv: use wrapper function

include/arch/riscv/arch/machine.h, include/arch/riscv/arch/sbi.h, src/arch/riscv/smp/ipi.c
Hide the actual SBI call parameter details of the legacy API and remove the pointer parameters in the higher code layers. This is a preparation step for switching to the newer SBI API.
=> riscv: pass hart mask by value to SBI wrappers

include/arch/riscv/arch/machine/timer.h
The `getMaxUsToTicks` function is supposed to return maximum amount of time you can pass to `usToTicks` without overflow,but in RISC-V implementation it returns ticks instead. This patch corrects it so it's implementation is akin to those in other platforms.
=> Fix getMaxUsToTicks function in RISC-V machine/timer.h

config.cmake, tools/hardware/config.py, tools/hardware/outputs/c_header.py, tools/hardware_gen.py
Also make 'arch' a required parameter to avoid implicit assumptions.
This PR make a change in the ELF-Loader script necessary, too. See https://github.com/seL4/seL4_tools/pull/130
Test with seL4/seL4_tools#130
=> python: use KernelSel4Arch instead of KernelArch

include/arch/arm/arch/32/mode/machine.h
I had trouble boot with allwinner A20 (Cortex-A7) and got it fixed by cleaning to PoC.
It seems all Cortex-A7 (I.MX7, AllwinnerA20), Cortex-A15 (Exynos5, Tk1), and Cortex-A53 boards require to flush to coherency.
=> Fix d-cache flush on aarch32

src/kernel/cspace.c
It's impossible for "n_bits < levelBits", because a few lines above, it
has already judged this case and would have returned with error:
if (unlikely(levelBits > n_bits)) {
current_lookup_fault =
lookup_fault_depth_mismatch_new(levelBits, n_bits);
ret.status = EXCEPTION_LOOKUP_FAULT;
return ret;
}
Signed-off-by: Bao Haojun <baohaojun@lixiang.com>
=> trivial: Make the branch easier to understand.

include/arch/arm/arch/types.h, include/arch/riscv/arch/types.h, include/arch/x86/arch/types.h, include/basic_types.h
Seems these definition are all based on generic types, so they could be move one level up and get unified across architectures then.
=> unify libsel4 type definitions

src/arch/arm/machine/gic_v2.c
Errant semicolon in macro is removed
=> trivial: remove semicolon after macro

libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/syscalls.h
Commit 8035f1a7c4 removed "-fno-integrated-as" for llvm, which on more
recent versions (clang-11) means that we now need `#` instead of `$`
for immediate values.
=> libsel4: adjust asm immediate syntax for clang

CMakeLists.txt
When running a python script from CMake, explicitly invoke Python via
the `PYTHON3` variable defined in the seL4 CMake config, rather than
relying on the script to specify its interpreter with `#!`.
This makes it easier to override the Python interpreter used for all
Python scripts called from CMake builds.
=> cmake: invoke python3 explicitly

src/arch/riscv/kernel/boot.c
Explicitly include the config header file as the first thing, don't rely on other headers doing this eventually.
=> boot/risc-v: add missing include

src/arch/riscv/kernel/boot.c
The phys/virt translation fails on 64-bit systems when uint32_t is used. With `virt_address = 0xc0000000` and `phys_address = 0x0` the calculation
```
pv_offset = phys_address - virt_address
= 0x0 - 0xc0000000 = 0xffffffff40000000
````
result truncated to `uint32_t` is `0x40000000`. Then the phys-to-virt reverse calculation
```
virt_address = phys_address - pv_offset
= 0 - 0x40000000 = fffffffc0000000
```
results in a wrong virtual address. Using the proper `(s)word_t` type
```
virt_address = phys_address - pv_offset
= 0 - 0xffffffff40000000 = 0xc0000000
```
gives the correct result.
Note that the C rules define that sword_t is converted to word_t in this operation automatically, thus using sword_t or word_t does not make any difference here. Using a signed type for offset is just more …
=> boot/risc-v: pv_offset cannot be uint32_t

src/arch/riscv/idle.c
This also aligns RISC-V behavior with ARM port.
=> risc-v: print kernel entry reason on halt

src/kernel/boot.c
The loop is counting down and must check if the index is valid first. Only when the index is greater or equal zero, the element at this index can be accesses for a content check. IN the corner case where no free memory is available, the old order tries to access the element -1. Changing the order ensures that this element is not accessed, because the short-circuit evaluation rules apply.
Note that I have also seen a slightly disturbing behavior with the old code, as it still seems to enter the following (`for (; i >= 0; i--) { ...create root server objects ...`) on completely invalid array indices - even if `i` clearly is negative now. It should not run the loop at all actually.  When adding `printf("i 0x%x, is_neg %d\n", i, i<0);` even in the loop it says "`i 0xffffffff, is_neg 0`" …
=> boot: check index before accessing element

include/api/types.h, include/kernel/thread.h, src/kernel/thread.c, src/object/tcb.c
Defined to be equal to CONFIG_NUM_DOMAINS. seL4 makes control-flow
decisions based on whether the number of domains is greater than 1. To
perform refinement proofs independent of the number of domains, we need
to follow both branches of these if statements, pretending we don't know
which branch will be taken. This is made significantly harder when
preprocessed C code ends up with comparisons like `if (16 > 1)`.
By adding a numDomains that appears in the C code, we obtain a name we
can point to and link up to higher level specifications.
Signed-off-by: Rafal Kolanski <rafal.kolanski@proofcraft.systems>
=> Add numDomains enumeration constant

src/arch/riscv/common_riscv.lds
The comment seems to be a copy/paste fragment from the ARM port.
=> risc-v: remove misleading comment

include/arch/arm/arch/kernel/vspace.h
The function `create_device_frames()` no longer exists.
=> remove obsolete prototype

libsel4/include/sel4/bootinfo_types.h
- use enum for `SEL4_BOOTINFO_HEADER_xxx` to keep some semantic information
- Also add more comments.
=> use enum for SEL4_BOOTINFO_HEADER_xxx

libsel4/include/sel4/bootinfo_types.h
This reverts a small part of 1596aa5857 (#724) which unexpectedly broke the binary verification frontend, because the verification tool chain forces the enum to `int` instead of of `long`.
See also seL4 issue #738 -- when that issue is solved, we may be able to go back to the more specific type.
=> keep seL4_Word for seL4_BootInfoID

include/benchmark/benchmark.h, include/smp/ipi.h, src/api/syscall.c, src/benchmark/benchmark.c, src/config.cmake, src/smp/ipi.c
Make `syscall.c` call syscall handler function for debug syscalls, so the implementation is no longer visible there. That makes the dispatcher code easier to read and maintain. Also changes in the debug syscalls no longer cause cause preprocess failures, this is all hidden from verification anyway. Furthermore the this enforces a cleaner implementation of the debug syscalls, then need to fully handle the syscall.
The PR is on top of https://github.com/seL4/seL4/pull/673 and a preparation for reworking https://github.com/seL4/seL4/pull/298 eventually.
=> Move debug implementation out of syscall.c

.github/workflows/proof.yml
By default GitHub spawns a new test for each push to a PR. Since the
proof tests have limited resources, we want only the most recent push
to be triggered, intermediate pushes will be skipped.
=> github: proof test only for most recent push

manual/parts/io.tex, src/arch/arm/64/model/statedata.c, src/arch/arm/object/smmu.c
Came across these looking at SMMU. Not 100% on "and conducting a
TLB invalidation", but this is my guess. Cross-check?
It's possible that "invalidates the TLB" is wrong here, and "conducts a TLB invalidation" is what we want.
=> smmu+manual: typo and small sentence tune

.github/workflows/proof.yml
`${{github.ref}}` is not what it seems for `pull request target`. It will point to the base branch instead of `refs/pulls/<num>` like the docs would suggest. Using the PR number directly should work.
=> github: use PR number instead of ref

configs/AARCH64_verified.cmake
For ongoing verification of seL4 on AArch64. This config has SMMU and hypervisor support enabled. AArch64 also implies FPU support is on. The target board for now is the TX2, which has an SMMU.
When this is merged, I'm planning to add the config to preprocess and compile tests.
=> config: AARCH64 config for verification

.github/workflows/proof.yml, include/arch/arm/arch/kernel/thread.h, include/arch/arm/arch/kernel/vspace.h, include/arch/riscv/arch/kernel/thread.h, include/arch/riscv/arch/kernel/vspace.h, include/arch/x86/arch/kernel/thread.h, include/arch/x86/arch/kernel/vspace.h, include/kernel/thread.h, src/arch/arm/32/kernel/thread.c, src/arch/arm/64/kernel/thread.c, src/arch/riscv/kernel/thread.c, src/arch/x86/32/kernel/thread.c, src/arch/x86/64/kernel/thread.c
Consolidate arch thread function prototypes. They are the same on all architectures and thus there is no need to duplicate this in the architecture specific headers
=> consolidate idle and arch thread prototypes

include/assert.h, libsel4/include/sel4/assert.h
- use `_Static_assert()` in kernel builds (except verification) to have nicer error messages. Both gcc and clang support it even for c99.
- simplify macro `seL4_CompileTimeAssert()` to use `SEL4_COMPILE_ASSERT()`
=> clean up compile_assert()

config.cmake, gcc.cmake
This has been sitting in my private patch queue for a while -- it turns out if the scope is just `kernel.elf` the changes needed to build `kernel.elf` on MacOS are minimal, so I think it would make sense to include them here. I'm happy to be the maintainer for the foreseeable future.
This PR contains:
- additional toolchain prefixes to match up defaults on MacOS
- user `CMAKE_HOST_APPLE` instead of `APPLE` (selects based on host instead of target)
- produce a slightly different command-line invocation for `stat`, since MacOS X has BSD `stat` not GNU `stat`.
I've tested these with the verified build configurations on MacOS (and all configs on Linux. I don't expect other configs to turn up any problems, but I have not looked at trying to build sel4test or other user-level code.
=> add support for building kernel.elf on MacOS

include/benchmark/benchmark.h, src/api/syscall.c, src/benchmark/benchmark.c
Follow up from comment https://github.com/seL4/seL4/pull/676#discussion_r780857025
Fail the log buffer setup syscall completely (and invoke a fault hander is one is set up) if `CONFIG_ENABLE_KERNEL_LOG_BUFFER` is not set. The old behavior of silently ignoring this is confusing, as a caller would never know if this worked or not.
=> benchmark: fail log buffer setup if not enabled

src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c
Follow-up from comment https://github.com/seL4/seL4/pull/422#discussion_r715981928
There is no reason to round the DTB area up or down to page boundaries, because the content is copied anyway and reserving memory areas works on arbitrary granularity.
This is also a step towards https://github.com/seL4/seL4/issues/660 to align the ARM/RISC-V boot code, so it can be unified eventually.
=> boot: don't round DTB area down or up

libsel4/sel4_arch_include/ia32/sel4/sel4_arch/syscalls.h
Fixes a syntax error on libsel4 on ia32 with position independent code
compilation options.
Fixes https://github.com/seL4/seL4/issues/743
=> libsel4,ia32: Add missing comma to asm statement

.github/workflows/sel4test-deploy.yml
Merge to master is infrequent enough that we can let the hardware test
suite run to completion even if one of the tests failed. This will
provide more information in the history on which boards worked for
which commits, even if the test for one is broken for some time.
=> github: let hw test run to completion on failure

.github/workflows/pr.yml, .github/workflows/preprocess-deploy.yml
There is now an `AARCH64_verified` configuration which is used in ongoing verification of the seL4 Aarch64 port. This commit enables the preprocess check for this config so that verification impact becomes visible on pull requests.
=> github: add AARCH64 to preprocess test

.github/workflows/compilation-checks.yml
Use the AARCH64_verified config for the standalone kernel compilation check.
(This is the counter part to seL4/ci-actions#183)
=> github: standalone-compilation for AARCH64

include/arch/arm/armv/armv8-a/64/armv/vcpu.h
In `vcpu_enable` and `vcpu_disable`, use `setHCR` to wrap setting
REG_HCR_EL2 (similar to AArch32).
Reorder `vcpu_enable` to match AArch32 operation order for easier proof.
Signed-off-by: Rafal Kolanski <rafal.kolanski@proofcraft.systems>
=> aarch64: verification VCPU tweaks

libsel4/tools/syscall_stub_gen_rs.py
This PR is related to discussion in the devel mailing list. It splits syscall_stubs generator into language specific backends. It also adds Rust and C backends.
Any comments are appreciated.
=> Add support for generating syscall_stubs for different languages

include/object.h
Remove the duplicate objecttype.h in include/object.h
Signed-off-by: Cao Jianlong <caojianlong@outlook.com>
=> trivial: remove duplicate headers

libsel4/tools/sel4_idl.dtd
This patch restricts mixed-content elements from ANY
to the various leaf nodes which are used.
This is intended to allow for easier parsing in languages with
no recursive datatypes like rust.
Since they no longer have to handle things like
```
<description> text
<description>more text</description>
<description>
```
which the dtd allowed for, but never used.
tested with:
```
for i in {libsel4/arch_include/*/interfaces/,\
libsel4/include/interfaces/,\
libsel4/sel4_arch_include/*/interfaces}/*.xml;
do
xmllint --noout --dtdvalid libsel4/tools/sel4_idl.dtd $i;
done
```
=> remove usage of ANY in dtd

include/util.h, src/machine/io.c
When building seL4 on a host whose default encoding is not UTF-8,
tools/bitfield_gen.py complains, as with the following log from
Python 3.6 on a Ubuntu 18.04 host says:
```
Traceback (most recent call last):
File "tools/bitfield_gen.py",
line 2773, in <module>
string = f.read()
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 607543: ordinal not in range(128)
```
As the Python 3 doc for open() [1] says the default encoding is
platform dependent, such build error may happen on some hosts.
We can either updating tools/bitfield_gen.py to call open() with
an explicit encoding="utf-8" parameter, or avoiding UTF-8 characters
in the source codes.
After …
=> trivial: Convert UTF-8 character to ASCII

src/kernel/cspace.c
Commit 9f2d5219 made this 32/64-bit agnostic, but did not update the comment. Demystify the magic number mentioned there.
I wonder, who was/is 'swj' ?
=> doc: update comment about mask

src/kernel/cspace.c
The loop is always left by a direct return from the body, any code after the loop is not reachable.
=> use unreachable instead of returning something

CMakeLists.txt
Making things a bit more generic is supposed to make using various RISC-V extensions easier. This also remove some redundancies also. Seem on rv32 we do not support the FPU at the moment because nobody has tested this?
This is supposed to make integration of https://github.com/seL4/seL4/pull/776 a bit easier.
=> make RISC-V parameter handling more generic

include/arch/riscv/arch/machine/fpu.h, src/arch/riscv/config.cmake
This includes a fix for the riscv F extension as well as a simplification of the riscv `config.cmake`.
=> riscv: fpu extension fixes

include/arch/arm/arch/machine/gic_common.h
This PR just fixes examples given in a comment for how an IRQ gets converted to a CNode index.
Example 2: The IRQ number is not a PPI so the index is `(irq.target_core)*NUM_PPI + (_irq.irq)`, which means it should be `+ 16` not `+ 12`.
Example 3: The IRQ number is a PPI so the index is `(CONFIG_MAX_NUM_NODES-1)*NUM_PPI + (_irq.irq)`, which means it should be `(3 * 32) + 33` since there's 4 cores, not sure where the `(33 - 32)` came from.
=> trivial: fix examples explaining IRQT_TO_IDX macro

CMakeLists.txt
It's not possible to build the RISC-V kernel anymore with GNU binutils version 2.38 since it requires specifying the Zicsr and Zifencei extensions explicitly.
This patch adds a check for the GNU binutils version used to build the kernel and adds the corresponding flags if necessary.
I'm not sure whether this is an elegant solution, any suggestions are welcome.
Edit:
Fixes #749
=> RISC-V/CMake: Fix build when using GNU binutils >= 2.38

include/util.h
Put the parameter in brackets to ensure it is an atom. This makes the macro work as expected in corner cases like `ARRAY_SIZE(foo + 3)` also.
Such a corner case may happen when the argument passed is another macro that lacks brackets. Could happen when experimenting with the code and using sloppy statements...
See also https://github.com/seL4/util_libs/blob/master/libutils/include/utils/arith.h#L121 where it uses proper brackets.
=> make macro ARRAY_SIZE() handle corner cases

include/api/debug.h
This is not supposed to happen, thus printing the value gives a bit more insight what might have happened here.
=> print value for unknown entry reason

src/arch/x86/machine/breakpoint.c
The conditional else-block with the dummy reference might have been added once to avoid a compiler warning about unreferenced parameters. However, 'int_vector' is used in the code now, so this is obsolete.
=> benchmark/trace: remove conditional else block

tools/bitfield_gen.py
A tagged union can now optionally use multiple fields to indicate the tag. These are called "sliced" tags in the code. The tag fields have to be at the same position and width in each block of the tagged unions, and all tag fields have to be within the same word.
When sliced tags are used, tag class masks cannot be used at the same time for this tagged union.
In the `tagged_union` declaration, the values of such sliced tags become tuples. 
Example:
```
block ex1 {
padding 16
field x 1
padding 16
padding 29
field y 2
}
block ex2 {
padding 16
field x 1
padding 16
field b 5
padding 20
field a 4
field y 2
}
tagged_union ex exType(x,y) {
tag ex1 (1,0)
tag ex2 (1,3)
}
```
In the existing bitfield generation almost nothing changes: some redundant assertions were dropped, but no assertion …
=> bitfield_gen: allow non-contiguous tag fields

tools/bitfield_gen.py
Bring up-to-date with current proof style, make style consistent, slightly increase proof parallelism.
These should be almost exclusively whitespace and formatting changes, and some `apply/done` replaced by `by`.
=> trivial: proof style fixes for bitfield_gen

config.cmake
Clean up the CMake script:
- `SLOTS` cannot be less than `MAX_IRQ` (I'm not sure why this was added initially, seems some safe-guard that was never really needed)
- remove helper variable `MAX_IRQ` and use only `MAX_NUM_IRQ` everywhere  (should have happened at the last refactoring already)
=> cmake: remove unused code

libsel4/tools/syscall_stub_gen.py, tools/bitfield_gen.py, tools/invocation_header_gen.py
using the '#paragma once' include guard simplifies things a bit and it's the modern way to guard includes.
=> python: use '#paragma once' include guard

CHANGES, include/arch/arm/arch/64/mode/fastpath/fastpath.h, include/arch/arm/arch/64/mode/kernel/vspace.h, include/arch/arm/arch/64/mode/object/structures.bf, include/arch/arm/arch/64/mode/object/structures.h, include/arch/arm/armv/armv8-a/64/armv/context_switch.h, libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h, src/arch/arm/64/kernel/vspace.c, src/fastpath/fastpath.c
Use the asid_map bitfield from x86 for aarch64 to map from ASID to an intermediate asid_map object that can hold a vspace object reference plus additional related attributes.  This can free up reserved slots in the top level page table for use at user level. 
This PR uses some commits from https://github.com/seL4/seL4/pull/579 but is only targeting aarch64.
More background: https://sel4.atlassian.net/browse/SELFOUR-1840
=> aarch64: Use asid_map_t bitfield to store vspace attributes to free mapping slots

include/arch/riscv/arch/32/mode/machine.h, include/arch/riscv/arch/64/mode/machine.h
Provide generic CSR access function macros that can be extended easily for other CSRs.
Note that this PR is on top of https://github.com/seL4/seL4/pull/646
=> riscv: provide functions for CSR access

CAVEATS-generic.md
Remove x86 and Arm from heading of the "Re-using address spaces" caveat
because it's also present on RISCV and isn't actually arch specific.
=> CAVEATS-generic: ASID caveat applies all arches

include/benchmark/benchmark.h, src/api/syscall.c, src/benchmark/benchmark.c
The latest code updates introduced CONFIG_ENABLE_KERNEL_LOG_BUFFER
meanwhile other code and config.cmake keeps using
CONFIG_KERNEL_LOG_BUFFER
Signed-off-by: Nataliya Korovkina <malus.brandywine@gmail.com>
=> benchmark: config opt. name to enable log buffer

config.cmake
The seL4 CMake build currently uses the `stat` utility to determine the
size of the flattened device tree file. The `stat` utilities in macOS
and GNU coreutils have different interfaces, the CMake build needs to
determine which one it's using.
This change supports building on macOS with GNU coreutils in the PATH,
by only using the macOS `stat` interface with `/usr/bin/stat` on a macOS
host, and otherwise assuming GNU coreutils.
In future, we might be able to avoid the `stat` utility altogether, by
using the built-in `file (SIZE ...)` command that became available in
CMake version 3.14. For now, we avoid updating our build dependencies.
=> cmake: allow building with coreutils on macOS

include/arch/arm/armv/armv8-a/64/armv/vcpu.h
CPSR.AIF already presented in HCR_COMMON macro,
And HCR_NATIVE includes HCR_COMMON, then no need
To set CPSR.AIF bit again
Signed-off-by: Cao Jianlong <caojianlong@outlook.com>
=> aarch64: remove redundent CPSR.AIF in HCR_NATIVE

src/arch/arm/64/kernel/vspace.c
Set Write-through non-transient, No-Write-allocate, Read-allocate
attributes for kernel log buffer.
Signed-off-by: Nataliya Korovkina <malus.brandywine@gmail.com>
Test with: seL4/seL4_tools#146
=> benchmark/arm64: write-through kernel log buffer

CHANGES, libsel4/sel4_plat_include/maaxboard/sel4/plat/api/constants.h, src/plat/maaxboard/config.cmake, src/plat/maaxboard/overlay-maaxboard-32bit.dts, src/plat/maaxboard/overlay-maaxboard.dts, tools/dts/maaxboard.dts, tools/dts/update-dts.sh
This pull request is a call for feedback and comment on an initial implementation for supporting seL4 on the Avnet MaaXBoard, with the intention of the changes below being merged back to the main seL4 repository.
This pull request contains the following changes:
* Addition of a device tree (DTS) file sourced from Avnet.
* The creation of an 32-bit overlay DTS file to provide memory clamping and exclusion of devices (the GPU) that extend outside of the 32-bit memory range, in order to support running seL4 under AArch32.
* The creation of a general overlay DTS file, to provide nodes for general purpose timers that exist in the SOC documentation (i.MX8) for the Avnet MaaXBoard, but where not present in the DTS sourced from Avnet, as well as the relevant interrupts for these timers. The …
=> Add support for the Avnet MaaXBoard

CHANGES, include/arch/arm/arch/32/mode/fastpath/fastpath.h, include/arch/arm/arch/32/mode/hardware.h, src/arch/arm/32/c_traps.c, src/arch/arm/32/hyp_traps.S, src/plat/qemu-arm-virt/config.cmake
Add support for the qemu-arm-virt simulation platform to run seL4 in hyp mode.
=> qemu-arm-virt: Add support for 32bit arm hyp mode configurations

.github/workflows/proof.yml
Setting the correct branch for the isabelle repository.
=> github: switch proofs to Isabelle2021-1

gdb-macros
Various kernel symbols have changed their names; update
the GDB macros to match.  Also remove hard-coded  0xf0000000 for
the address of the kernel window.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
=> Update GDB macros

include/arch/x86/arch/64/mode/fastpath/fastpath.h, include/arch/x86/arch/64/mode/machine.h, src/arch/x86/64/c_traps.c
sysexit requires a 64-bit operand to remain in 64-bit mode when
switching to user level. gcc versions older than 12 encode this as
"REX.W SYSEXIT" while clang encodes this as "SYSEXITQ". Both compilers
don't support the alternate encoding. We instead use ".byte
0x48,0x0F,0x35" which is the actual opcode of the required instruction
which will work with both compilers.
=> x86_64: Fix x86_64 gcc compile error with sysexitq

include/arch/arm/arch/machine/gic_common.h, include/arch/riscv/arch/32/mode/hardware.h
The kernel files usually simply include `config.h`, which then handles further details. It's unclear why these two files do things differently, there seems no specific reason and it might be just legacy. The file `config.h` will include `sel4/config.h` anyway, which does include `autoconf.h` then.
Changing this avoids setting a bad example. If there is reason, e.g. why `sel4/config.h` must be hidden from the GIC header file code that might be worth documenting. Due to the way the kernel build works on a single file, this header might have been included already anyway.
=> fix config includes

libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/syscalls_sysenter.h
The MCS-related macros were causing the build to fail when configured to
use the sysenter instruction. Additionally, some message registers
weren't explicitly being passed to the assembly block for
seL4_NBSendRecv in this configuration.
=> x64: fix sysenter syscalls

src/kernel/thread.c, src/object/notification.c
sc_sporadic() already calls sc_active.
Signed-off-by: Indan Zupancic <Indan.Zupancic@mep-info.com>
=> Remove redundant sc_active checks

CMakeLists.txt, config.cmake
Some inter-procedural optimisations can produce cloned or partial
functions in the binary. Since binary verification is incompatible with
cloned and partial functions, we add a config option to disable these
optimisations.
This does not change any defaults, so to avoid cloned and partial
functions for a binary verification build, it is necessary to explicitly
configure this, e.g. using `-DKernelBinaryVerificationBuild=ON`.
Fixes https://github.com/seL4/seL4/issues/805.
=> Add config option to prevent cloned functions

config.cmake
Sometimes device trees may have differences between vanilla Linux and SoC vendor, and the changes can be tedious to override with a device tree overlay.
This change allows overriding the platform default dts and overlays with a custom dts.
It can be used together with `KernelCustomDTSOverlay` to pass custom base device tree and overlay.
For rpi4, we are using `linux-raspberrypi` kernel in guest VMs which contains quite many differences compared to dts in vanilla kernel. And that becomes a problem when passing through the devices to the guest. This change allows us to more easily manage and reason about the device trees used in a build without having to modify device trees in seL4 kernel.
=> cmake: support for supplying custom device trees

tools/bitfield_gen.py, tools/umm.py
There are cases that reasonably require non-ASCII characters in the source code, hence tools/bitfield_gen.py must be able to handle them correctly. This commit makes sure the bitfield generator consistently opens all files with UTF-8 encoding.
This is a slightly tweaked version of #780 that applies UTF-8 encoding to all files the bitfield generator handles.
=> tools/bitfield_gen: ensure UTF-8 encoding

CHANGES, include/arch/arm/arch/32/mode/machine_pl2.h, include/arch/arm/arch/64/mode/machine.h, include/arch/arm/arch/64/mode/machine_pl2.h, src/arch/arm/32/kernel/vspace.c, src/arch/arm/64/kernel/vspace.c, src/arch/arm/api/faults.c
This commit introduces `addressTranslateS1` to be used on Arm platforms
with hypervisor enabled for stage 1 (vaddr to IPA) translation. On
AArch32 this is a rename from `addressTranslateS1CPR`, and on AArch64 it
wraps `ats1e1r`. This changes to ABI on AArch64 to report faulting
address as IPA.
Reasoning:
With hypervisor enabled, AArch64 defined `addressTranslateS1CPR` to do
nothing, while AArch32 defined it to do stage 1 translation. This
delivered VM faults to the user with the faulting address being either
an IPA or a vaddr depending on mode. This inconsistency is undesireable.
This commit proposes adjusting the inconsistency to match AArch32
behaviour, as it is one of the verified platforms.
Signed-off-by: Rafal Kolanski <rafal.kolanski@proofcraft.systems>
=> arm: consolidate stage 1 translation function use

include/arch/arm/arch/kernel/vspace.h, include/arch/riscv/arch/kernel/vspace.h, include/arch/x86/arch/kernel/vspace.h, include/arch/x86/arch/object/objecttype.h, include/arch/x86/arch/object/vcpu.h, src/arch/arm/32/kernel/vspace.c, src/arch/arm/32/object/objecttype.c, src/arch/arm/64/kernel/vspace.c, src/arch/arm/64/object/objecttype.c, src/arch/arm/object/smmu.c, src/arch/riscv/kernel/vspace.c, src/arch/riscv/object/objecttype.c, src/arch/x86/32/kernel/vspace.c, src/arch/x86/32/kernel/vspace_32paging.c, src/arch/x86/32/object/objecttype.c, src/arch/x86/64/kernel/vspace.c, src/arch/x86/64/object/objecttype.c, src/arch/x86/kernel/vspace.c, src/arch/x86/object/ioport.c, src/arch/x86/object/objecttype.c, src/arch/x86/object/vcpu.c, src/object/tcb.c
This PR updates https://github.com/seL4/seL4/pull/243 to make it better conform to the reply convention. In particular, we introduce a `call` parameter to guard message register updates. We ignore `setConsumed` for now, which will be fixed in a future PR addressing the `isReceiver` parameter of IPC buffer lookups.
Signed-off-by: Ryan Barry <ryan.barry@proofcraft.systems>
=> Don't clobber msgInfo register after an invocation

src/object/objecttype.c
This adds AUXUPD and GHOSTUPD comments to aid verification in
reasoning about the length and type of the refill buffer
associated with scheduling contexts
This also add a AUXUPD comment for replies
=> mcs: add AUXUPD and GHOSTUPD comments for verification

src/arch/riscv/kernel/vspace.c
The RISC-V Instruction Set Manual - Volume II: Privileged Architecture:
For non-leaf PTEs, the D, A, and U bits are reserved for future standard
use. Until their use is defined by a standard extension, they must be
cleared by software for forward compatibility.
Signed-off-by: Ahmed Charles <acharles@outlook.com>
=> RISC-V PTE compliance.

src/arch/arm/common_arm.lds, src/arch/riscv/common_riscv.lds
- Move the .boot.bss section into the range of memory that can be reclaimed after boot.
- Mark the idle thread symbol as NOLOAD to avoid it taking up space in the ELF file.
=> Small common_riscv.lds improvements

include/object/structures.h, include/object/structures_64.bf
The kernel expects object sizes to be powers of two for size and alignment computations.
- add missing padding for MCS 64-bit configurations for notifications (other configs were already fine)
- add missing padding for reply object struct
- strengthen compile time assertion to catch discrepancies in the future.
This most likely did not trigger any actual bugs because we don't tend to do much computation with the object size directly for these specific types, but verification predicates do need to do those computations and rely on them lining up.
=> structures: fix MCS 64-bit notification obj size

include/arch/x86/arch/machine.h, src/arch/x86/kernel/boot_sys.c
At least some server-class Skylake processors use 0x55 as
their model ID.
These are Skylake X processors.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
=> Add newer Skylake model ID

CMakeLists.txt, src/arch/x86/kernel/cmdline.c
Issue #875 shows how gcc-12 is much more aggressive in
array bounds checking.  By lying to gcc and telling it the
page size is zero, the warning can be avoided.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
=> Fix gcc-12 spurious array bounds warning

include/object/structures.h
The pointer to a reply object, if any, can be accessed via the replyObject in the thread state
=> mcs: remove unused tcbReply field from tcb struct

include/arch/arm/arch/64/mode/machine/fpu.h
Signed-off-by: Yanyan Shen <yshen@hybridkernel.com>
=> aarch64: Use isb after changing FPU control registers

src/arch/arm/64/head.S
The preprocess/AARCH64 error seem to come from the changes of https://github.com/seL4/seL4/pull/911, where an update is still missing.
=> trivial: fix typo

configs/seL4Config.cmake
Ensure the configuration is within the expectation. This catches potential porting problems early, and avoids quite odd errors and undefined behavior later on that is more difficult to understand.
=> cmake: add a sanity check

src/machine/capdl.c
Commit b181184d75a4a74509b95d19ded54f445b3bd538 turned the macro `REFILL_HEAD` into a function `refill_head()` in `include/kernel/sporadic.h`. It seems that commit a403d0d66c9fc1ec7593de965dd6fc4cb4ccc6fd created `capdl.c` in a parallel branch, so so `REFILL_HEAD` was added here again. This is not necessary, `refill_head()` can be used because we include `include/kernel/sporadic.h`.
The preprocess/AARCH64 error seem to come from the changes of https://github.com/seL4/seL4/pull/911, where an update is still missing.
=> remove redundant definitions

include/kernel/boot.h
- explicitly mention the parameter to make macro less obscure.
- add brackets to make the expression an atom.
=> make macro less obscure

gcc.cmake
When compiling in the Docker container on an M1 MacBook, or any other ARM host, the CMAKE_HOST_APPLE variable is not set. Therefore, no CROSS_COMPILER_PREFIX is set and x86 applications will not compile.
This commit adds another check to see if the host processor is an ARM chipset, and sets the appropriate CROSS_COMPILER_PREFIX variable.
M1 docker issues described here: https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles/issues/40
=> gcc: add x86 cross-compiler for arm host

include/arch/arm/arch/32/mode/fastpath/fastpath.h, include/arch/arm/arch/64/mode/fastpath/fastpath.h, include/arch/riscv/arch/fastpath/fastpath.h
Use the thread passed as parameter instead of making assumption that this is in sync with the global state.
Using `NODE_STATE(ksCurThread)` feels semantically wrong when `cur_thread` is passed to the function. It seems this function is not supposed to ever be called with `cur_thread` being different to `NODE_STATE(ksCurThread)`, so I wonder if an explicit assert in the code should be added then to state this (and catch potential copy/paste porting errors).
=> fastpatch: use thread passed as parameter

include/kernel/boot.h, src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c, src/arch/x86/kernel/boot.c, src/kernel/boot.c
Remove the return value from `configure_sched_context()`, because it never fails. As a consequence, `create_idle_thread()` also never fails and does not need a return value.
=> boot: remove unused return values

libsel4/include/sel4/constants.h
=> mcs: correct MinSchedContextBits and add compile assert

src/plat/polarfire/config.cmake, tools/dts/mpfs_icicle.dts
A few small commits fixing the timer node in the device tree and the TIMER_FREQUENCY in the config for the polarfire platform.
=> Polarfire fixes

include/arch/arm/arch/64/mode/kernel/vspace.h, include/arch/arm/arch/kernel/vspace.h, src/arch/arm/32/kernel/vspace.c, src/arch/arm/kernel/boot.c
`activate_global_pd` is just an alias for `activate_kernel_vspace` nowadays. Seems the C parts is trivial, not sure about the impact on the proofs.
=> boot/arm: remove activate_global_pd usage

.github/workflows/sel4bench-pr.yml
Like the sel4test hardware runs, a sel4bench run can be requested via adding a label (`hw-bench`) to any PR.
=> github: enable sel4bench hardware test on PR

src/plat/zynq7000/mcs-overlay-zynq7000.dts
Apply changes from commit 0f619780 for MCS also. Without them there is no output visible when running e.g. sel4test (tested on QEMU only)
=> zynq7000: fix DTS overlay on MCS

.github/workflows/compilation-checks.yml, .github/workflows/manual.yml, .github/workflows/proof.yml, .github/workflows/sel4bench-pr.yml, .github/workflows/sel4test-deploy.yml, .github/workflows/sel4test-hw.yml, .github/workflows/xml_lint.yml
- update GitHub action versions, because the old ones are now deprecated
- update Isabelle to 2022 version
=> update versions for GitHub actions + Isabelle

include/drivers/irq/riscv_plic0.h, src/plat/qemu-riscv-virt/config.cmake
Fix a build breaker.
Test with: seL4/ci-actions#234
=> risc-v: support rv32 targets for qemu-riscv-virt

manual/parts/threads.tex
👋 In the following table, an undefined field `seL4_VMFault_SP` is referenced despite `seL4_VMFault_Addr` is not documented here. I guess it's just a typo.
=> manual: Fix a typo in threads.tex

src/object/objecttype.c
This removes a memzero call from the seL4_SchedContextObject and seL4_ReplyObject cases of createObject. The memory is now cleared via clearMemory within resetUntypedCap
=> mcs: remove redundant memzero from createObject

config.cmake, include/arch/arm/arch/fastpath/fastpath.h, include/arch/arm/arch/kernel/traps.h, include/fastpath/fastpath.h, include/object/endpoint.h, include/object/notification.h, src/arch/arm/64/traps.S, src/arch/arm/c_traps.c, src/fastpath/fastpath.c, src/object/endpoint.c, src/object/notification.c
This is basically a combination of [Shane's signal fastpath](https://github.com/seL4/seL4/pull/322/commits) from last year and [Anna's signal/IRQ fastpath](https://github.com/pingerino/seL4/blob/phd/src/fastpath/fastpath.c#L421). 
Shane's fastpath was able to handle signalling to both lower and higher prio threads, but there were some issues related to what needs to be done when scheduling contexts are switched in the case of a lower to higher prio signal. I have looked at the `schedule()` code to try and figure out what needs to be done. I have been unable to check my progress much as of yet, so this first pull request is mainly for feedback. 
Shane's code was working on all platforms but I have only tested on AARCH64 so far, where it passes all of seL4test and performs in seL4bench …
=> Signal fastpath v2

include/arch/arm/arch/32/mode/fastpath/fastpath.h, include/arch/riscv/arch/fastpath/fastpath.h
The thread context structure layout is explicitly designed to have the register context first, as this simplifies saving the user context on entry in assembly code. On the exit path there is no need to hard-code this assumption, stick to the semantics and leave details to the compiler.
=> user proper field from thread context structure

libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/syscalls.h
Currently, building `libsel4` as a static library with `KernelIsMCS` enabled fails with the following error:
```
/path/to/build/sel4/libsel4/include/sel4/sel4_arch/syscalls.h:226:34: error: static declaration of 'seL4_NBWait' follows non-static declaration
/path/to/build/sel4/libsel4/include/sel4/syscalls_mcs.h:251:1: note: previous declaration is here`
```
This [was mentioned][1] in the original PR that modified exported functions to use `LIBSEL4_INLINE_FUNC`.
[1]: https://github.com/seL4/seL4/pull/101#issuecomment-442010551
Signed-off-by: Klim Tsoutsman <klim@tsoutsman.com>
=> libsel4: use `LIBSEL4_INLINE_FUNC` attributes for `seL4_NBWait`

include/drivers/irq/riscv_plic0.h, src/arch/riscv/common_riscv.lds, src/arch/riscv/kernel/boot.c, src/arch/riscv/machine/hardware.c, src/object/interrupt.c, src/plat/rocketchip/config.cmake, src/plat/rocketchip/overlay-rocketchip-zcu102.dts
This PR does two things:
1. Differentiates the base Rocketchip platform with a version generated for the ZCU102 FPGA fabric
2. Fixes bugs we encountered running on the softcore implementation
We tested this with the VMM created by @yyshen
=> Rocketchip bug fixes + zcu102 softcore

CMakeLists.txt, libsel4/CMakeLists.txt
When the kernel is built as a top-level CMake project, the kernel and libsel4 can be installed using `cmake --install`. This PR adds some more files to that installation which can be useful to components surrounding the kernel, such as userspace bindings to the seL4 API in languages other than C.
Specifically, these files are:
- `sel4{,-arch,-sel4arch}.xml` and `syscall.xml`: Syscall and object interface definition files.
- `*.pbf`: Preprocessed `.bf` files.
- `kernel.dtb`: The device tree generated and used for the kernel build.
- `platform_gen.yaml`: Generated from `kernel.dtb` and used to generate `platform_gen.h`.
This PR includes the addition of a new subdirectory of the installation directory named `support/` which includes `kernel.dtb` and `platform_gen.yaml`. Perhaps there is a …
=> Expose more files for external tools via `cmake --install`

CHANGES
The motivation for this is that not everything uses the the seL4 API C headers for constants like `MinSchedContextBits` (e.g. seL4 Core Platform). Anything depending on the value may want to be aware of a change in the constant.
=> Include change to MinSchedContextBits in CHANGES

.github/workflows/proof.yml
For proof workflow runs on seL4 PRs, upload kernel build artifacts generated by the aws-proofs action. These can be used to run binary verification, although we currently still require binary verification to be manually triggered.
=> ci proof: Upload build artifacts

CHANGES
`gen_config.h` files are now generated at build time rather than configure time.
This change was introduced by https://github.com/seL4/seL4/pull/975/
=> cmake: mention gen_config.h change in CHANGES

src/api/syscall.c
The irq argument of `mcsPreemptionPoint()` is unused since the refactor in d8caaf754d7ef86 (PR #327).
Fixes #991
=> remove unused argument from mcsPreemptionPoint

src/api/syscall.c
The computation in `mcsPreemptionPoint()` no longer depends on the irq, so `getActiveIRQ()` can be called closer to the actual use site of the irq.
This makes things slightly easier for verification because we don't need to reason about potential side effects of mcsPreemptionPoint before the irq value is used.
Closes #472
(Depends on #992 and should be merged after)
=> Move getActiveIRQ() close to use site

libsel4/include/sel4/bootinfo_types.h
This header file is shared by kernel and userland. We can control the kernel compiler setting, but userland might use an arbitrary setup. Put a safeguard in place that things works as expected.
=> add compile assert for seL4_UntypedDesc size

manual/parts/vspace.tex
- clearer distinction between VSpace and VSpace object
- give example and consistent definition for VSpace object (addresses #564) -- it was defined before already, but a bit hidden
- more consistent terminology in the rest of VSpace section, esp wrt to cap vs object
- use `\obj` consistently when referring to kernel objects (previously mix of `\ob` and `\texttt`)
=> manual: improvements to VSpace section

CMakeLists.txt, libsel4/CMakeLists.txt, tools/bitfield_gen.py, tools/helpers.cmake
Add a `--from_file <file>` option to the bitfield generator for printing a `/* generated from <file> */` message in a comment.
Use this option in cmake to provide the original source .bf file before preprocessing so it's easier to find out where the corresponding definitions are.
This should address the concerns in #842.
=> bitfield_gen: comment for original source file

include/basic_types.h, src/kernel/boot.c
- document the `region_t` types
- document in `create_untypeds_for_region` what makes region overflow for device untypeds work.
Fixes #1004
=> document allowed region overflow

include/arch/arm/arch/32/mode/hardware.h, include/arch/arm/arch/64/mode/hardware.h, include/arch/riscv/arch/machine.h
Add compile time checks for conditions on physBase that are necessary for verification of multikernel builds to succeed -- if these fail, the proofs will fail.
If these succeed, and nothing else has changed compared to a verified kernel other than physBase, then the proofs will succeed. This does not mean that all platform requirements are validated, it just means that all requirements for the proofs to be consistent are met.
The conditions correspond to those in
spec/machine/*/Arch_Kernel_Config_Lemmas.thy
in the verification repository. E.g. see [here for Aarch32](https://github.com/seL4/l4v/blob/master/spec/machine/ARM/Arch_Kernel_Config_Lemmas.thy).
=> machine: compile time checks for multikernel

src/kernel/boot.c
Check arguments for alignment, size, and kernel window (if not device untyped). This provides sanity checks in case any of the memory region computations are wrong.
Since this code is not performance critical and can return failure, these are not assertions, but normal conditions with user feedback. I.e. they are on in release and verified configurations.
(One part of #1004)
=> boot: sanity checks for provide_untyped_cap

src/arch/arm/kernel/boot.c, src/kernel/boot.c
Follow up from https://github.com/seL4/seL4/pull/1006 to add the line breaks in the error messages. There is also another message that does not have the line break, so fixing this also.
Found this because one of my experimental patches indeed failed in one of these new checks.
=> boot: add missing line break in error messages

gcc.cmake
These are the prefixes used by the official Arm GNU Toolchain [1] It would be convenient if seL4 would recognise it out of the box.
[1] https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
=> gcc.cmake: add more known ARM cross compilers

include/arch/arm/arch/64/mode/machine.h
- Missing isbs between AT and PAR instructions and required by ARMv8 spec.
=> Aarch64: add required isb() barriers for address translation

include/arch/arm/arch/machine/hardware.h, include/arch/arm/armv/armv7-a/armv/machine.h, include/arch/arm/armv/armv8-a/64/armv/machine.h, src/smp/ipi.c
- dmb() no longer works for GICv3, and consequently a stronger barrier like dsb() has to be used. A weaker variant of dsb is used to ensure the observability of complete stores in the same inner-shareable domain.
=> ipi: add missing barrier and enforce completion

src/plat/hifive/config.cmake
- risc-v/hifive: adapt to post-v0.9 OpenSBI
- riscv: provide wrapper for new (extended) SBI interface
Test with seL4/sel4test-manifest#13
It seems `sifive/fu540` is no longer a valid OpenSBI platform, all this is generic now? Does anybody have access to a hifive or polarfire to test what works here? Seems there is QEMU support also, has anybody tested this?
=> risc-v: adapt to OpenSBI post v0.9

include/arch/riscv/arch/machine.h, src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c
- The cache maintenance is needed on `AARCH32`, so check explicitly for this architecture instead of doing this everywhere except `AARCH64`.
- Do nothing on `AARCH64` and add a build breaker for future unknown architectures this code might be compiled for.
- Improve the documentation to describe the potential pitfall here and why/when explicit action might be needed.
- RISC-V: Improve the documentation to describe about the potential pitfall in SMP boot and the non-recommended barrier that is used.
=>  improve SMP boot arch handling and documentation

include/arch/arm/arch/64/mode/machine/hardware.h, include/arch/arm/armv/armv8-a/64/armv/vcpu.h, src/arch/arm/64/head.S, src/arch/arm/config.cmake
Add a config option, KernelAArch64UserCacheEnable, that enables user
level access to DC CVAU, DC CIVAC, DC CVAC, and IC IVAU which are cache
maintenance operations for the data caches and instruction caches
underlying Normal memory and also access to the read-only cache-type
register CTR_EL0 that provides cache type information. The ArmV8-A
architecture allows access from EL0 as fast cache maintenance operations
improves DMA performance in user-level device drivers.
These instructions are a subset of the available cache maintenance
instructions as they can only address lines by virtual address (VA).
They also require that the VA provided referrs to a valid mapping
with at least read permissions. This corresponds to lines that the
EL0 could already affect via regular operation and so it's …
=> aarch64: Add option for user cache maintenance 

tools/bitfield_gen.md, tools/bitfield_gen.py
Add a user manual for the bitfield generator that documents syntax, semantics and basic concepts. Should also be able to serve as main spec for what the tool is supposed to do.
This is not fully complete yet (see TODO list in comment at the bottom), but I think it is already useful and can be merged.
One thing I'm less sure about is where it should go. I've currently put it into the `tools` directory so it is next to the generator itself and purposefully kept it to a single `.md` file. An alternative would be to create a `docs/` directory and put it there (maybe making the manual also a subdir of that `docs/` directory). Happy with either.
=> add manual for bitfield generator

src/arch/arm/machine/gic_v3.c
- CNTFRQ is a constant value, and does not work for this case, while CNTPCT is the one that should be used as 64-bit physical counter.
=> gic_v3: use CNTPCT instead of CNTFRQ

include/arch/arm/arch/machine/gic_v3.h
- In non-secure world, group 1 IRQs are used instead of group 0.
- APR for GICv2 is 32-bit while for GICv3 is 64-bit wide.
=> gic_v3: AP1R for group 1 IRQs

configs/seL4Config.cmake
Define the (relative) location of the kernel project in one place only.
=> cmake: define KERNEL_ROOT_DIR

include/arch/arm/arch/64/mode/object/structures.h, src/arch/arm/64/kernel/vspace.c
From investigating https://github.com/seL4/seL4/issues/214 it looks like the VM right `VMKernelReadOnly` is not used at all. It was introduced in the initial AArch64 port of seL4, I do not know why it exists, perhaps there is a reason and I am missing something.
=> Remove VMKernelReadOnly from AArch64 VM rights

include/drivers/timer/arm_generic.h, src/drivers/timer/generic_timer.c
Generic Timer IRQs are level-sensitive, when the CNT_TVAL is updated the trigger condition is de-asserted and the change is propagated to the GIC in a finite time to clear the pending state.
However, we have to make sure the timer deasserts before EOIR/DIR, otherwise the interrupt happens again. Therefore, we need an isb() to cause the timer to de-assert before EOIR/DIR. 
There is also a chance of spurious IRQ. A spurious IRQ can be generated, in the case we have a level-sensitive IRQ, and its pending state is cleared at device-level but not yet propagated to the GIC. In between the IRQ deactivation and IRQ ack of the new interrupt if the requested change from the timer gets propagated then it causes a spurious IRQ.
https://community.arm.com/support-forums/f/architectures-and-processors-fo …
=> generic_timer: force timer to de-assert irq

include/arch/arm/arch/machine/gic_v3.h
Prefer compile_assert over _Static_assert. The latter is only available in C11, and the verification demands C99.
(The offending instance was introduced in #387)
=> gic_v3: _Static_assert is not supported

include/arch/arm/arch/machine/gic_v3.h, libsel4/include/sel4/macros.h
`__builtin_offsetof` is not part of the verification C subset -- avoid accidental use by not declaring a macro for it and filter out the single use by explicitly marking it as invisible to verification.
(I've checked that the macro is not used outside the kernel repo either)
=> macros: avoid breaking C subset

src/plat/bcm2711/config.cmake, src/plat/bcm2711/overlay-rpi4-1gb.dts, src/plat/bcm2711/overlay-rpi4-2gb.dts, src/plat/bcm2711/overlay-rpi4-4gb.dts, src/plat/bcm2711/overlay-rpi4-8gb.dts, src/plat/bcm2711/overlay-rpi4.dts
There are multiple variants of the RPi4B SBC with different sizes of RAM. There exists 1GB, 2GB, 4GB, and 8GB models. This patch adds the `RPI4_MEMORY` CMake configuration option in order to be able to specify the RAM size when building the kernel. Based on the RAM size provided, an appropriate device tree overlay is selected.
The default memory size of 8GB remains the same as to not introduce breaking changes.
Closes https://github.com/seL4/seL4/issues/1044.
=> Add support for other Raspberry Pi 4B variants

src/plat/bcm2711/config.cmake
Apologies, I had made an error in my previous commit which causes a compile error when trying to build the kernel without passing `-DRPI4_MEMORY`.
=> Fix setting of CMake variable in BCM2711 config

configs/ARM_HYP_exynos5_verified.cmake, configs/ARM_HYP_verified.cmake, configs/ARM_MCS_verified.cmake, configs/ARM_imx8mm_verified.cmake, configs/ARM_verified.cmake, src/arch/arm/config.cmake
- make AArch32 FPU possible for verification builds (cherry-pick 453ad135e2bea30f3)
- switch FPU off explicitly in current verification builds
- cherry-pick imx8mm FPU config for verification from branch imx8-fpu-ver as `ARM_imx8mm_verified.cmake`
- cherry-pick exynos5 hyp config for verification from branch exynos5-ver as `ARM_HYP_exynos5_verified.cmake`
These are designed to work together with https://github.com/seL4/l4v/pull/639 so that multiple verification platforms can be present for a particilar L4V_ARCH settings.
=> additional verification configs

src/arch/arm/32/machine/capdl.c, src/arch/arm/64/machine/capdl.c, src/arch/riscv/machine/capdl.c, src/arch/x86/64/machine/capdl.c, src/kernel/sporadic.c
These are only called when CONFIG_DEBUG_BUILD is on, which *usually* means that CONIFG_PRINTING is also enabled, but, it's not necessarily the case.
=> Add missing ifdefs around printing functions

CHANGES, src/plat/ariane/overlay-ariane.dts, src/plat/polarfire/overlay-polarfire.dts, src/plat/qemu-riscv-virt/overlay-qemu-riscv-virt.dts, src/plat/rocketchip/config.cmake, src/plat/rocketchip/overlay-rocketchip-base.dts, src/plat/rocketchip/overlay-rocketchip-zcu102.dts, src/plat/spike/config.cmake, src/plat/spike/overlay-spike.dts, tools/hardware.yml
Without this patch, user-level programs have the ability to map in the core-local interrupt controller on RISC-V platforms which contains the memory-mapped registers for the core-local timer the kernel uses. This is a level of privilege that user-level programs should not have. Writing to the `mtime` register is possible which can then affect the timer interrupts that are delivered to the kernel.
An example of the CLINT memory map can be found in Chapter 9.5 of the SiFive U54-MC manual (which is what the HiFive Unleashed uses). While seL4 does not directly use `mtime`, I believe the emulated `rdtime` instruction uses this register.
I have a patch to sel4test to reproduce my claims here: https://github.com/Ivan-Velickovic/sel4test/commit/289201d6f2cc75aad4702dc9d62a6b71135919ff. Running …
=> Mark CLINT as reserved device on RISC-V platforms

include/object/tcb.h, src/arch/arm/object/tcb.c, src/arch/riscv/object/tcb.c, src/arch/x86/object/tcb.c, src/model/smp.c
Remove `Arch_migrateTCB()`, because nowadays It does the same on all architectures, so the contents can be moved into the generic code. Architectures that support `CONFIG_HAVE_FPU` must provide proper implementations for `nativeThreadUsingFPU()` and `switchFpuOwner()` anyway, as this is also used in other places in the generic kernel code.
I also have doubts that keeping `Arch_migrateTCB()` as empty function with the current signature has a value, as it lacks the destination core parameter. If there is more to do, introducing more specific function might be the better way. That is why it's removed completely.
=> remove Arch_migrateTCB()

libsel4/include/sel4/bootinfo_types.h
Some slot positions in the rootnode would depend on configuration. However that makes it difficult to add new root caps, especially if multiple caps only exist based on configuration. Make all caps always there, but null if not configured.
=> libsel4: Make bootinfo consistent

libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/deprecated.h, libsel4/sel4_arch_include/ia32/sel4/sel4_arch/deprecated.h
Additional header files may now be included in non-C contexts and so we need to guard some C definitions with the __ASSEMBLER__ guards convention.
=> libsel4: Add __ASSEMBLER__ guards in .h files

CMakeLists.txt, config.cmake, tools/hardware/outputs/json.py, tools/hardware_gen.py
There is already existing YAML output for the hardware platform description, this adds JSON output as well.
My main motivation for this is that JSON is part of the standard library of Python and so doesn't need an external dependency to parse. Also, other generated config files such as `gen_config` have JSON and YAML versions so this is being consistent with that.
Example output:
```json
{
"devices": [
{
"start": 0,
"end": 16777216
},
{
"start": 83886080,
"end": 87031808
},
{
"start": 268435456,
"end": 270532608
},
{
"start": 2147483648,
"end": 3291484160
},
{
"start": 3291492352,
"end": 3291496448
},
{
"start": 3291500544,
"end": 1099511627776
}
],
"memory": [
{
"start": 16777216,
"end": 83886080
},
{
"start": 87031808,
"end": 268435456
},
{
"start": 270532608,
"end": 2147483648
}
]
} …
```
=> Output JSON for hardware configuration

include/arch/x86/arch/machine/timer.h
This looks like a trivial omission. The header is required to build with `KernelLAPICMode=X2APIC`.
=> x86: missing x2apic.h header inclusion

include/api/types.h, include/arch/arm/arch/32/mode/machine/timer.h, include/arch/arm/arch/64/mode/machine/timer.h, include/arch/arm/arch/machine/timer.h, include/arch/riscv/arch/machine/timer.h, include/arch/x86/arch/machine/timer.h, include/kernel/thread.h, include/model/statedata.h, src/config/default_domain.c, src/kernel/thread.c, src/machine/capdl.c
- doc: improve comments
- use types time_t and tickts_t properly, currently the semantics are incorrect
- print period and budget with units
The PR in seL4_libs is not necessary, it's just another bit of semantic cleanup.
=> use types time_t and tickts_t properly

include/arch/arm/armv/armv8-a/64/armv/vcpu.h, src/arch/arm/64/kernel/vspace.c, src/arch/arm/config.cmake
These are the changes I needed to introduce to get the C kernel parsed and imported into Isabelle:
- aarch64: avoid void-return statements
- aarch64: DONT_TRANSLATE 32-bit __asm__
- aarch64: don't take address of local vars
- arm: pde_C type is only available on aarch32
I was a bit surprised by the `&cap` where `cap` is local. Well-known limitation of the verification infrastructure.
The 32-bit `__asm__` is a bit disappointing on the verification side (the limitation is irritating, but tracking down the error is terrible), maybe we should think of what we can do about it next time binary verification comes up.
=> AArch64: updates for verification compatibility

include/bootinfo.h, libsel4/include/sel4/bootinfo_types.h, manual/parts/bootup.tex, src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c, src/arch/x86/kernel/boot.c, src/kernel/boot.c
- Provide `seL4_BootInfoFrameSize` for userland, to there is no longer a need to hard-code the 4 KiByte assumption.
- Remove `SEL4_BI_FRAME_SIZE`
For usage examples see:
- seL4/seL4_libs#73
- seL4/capdl#49
=> introduce constant seL4_BootInfoFrameSize 

manual/parts/threads.tex
The manual does not say much about the core affinity of a thread. Add some description.
- replace "master" by "non-MCS"
- improve thread affinity description
=> manual: improve thread affinity description

CHANGES, include/arch/arm/arch/64/mode/model/statedata.h, include/arch/arm/arch/64/mode/object/structures.bf, include/arch/arm/arch/object/smc.h, include/arch/arm/arch/object/structures.h, libsel4/arch_include/arm/sel4/arch/types.h, libsel4/include/sel4/bootinfo_types.h, libsel4/sel4_arch_include/aarch64/interfaces/sel4arch.xml, libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/types.h, libsel4/tools/syscall_stub_gen.py, src/arch/arm/64/object/objecttype.c, src/arch/arm/config.cmake, src/arch/arm/kernel/boot.c, src/arch/arm/object/smc.c, src/object/cnode.c
Add a new capability which certain threads can invoke so seL4 can make SMC calls on ARM platforms in EL2 (virtualized mode) on the thread’s behalf.
See https://sel4.atlassian.net/browse/RFC-9
=> SMC Capability

src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c
- Describe the SMP lock variable mechanism detail.
- Add checks that the lock state is valid, this will catch potential kernel loader problems.
This might catch some porting issues, I was running into this with a broken loader.
=> boot: sanity check for SMP lock variable state

src/fastpath/fastpath.c
This change was missing from commit dc808b3d76fc09741e91ccc53e2738d052c08f0a. Renames `cap_vtable_root_get_mappedASID` to `cap_vspace_cap_get_capMappedASID`, allowing builds with the exception fastpath enabled to build.
=> VM fault fastpath: missing rename of vspace cap ASID function

.github/workflows/proof.yml
The proofs are now running on Isabelle2023
=> github: bump Isabelle version on proof checks

include/arch/arm/armv/armv8-a/64/armv/vcpu.h, src/arch/arm/64/kernel/vspace.c
This overhauls `makeUserPage` to take care of the bit 58 and bitfield gen issues outlined in #1110 
I threw in a verification MODIFIES annotation commit to do less PR littering, it doesn't have any impact on the code.
=> aarch64: makeUserPage rework and some verification MODIFIES annotations

include/arch/arm/arch/object/vcpu.h
Verification requires packed C structures for reasoning. While we previously updated `struct vcpu` to be packed on AArch32, on AArch64 `struct gicVCpuIface` needs extra padding.
This extra padding now aligns a previously un-aligned field on AArch32, meaning that needs to go away, and the comment there adjusted.
ARM_HYP CRefine passed with this change, but might be worth rerunning proofs anyway.
=> arm: tune vcpu/gic struct padding for verification

include/kernel/sporadic.h
Just a slight rephrasing to avoid duplication in the proofs and isolate the heap access from the `if` condition.
=> mcs: rephrase refill_capacity to ease verification

.github/workflows/proof.yml
These proofs are currently still in progress (unfinished), but already check large parts of the kernel and can break when the MCS preprocess check fails.
=> github: add MCS C proofs to proof check

include/kernel/boot.h
This sanity check does not pass reliably on qemu-arm-virt due to it being a virtualized platform.
=> boot: Skip clock sync test on qemu-arm-virt

src/plat/qemu-arm-virt/config.cmake, src/plat/qemu-arm-virt/overlay-qemu-arm-virt32.dts, src/plat/qemu-riscv-virt/config.cmake, src/plat/qemu-riscv-virt/overlay-qemu-riscv-virt32.dts
Use device tree overlay as a smart hack to avoid crashes if 32-bit QEMU is misconfigured or has >=4 GiB RAM.
This cope with the current inability of the seL4 build scripts to handle a full 4 GiB address space without overflows. It handles configurations where a 32-bit QEMU has RAM beyond the 4 GiB border (by accident or design) by simply reserving all memory beyond `0xffffffff`. It avoids that the seL4 build scripts generate regions addresses >= `0x100000000`, which break compilation, because such values don't fit into 32-bit variables used for physical addresses on 32-bit systems.
The long term solution should be a fix in the builds scripts, so a full 4 GiB address space is usable and everything beyond 4 GiB is ignored.
=> qemu: avoid QEMU build/run crashing for 32-bit systems.

src/arch/arm/64/kernel/vspace.c
Report the vspace cap (1) as invalid, instead of the frame cap (0) in decodeARMFrameInvocation to stay consistent with the other architectures.
See also #1075
=> aarch64: make error reporting consistent

include/arch/arm/arch/64/mode/kernel/vspace.h, include/arch/arm/arch/machine/hardware.h, src/arch/arm/64/kernel/vspace.c
This is a bunch of tweaks that make it easier for verification to deal with cap updates, and also to make some things more like what's on the other platforms.
TLDR: a single update using a `_ptr_set_` generated function is fine, but if multiple updates are needed, best fetch the thing, do updates to a local var, and then post back.
=> aarch64: (verification) performPageInvocationUnmap, performASIDPoolInvocation, checkVPAlignment

include/arch/arm/arch/machine/gic_v2.h, include/arch/arm/arch/machine/gic_v3.h
Clearing the pending state only has an effect if the IRQ state is active-and-pending, which happens for edge-triggered interrupts if another edge happens on the IRQ line for the currently active interrupt. This window is small enough to ignore, at worst user space will get another notification, which is harmless.
If unnecessary notifications are unwanted, the pending state should be cleared during seL4_IRQHandler_Ack(), as that covers a much bigger window. However, edge-triggered interrupts are not expected to happen often. Making all interrupt handling slightly faster and the code simpler is the better trade-off.
Reading the GIC config word is very slow for GICv2, see pull #1107.
For a more detailed explanation, see [this](https://github.com/seL4/seL4/pull/1107#issuecomment-1745278447) …
=> ARM: No special handling for edge-triggered IRQs

include/arch/arm/arch/64/mode/fastpath/fastpath.h, include/arch/arm/arch/64/mode/kernel/vspace.h, include/arch/arm/arch/64/mode/object/structures.bf, include/arch/arm/arch/64/mode/object/structures.h, src/arch/arm/64/kernel/vspace.c, src/arch/arm/64/machine/capdl.c, src/arch/arm/64/object/objecttype.c, src/arch/arm/object/smmu.c, src/fastpath/fastpath.c
The vspace (top level PT) cap had non-standard names which were a bit confusing to reason about. The name conflict with capPTBasePtr also spits out fully-qualified names in verification.
This commit updates all the field names of vspace_cap to start with "capVS" and updates all the call sites.
=> aarch64: use VS prefix for vspace_cap fields

CHANGES, tools/helpers.cmake
https://github.com/seL4/seL4/pull/975, which added JSON configuration output, caused the configuration headers to be generated at build-time instead of configure-time.  This broke CAmkES build systems which depend on configuration headers in CAmkES files at configure-time.
This PR makes the configuration headers available at configure-time.
=> Generate configuration headers at configure-time

include/arch/riscv/arch/kernel/traps.h, src/arch/riscv/common_riscv.lds, src/arch/riscv/traps.S
riscv: place traps and fastpath code adjacently
Follow Arm's code where it tries to place traps and vector
code adjacently in a 4KiB page to optimise performance
(through spatial cache locality).
Closes #1091
=> riscv: place traps and fastpath code adjacently

include/kernel/sporadic.h, src/object/objecttype.c, src/object/schedcontrol.c
#498 stipulates that `sc_sporadic` should imply `sc_active`, but the code showed assertion failures for a corresponding check.
It turns out that the failing assertion was wrong in the sense that it checked a different condition. It also turns out that the invariant as stipulated there is true if `scSporadic` is reset in `finaliseCap`. Thanks to @michaelmcinerney for proving that.
This PR:
- fixes `finaliseCap` so that the expected invariant holds
- simplifies `sc_sporadic` again so that it does not have to check `sc_active`
- adds the correct corresponding assertion
- slightly tweaks code ordering in `invokeSchedControl_ConfigureFlags` to make verification easier
=> MCS: preserve sc_sporadic invariant

manual/Makefile, manual/tools/gen_invocations.py, manual/tools/parse_doxygen_xml.py
Different API groups may contain the same function name, for instance `IRQ_Control` `GetTrigger` for RISC-V vs the same for ARM. Duplicate function names with identical parameter lists confuse `doxygen`, leading it to generate a single merged xml entry for both, which means one of the entires will be missing and the other will be potentially wrong.
As @Ivan-Velickovic  and I found out in #530, when the functions are placed in different files and different groups at the same time, doxygen no longer is confused in all cases.
Therefore:
- generate a separate file for each API group
- generate a separate file group_defs.h that contains group definitions
and declares group nesting
Unfortunately, this does not seem to always work (e.g. the toplevel MCS/non-MCS syscalls), so manual inspection is …
=> manual: handle name duplication between groups 

libsel4/include/interfaces/sel4.xml, manual/Doxyfile, manual/tools/gen_invocations.py
(this PR is on top of #1123)
Put MCS-only invocations into their own groups and files. This solves the problem that doxygen gets confused by duplicate function names with the same parameters.
MCS/non-MCS is distinguished by evaluating the `<condition>` field in the API XML definition. If the condition evaluates to true when `CONFIG_KERNEL_MCS` is set, it is an MCS-only method, otherwise it is assumed to be non-MCS or present in both configs.
The longest part of all of this is parsing the condition field, but it's still relatively short and I don't think it warrants use of a full-blown parser generator or library.
Fixes https://github.com/seL4/seL4/issues/558
Also:
- distinguish SetSpace (MCS) by name in the manual to avoid confusion for the reader
- remove obsolete doxygen settings to …
=> manual: group invocations by MCS/non-MCS

include/arch/riscv/arch/machine/timer.h, include/arch/x86/arch/machine/timer.h, include/drivers/timer/arm_generic.h, include/drivers/timer/arm_global.h, include/kernel/sporadic.h, include/machine/timer.h, src/kernel/thread.c
Please see the commit message for a brief explanation of this change. I'll elaborate on that message a little here, but I should point out that I have made this change to the abstract specification, and the proofs for all the invariants we have (which are very detailed regarding the refill lists) all work very nicely.
`refill_ready` currently says that an sc is ready if its head `rTime` is at most the current time plus the kernel WCET. I think there are a couple problems with this. 
First, `refill_unblock_check` might be called on an sc that is ready, but whose head `rTime` is somewhere strictly between the current time, and the current time plus the kernel WCET. This would result in `refill_unblock_check` bringing the head refill forward. This breaks an invariant that the verification …
=> mcs: remove `getKernelWcetTicks` term from `refill_ready`

src/kernel/thread.c
The assert() condition is checked two lines above, so it can never fail.
=> remove useless assert

src/plat/exynos4/config.cmake
The default value is zero anyway.
=> exynos4: remove explicit setting of TIMER_PRECISION

config.cmake
Printing the input DTS file name makes more sense than printing the output DTB name on error. The output likely does not exists and thus this does not help.
=> CMake: show DTS name in error message

include/arch/arm/arch/machine/gic_v2.h, include/arch/arm/arch/machine/gic_v3.h, include/arch/arm/arch/object/smc.h, include/arch/arm/arch/object/smmu.h, include/arch/arm/arch/object/vcpu.h, src/arch/arm/64/kernel/vspace.c, src/arch/arm/machine/gic_v2.c, src/arch/arm/machine/gic_v3.c, src/arch/arm/object/smc.c, src/arch/arm/object/smmu.c, src/arch/arm/object/vcpu.c
Arch_decodeInvocation takes a word_t length and then passes it to functions that take an unsigned int length. This was OK on 32-bit where these types are the same, but on 64-bit this is a downcast without a range check. It isn't clear why this doesn't trip a compiler warning.
=> Arm 64-bit: do not use unsigned int for arg length

tools/invocation_header_gen.py
Since commit cf8be663 this is no longer needed.
=> python: remove unused template parameter

.github/workflows/compilation-checks.yml, .github/workflows/sel4test-deploy.yml, .github/workflows/sel4test-hw.yml, .github/workflows/sel4test-sim.yml
Changes
- CI: build standalone kernel for RISCV64 with LLVM
- CI: run sim and HW build with LLVM for RISCV
To be me merged one these docker containers have been updated, so the workflows use them
- https://hub.docker.com/r/sel4/sel4test-hw
- https://hub.docker.com/r/sel4/sel4test-sim
related CI-Actions PR
- https://github.com/seL4/ci-actions/pull/295
- https://github.com/seL4/ci-actions/pull/299
=> CI: build and test kernel for RISCV64 with LLVM

include/arch/arm/arch/64/mode/object/structures.bf, src/arch/arm/64/kernel/vspace.c, src/arch/arm/64/object/objecttype.c, src/plat/tqma8xqp1gb/config.cmake
- refactor/remove `getMapRefForASID` for verification convenience
- add retype annotations for AArch64
- constrain `irq_w` field width in `VPPIEvent` to maxIRQ bit width
The last of these (`irq_w` field width) might be a problem on `tqma8xqp1gb` where `maxIRQ` is 512, which means the irq bit width is 10 instead of 9 like on the other platforms. This looks like a mistake to me, though, it'd be strange if the platform had exactly 513 IRQs instead of 512 (in which case maxIRQ should be set to 511). See also #1155.
=> aarch64 verification tweaks

src/arch/arm/64/kernel/vspace.c
This PR types `invLabel` consistently as `word_t`, not sometimes as unsigned `int`. This makes verification easier because it avoids unnecessary casts.
=> aarch64/vspace: avoid unnecessary casts

src/arch/arm/64/kernel/vspace.c
Bring the type of `i` into line with what the other architectures do in `decode...MMUInvocation` for `ASIDControl`. This makes it easier to re-use those proofs.
=> aarch64/vspace: adjust type for verification

libsel4/arch_include/arm/interfaces/sel4arch.xml, libsel4/arch_include/riscv/interfaces/sel4arch.xml, libsel4/arch_include/x86/interfaces/sel4arch.xml, libsel4/include/interfaces/sel4.xml, libsel4/include/sel4/syscalls.h, libsel4/include/sel4/syscalls_master.h, libsel4/include/sel4/syscalls_mcs.h, libsel4/sel4_arch_include/x86_64/interfaces/sel4arch.xml
@Indanz @lsf37 
A first conservative go at addressing https://github.com/seL4/seL4/issues/565
- made method names consistent
- deleted duplicates for manual_name and name
There many other acronyms in manual headings, e.g. Recv, but renaming these is probably unnecessary.
=> make method names consistent

src/arch/arm/64/kernel/vspace.c
Test the PTE directly for being of page type and avoid ptr access to ease verification in unmapPage.
=> aarch64/vspace: test for page type directly

gcc.cmake
Mark `CROSS_COMPILER_PREFIX` as meaningful to `gcc.cmake`, so that it is propagated for all cases where `gcc.cmake` used.
`gcc.cmake` may be evaluated multiple times by CMake during configuration. Without this patch, `gcc.cmake` may be evaluated without `CROSS_COMPILER_PREFIX` set in some cases, even if `-DCROSS_COMPILER_PREFIX=<...>` was specified in the CMake command line.
[Documentation for CMAKE_TRY_COMPILE_PLATFORM_VARIABLES](https://cmake.org/cmake/help/latest/variable/CMAKE_TRY_COMPILE_PLATFORM_VARIABLES.html).
=> cmake: propagate `CROSS_COMPILER_PREFIX`

src/arch/arm/64/kernel/vspace.c
Fixing up a small detail in error reporting: `seL4_InvalidCapability` expects `invalidCapNumber` to be set (currently has `invalidArgumentNumber`, might have been a copy/paste error).
=> aarch64/vspace: fix error reporting in decode

.github/workflows/compilation-checks.yml, .github/workflows/manual.yml, .github/workflows/proof.yml, .github/workflows/sel4bench-pr.yml, .github/workflows/sel4test-deploy.yml, .github/workflows/sel4test-hw.yml, .github/workflows/xml_lint.yml
GitHub has updated the LTS node.js version from 16 to 20 and is starting to show warnings for node16 actions.
=> github: bump GitHub actions to node20

src/arch/arm/64/kernel/vspace.c
As in the other architectures, avoid unnecessary casts for the loop counter by making it a `word_t`.
=> aarch64/vspace: type of counter in ASIDPoolAssign

.github/workflows/sel4bench-pr.yml, .github/workflows/sel4test-hw.yml, .github/workflows/sel4test-sim.yml
This also removes the space in the workflow name to ensure there are no side effects when using it as an identifier.
This applies what has been done in https://github.com/seL4/camkes-vm-examples/pull/69
=> CI: cancel older concurrent PR runs

include/arch/arm/arch/64/mode/machine/fpu.h
Current verification model does not include lazy FPU switching, i.e. it acts as if this function always returns true, so no FPU faults could be produced. In order to guard against deriving a contradiction, we don't allow the C parser to translate it.
=> AArch64: mark isFpuEnable as DONT_TRANSLATE

src/plat/qemu-arm-virt/config.cmake
- CMake, QEMU/arm: fix parser usage, so the "ve" extension is enabled
- QEMU/arm: select CPU from architecture, so aarch32 defaults to Cortex-A15 and aarch64 to Cortex-A53
Fixed the issue from https://github.com/seL4/seL4/pull/824#issuecomment-1921221807
Since we are not using QEMU for ARMv7 virtualzation, these issues have not shown up. See also https://github.com/seL4/camkes-vm-examples/issues/73
=> Fix QEMU/arm CPU selection

config.cmake
Allow multiple overlay files to be specified. This supports custom tooling support to add additional memory reserve regions to a platform.
EG:
```
cmake -DKernelCustomDTSOverlay=../src/plat/imx6/overlay-nitrogen6sx.dts .
-- Found GCC with prefix arm-linux-gnueabi-
-- Appending /tmp/tmp.5Kv410Y6vE/kernel/src/plat/imx6/overlay-nitrogen6sx.dts overlay
-- /tmp/tmp.5Kv410Y6vE/kernel/build/gen_headers/plat/machine/devices_gen.h is out of date. Regenerating from DTB...
cmake -DKernelCustomDTSOverlay="../src/plat/imx6/overlay-nitrogen6sx.dts;../src/plat/imx6/overlay-wandq.dts" .
-- Found GCC with prefix arm-linux-gnueabi-
-- Appending /tmp/tmp.5Kv410Y6vE/kernel/src/plat/imx6/overlay-nitrogen6sx.dts overlay
-- Appending /tmp/tmp.5Kv410Y6vE/kernel/src/plat/imx6/overlay-wandq.dts overlay
-- …
```
=> cmake: Support multiple overlay files

.github/workflows/proof.yml
Proof artifact upload had name clashes for different artifacts from the same job that previously would overwrite each other and with v4 actions now error. This commit disambiguates the names.
=> github: disambiguate proof artifact upload

src/plat/bcm2711/overlay-rpi4.dts, src/plat/bcm2837/overlay-rpi3.dts, src/plat/exynos5/overlay-exynos5250.dts, src/plat/exynos5/overlay-exynos5410.dts, src/plat/exynos5/overlay-exynos5422.dts, src/plat/fvp/overlay-fvp.dts, src/plat/hikey/overlay-hikey.dts, src/plat/imx7/overlay-imx7sabre.dts, src/plat/imx8m-evk/overlay-imx8mm-evk.dts, src/plat/imx8m-evk/overlay-imx8mq-evk.dts, src/plat/maaxboard/overlay-maaxboard.dts, src/plat/odroidc2/overlay-odroidc2.dts, src/plat/odroidc4/overlay-odroidc4.dts, src/plat/qemu-arm-virt/overlay-qemu-arm-virt.dts, src/plat/quartz64/overlay-quartz64.dts, src/plat/rockpro64/overlay-rockpro64.dts, src/plat/tk1/overlay-tk1.dts, src/plat/tqma8xqp1gb/overlay-tqma8xqp1gb.dts, src/plat/tx1/overlay-tx1.dts, src/plat/tx2/overlay-tx2.dts, src/plat/zynqmp/overlay-zynqmp.dts
These calls can now be implemented via binding the /timer driver in the elfloader's device tree configuration.
Test with: seL4/seL4_tools#168
=> elfloader: Replace calls to reset_cntvoff

CHANGES, src/arch/arm/object/vcpu.c
The vcpu is not guaranteed to be associated with a TCB at this point, so access to vcpuTCB must be guarded.
Fixes #1199
Test with: https://github.com/seL4/sel4test/pull/114
=> vcpu: guard against NULL ptr dereference

src/plat/odroidc4/config.cmake
The S905X3 manual (Revision 02) specifies the highest IRQ to be 255 in section 7.10.2 of the manual.
This issue was encountered when trying to use the PCIe device on the platform
=> Fix Odroid-C4 MAX_IRQ setting

tools/dts/odroidc4.dts
The Odroid-C4 is supposed to have 4GB of DDR memory.
According to the SoC manual (S905X3 Revision 02) the DDR region goes from 0x0 to 0xF57FFFFF in Table 7-1.
=> Fix DDR region for Odroid-C4

include/arch/riscv/arch/model/smp.h
Partially revert commit https://github.com/seL4/seL4/commit/70d1a5f792fbe1ae59a79dd5dcc413cf69447aa0.
Can't include arch/machine.h because that will cause a circular include dependency.
=> RISC-V SMP: Fix Compile Error

CHANGES, include/arch/arm/arch/32/mode/machine.h, include/arch/arm/arch/object/vcpu.h, include/arch/arm/armv/armv7-a/armv/vcpu.h, include/arch/arm/armv/armv8-a/64/armv/vcpu.h, libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/constants.h, libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h
Currently the seL4_VCPUReg enum only defines the seL4_VCPUReg_VMPIDR_EL2 register when the kernel is configured for SMP. This register should be available for unicore systems too as otherwise a user level VMM is not able to control the value of MPIDR_EL1 that the guest VM reads.
Resolves https://github.com/seL4/seL4/issues/1015
=> ARM: Allow VMPIDR_EL2 reg to be set on unicore

.gitignore, include/machine/interrupt.h, libsel4/include/sel4/syscalls.h, manual/Makefile, manual/manual.tex, manual/parts/glossary.tex, manual/parts/io.tex
- add a glossary to the manual
- consistent spelling of CSpace and IRQ in the API docs
- AU spelling and remove trailing whitespace in `manual/parts/io.tex`
=> Add glossary to manual

libsel4/arch_include/arm/interfaces/sel4arch.xml, libsel4/arch_include/x86/interfaces/sel4arch.xml, libsel4/include/interfaces/sel4.xml, libsel4/sel4_arch_include/x86_64/interfaces/sel4arch.xml
The seL4 API Reference points to a number of references that can only be resolved in the manual, and not in the online reference. E.g. search for "autoref" on https://docs.sel4.systems/projects/sel4/api-doc.html
The updates in this PR wrap the references in <docref> tags so that they only appear in the manual, not online. This is standard practise for the seL4 manual and API references.
=> Wrap docref references in <docref> tag

include/arch/riscv/arch/kernel/traps.h, src/arch/riscv/kernel/boot.c, src/arch/riscv/traps.S
Making this a function makes debugging a bit nicer, as we have a nice function symbol available then
=> RISC-V: make trap_entry a function 

.github/workflows/proof.yml
CRefine is now available for AARCH64 in l4v.
=> github: add AARCH64 C proof session

include/arch/arm/arch/benchmark.h, src/benchmark/benchmark_utilisation.c
Previously `ccnt_num_overflows` was accessed using the `NODE_STATE` macro. 
On SMP configurations, this would look for the `ccnt_num_overflows` value 
in the system node state (`nodeState_t`) in the `smpStatedata` struct. However,
this value resides in the cpu node state (`archNodeState_t`) and should be accessed
using the `ARCH_NODE_STATE` macro.
=> Fix incorrect use of NODE_STATE to access ccnt_num_overflows

src/kernel/boot.c
The check was not enforcing the minimum radix intended by 5fac9e8 and still allowed a radix of 4 to be specified.
=> boot: Fix root cnode size compile-time assert

tools/helpers.cmake
- remove obsolete variable. Seems it's a merge artifact that should never have been in commit ad4ea6cd, and commit c642a398 moved handling to a python script anyway.
- add missing bracket in comment.
=> trivial CMake cleanup

libsel4/tools/syscall_stub_gen_rs.py
Update script to match current code base:
- fix: brackets in check
- fix: use `CONFIG_ENABLE_SMP_SUPPORT`
- conditions for `CONFIG_MAX_NUM_NODES` have been removed
See also https://github.com/seL4/seL4/issues/1223#issuecomment-2015409628, https://github.com/seL4/seL4/issues/1223#issuecomment-2015441234
=> fix rust stub generation script

include/arch/arm/arch/64/mode/machine.h, libsel4/include/sel4/syscalls.h, src/arch/arm/64/traps.S, src/arch/riscv/head.S
Check for `CONFIG_ENABLE_SMP_SUPPORT` everywhere instead of checking `CONFIG_MAX_NUM_NODES > 1`. This are the remaining places in the code where `CONFIG_MAX_NUM_NODES` was used in the check. This change now allows enabling SMP support manually with just one node also, which comes handy for running some test configurations.
=> make SMP conditional check more general

include/api/types.h
The prior behavior would emit ANSI escape codes which set the terminal
foreground color to black bold (`[30;1m`), leaving the default
background color. On many terminals configured with a dark color scheme,
this creates black on black characters, i.e. the output is invisible.
This change moves to a better adapted output, where the output is only
marked as bold (`[1m]`), which works well on all color schemes.
Fixes #1243
=> fix: invisible chars due to ANSI escape codes

include/model/statedata.h, include/object/tcb.h, src/kernel/boot.c, src/kernel/thread.c, src/model/statedata.c, src/object/tcb.c
This introduces library functions for updating the linked lists which use the `tcbSchedNext` and `tcbSchedPrev` pointers of a TCB, and uses these to perform the updates to the ready queues and the release queue.
In order to accommodate this, `ksReleaseQueue` is now of type `tcb_queue_t`.
=> mcs: more uniformly handle ready and release queue updates

tools/bitfield_gen.py
Replace `"\<"` in strings with `"\\<"`. Until recently python did not complain about this illegal escape sequence, but now it warns.
I've checked that we're not replacing anything in raw strings (`r"..."` and `r'...'`).
=> bitfield_gen: properly escape backslash

src/plat/pc99/machine/ioapic.c
IOAPICS can have varying numbers of lines attached.
The actual number can be accessed in the top 16 bits of the
version register.
Rather than assuming fixed 24 lines per IRQ, read the actual number
and use that.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
=> Only access IOAPIC registers that are actually present

libsel4/sel4_plat_include/imx8mp-evk/sel4/plat/api/constants.h, src/plat/imx8m-evk/config.cmake, src/plat/imx8m-evk/overlay-imx8mp-evk.dts, tools/dts/imx8mp-evk.dts
This new platform is NXP Semiconductor's Evaluation Kit for the i.MX 8M Plus Applications Processor. It's from the i.MX 8M family of processors and is largely similar to the existing i.MX 8M Quad and i.MX 8M Mini platforms.
This port is not tested with the EVK, but it's tested against [Compulab's IOT-GATE-IMX8PLUS](https://www.compulab.com/products/iot-gateways/iot-gate-imx8plus-industrial-arm-iot-gateway/#overview) which is based on the same SoC but has a different memory layout. The device tree included in the port is for the EVK.
=> Add new imx8mp-evk platform

.github/workflows/proof.yml
Use the Isabelle version set in the verification manifest instead of overriding to a specific version here. This will automatically update as the verification repository updates to new Isabelle versions.
=> github: use default Isabelle version for proofs

include/plat/pc99/plat/machine.h, src/plat/pc99/machine/ioapic.c
Correctly mask the IOAPICVER register to the Maximum Redirection Entry field to potential avoid spurious higher bits on e.g. AMD processors.
Set IOAPIC_IRQ_LINES to the maximum value this field is allowed to return (239+1). While our `haswell` machines report 24 IRQ lines as expected, the `skylake` machines report 120.
The only impact should be the size of the ioredtbl_state array.
Sources: it was extremely hard to find actual docs for the IOAPIC. The Intel manual was not helpful. [This ancient PDF](https://pdos.csail.mit.edu/6.828/2016/readings/ia32/ioapic.pdf) had information on the register format, max value, and masking requirements, which I followed here. This seems to be consistent with what FreeBSD does in e.g. [apicreg.h](https://cocalc.com/github/freebsd/freebsd-src/blob/main/sys/ …
=> ioapic: set IOAPIC_IRQ_LINES to max allowed

src/arch/riscv/kernel/vspace.c, src/arch/x86/kernel/vspace.c
There is a warning when creating a write-only mapping on AArch32/AArch64.
This patch simply makes the message consistent across all architectures since the behaviour when creating a write-only mapping is also consistent across all architectures.
`x86/kernel/vspace.c` is used for x86 and ia32 right?
=> Make write-only mapping message consistent

src/arch/arm/armv/armv7-a/machine_asm.S, src/arch/arm/armv/armv7-a/tlb.c
- `lockTLBEntry` uses the global `tlbLockCount` as input without checking bounds. This is fine, because the function is called at most 2 times on unicore platforms, but this is only apparent when checking the entire possible calling context.
Make this bound obvious locally by doing nothing if the function is called with values of `tlbLockCount` of 2 or greater. This is safe, because TLB lockdown is a performance change only. Also add an assert for debug mode, because we want to know if calling context ever changes.
- remove TLB locking for Cortex A9. The code shared the A8 locking sequence with A9, but not all of these instructions are supported on A9. As far as we have been able to tell, they are silently ignored on the A9 platforms that seL4 supports, but it is of course better to …
=> arm tlb: guard TLB lockdown count

libsel4/arch_include/arm/interfaces/sel4arch.xml, libsel4/arch_include/riscv/interfaces/sel4arch.xml, libsel4/arch_include/x86/interfaces/sel4arch.xml, libsel4/include/interfaces/sel4.xml, libsel4/include/sel4/syscalls.h, libsel4/include/sel4/syscalls_master.h, libsel4/include/sel4/syscalls_mcs.h, libsel4/sel4_arch_include/aarch64/interfaces/sel4arch.xml, manual/parts/cspace.tex, manual/parts/glossary.tex, manual/parts/io.tex, manual/parts/ipc.tex, manual/parts/objects.tex, manual/parts/threads.tex, manual/parts/vspace.tex
I reviewed the user manual up to before section 10.7 (part 1) with regard to typos and consistency. Since I am neither a native speaker nor an expert, please review my changes, thanks.
=> Review of user manual (only typos and syntax)

include/arch/arm/armv/armv7-a/armv/vcpu.h, include/arch/arm/armv/armv8-a/64/armv/vcpu.h
When KernelArmDisableWFIWFETraps is disabled (trapping of WFI/WFE is enabled), the kernel traps WFx instructions from both native and vCPU threads. This change makes the code in line with the config description.
In any case, there don't exist many use cases for trapping WFx from native threads vs vCPU threads. Example: kvm uses this to yield physical CPU time to other vCPUs instead of busy waiting.
=> vcpu: only trap WFx instructions from vCPUs

src/model/preemption.c
This reorders the guard in one of the if statements in preemptionPoint to first check isIRQPending, since it is the most likely cause of this guard being true. This also eases verification.
=> mcs: rewrite guard in preemptionPoint

manual/parts/threads.tex
I find it difficult to read the fault types like this, there's too many of them (and there are more architecture dependent ones that are not part of this list yet).
=> manual: make list of fault types easier to read

libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/constants.h, libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h
`*_Length` constants exist for all `*_Msg` enums except for `seL4_VPPIEvent_Msg`.
=> arm: add missing `seL4_VPPIEvent_Length` constants

tools/hardware/config.py
This addresses #1186
It's not entirely clear to me what this does for AArch64 -- is that code used there?
=> config.py: fix SUPERSECTION_BITS for arm_hyp

src/arch/arm/32/object/objecttype.c, src/arch/x86/32/object/objecttype.c
I ran into this while reviewing https://github.com/seL4/seL4/pull/1289. It looks broken to pass the size here, as the function just expects the 2^n bit-size. This wipes the entire memory practically.
This came in with commit 16c34811.
=> fix parameter for log buffer cleanup

CAVEATS.md, CHANGES.md, configs/AARCH64_bcm2711_verified.cmake, configs/AARCH64_zynqmp_verified.cmake
The AARCH64 config now also works for functional correctness for zcu102/zcu106 and rpi4.
Needs the corresponding l4v PR to be merged first.
=> configs: add zynqmp and rpi4 to verified platforms

tools/python-deps/setup.py
See also https://github.com/seL4/ci-actions/issues/329, our old version of autopep8 crashes on more recent python code. Layout should be stable.
- bump version of autopep8
- bump version of sel4-deps
- update maintainer email
=> bump autopep8 version

tools/python-deps/setup.py
- require python >= 3
- require pyyaml < 6, because cmake-format breaks with pyyaml >= 6
- update upload instructions
- provide long-form release description of PyPi
- bump version, because the < 6 requirement might technically break compatibility
=> sel4-deps: tighten deps; update instructions

include/object/tcb.h, src/kernel/thread.c, src/object/tcb.c
This refactors awaken, providing an inline function for the while loop condition, and modifying tcbReleaseDequeue to now perform the entire loop body.
Since tcbReleaseDequeue will perform tcbReleaseRemove on the head of the release queue, the variable ksReprogram will be set to true within tcbReleaseRemove, and therefore, we do not need to set this variable separately within the loop body of awaken.
=> mcs: refactor awaken

include/object/schedcontext.h, src/object/objecttype.c, src/object/schedcontext.c, src/object/tcb.c
This removes the tcb parameter from schedContext_unbindTCB, which is unnecessary, since it is always the scTcb of the given sc.
=> mcs: remove parameter from schedContext_unbindTCB

src/plat/qemu-arm-virt/config.cmake, src/plat/qemu-riscv-virt/config.cmake
When starting on a fresh workspace with a custom seL4 plain CMake build flow, it turns out that CMake has not created `CMAKE_BINARY_DIR` yet when the `QEMU DTB` dumping command runs. QEMU will not create the DTB file parent folder(s) either, but fails with an error. Then CMake prints the error and finishes gracefully, creating `CMAKE_BINARY_DIR` with some configuration cache. 
```
$ cmake -G Ninja -S /mnt/repos/sel4/sel4test -B build-sel4test-qemu-riscv-virt -DCMAKE_MODULE_PATH=/mnt/repos/sel4/seL4;/mnt/repos/sel4/seL4_tools;/mnt/repos/sel4/seL4_tools/cmake-tool/helpers;/mnt/repos/sel4/seL4_tools/elfloader-tool;/mnt/repos/sel4/musllibc;/mnt/repos/sel4/seL4_libs;/mnt/repos/sel4/seL4_projects_libs;/mnt/repos/sel4/sel4runtime;/mnt/repos/sel4/util_libs;/mnt/repos/sel4/projects_libs …
```
=> QEMU: ensure output folder exists

include/arch/riscv/arch/fastpath/fastpath.h, src/arch/riscv/c_traps.c
I can't find a reason why it is done in such a complicated way, when the RISC-V port was added in 83ba0847.
=> risc-v: remove special handling for restoring tp

src/kernel/thread.c
This eases verification by using a local variable which remains unchanged during execution of the function.
This preserves semantics since tcbSchedDequeue will not modify the scTcb field of the given sc.
=> mcs: use local variable in postpone

CMakeLists.txt, tools/condition.py, tools/invocation_json_gen.py
The primary purpose of this PR is to generate `generated/invocations_all.json`, a JSON file containing a mapping between invocation labels and the numbers they correspond to.
It works by modifying `invocation_gen_header.py` to eagerly evaluate whether a particular invocation will exist for the current configuration and emitting an intermediate JSON file for each of the three XML invocation definition files. We then add a new build step that stitches the intermediate files together in the correct order to produce a JSON file of the format
```
{
"UntypedRetype": 1,
"TCBReadRegisters": 2,
"TCBWriteRegisters": 3,
...
}
```
The motivation of this PR is to simplify the implementation of the Microkit and avoid having to manually define this mapping, which gets annoying and error-prone when …
=> Adding auto-generation of a config file for invocation numbers

include/arch/arm/arch/32/mode/machine.h, include/arch/arm/arch/32/mode/machine_pl2.h
- `getKernelStack()` is never called
- `readHTPIDRO()` was only called in `getKernelStack()`
- `readTPIDRPRW()` is only used in hyp configurations
=> aarch32: remove unused functions

src/util.c
Make `str_to_long` more defensive against malformed content, since this function runs on user (cmd line) input on x86. The input is from boot time, i.e. trusted, but the function should still be memory safe.
This change does not fix overflow issues which may still lead to undefined behaviour when the supplied string has a value that is too large.
=> utils: safer str_to_long

include/arch/arm/arch/machine.h, include/arch/riscv/arch/machine.h, include/arch/x86/arch/machine.h, src/arch/arm/32/object/objecttype.c, src/arch/arm/64/object/objecttype.c
Do not perform cache flushing in clearMemory. Instead flush the cache only for those object types where it is necessary, and only when the object is retyped, not when the untyped cap is reset.
This reduces overall need for flushing and delays it to the point of use. This should speed up boot time significantly, but may impact WCET, because the largest flush is now the largest page size (e.g. 24) instead of CONFIG_RESET_CHUNK_BITS (8). The user could already request a flush of the largest page size before, though, so it this may not actually impact WCET. Remains to be investigated.
Why this is safe:
- Flushing is only necessary for objects that are seen by other parts of the system, not for kernel-internal object. These objects are non-device frames (including IOMMU pages) and page tables. …
=> move cache flush from untyped reset to retype

include/drivers/irq/riscv_plic0.h, src/plat/ariane/config.cmake
The current upstream support for Ariane is broken; being unable to launch seL4test (crashes on IRQ setup). This is due to the PLIC being disabled and the an interrupt max of 0 being set.
This commit re-enables the PLIC for Ariane as it is inoperable otherwise. I believe the original PLIC change was backed out due to uncertainty about functionality between different rounds of synthesis, but working sometimes seems like a better outcome than working never.
This is also required to enable Microkit and LibVMM support for Ariane.
Here is an example of seL4test output *without* this change applied:
```
ELF-loader started on (HART 0) (NODES 1)
paddr=[80200000..80662fff]
Looking for DTB in CPIO archive...found at 802b8228.
Loaded DTB from 802b8228.
paddr=[84024000..84024fff]
ELF-loading image …
```
=> Fix Ariane (CVA6) support

include/drivers/irq/riscv_plic0.h, src/plat/qemu-riscv-virt/config.cmake
This produced 'sifive_plic_write: Invalid register write 0x180' in QEMU. https://github.com/seL4/seL4/issues/1350#issuecomment-2464273308
The rest of the code only runs up to `i <= PLIC_MAX_IRQ`, not `+ 1`.
Partially fixes #1350 
---
Also updates the value of `MAX_IRQ` to 95 to completely fix #1350. Yes, the correct value is 95 as 96 is [0, 96) -> [1, 95]. This is not the better solution mentioned but that's a fair amount of work.
=> riscv: fix off-by-1 write for PLIC IRQ priorities, and QEMU MAX_IRQ

src/kernel/boot.c
In cases where the kernel is passed a very fragmented map of available memory (specifically when booting from GRUB on x86), it is possible for multiple available regions to overlap with a single reserved region.
Currently, if there is an overlap (where `avail_reg[a].start >= reserved[r].start`), the available region is trimmed and the region index is incremented. This causes any other overlapping regions to be handled as if they are non-overlapping, since it's now looking at the next reserved region. This eventually leads to reserved memory being passed to the root task and can cause corruption issues if it is used.
It is fine to skip this index increment since the available region is now either empty or non-overlapping, and both cases are already trivially handled.
[Here's a link to the …
=> boot: fix init_freemem skipping reserved regions

README.md
Fixes the URL for kernel features in README, currently tries to redirect to: https://docs.sel4.systems/projects/sel4/(/projects/sel4/status) (404)
=> docs: README: Fix url to kernel features

include/arch/riscv/arch/64/mode/hardware.h
This revises comments of riscv64 kernel address mapping for easier reading purposes.
=> arch/riscv64: revise comments

src/arch/x86/object/ioport.c
Multiple versions of GCC were unable to determine that these variables in `decodeX86PortInvocation` are initialized in all cases.
Oddly, this compilation failure was only observed with `-O1`. Compilation with `-O2` was not failing.
=> x86: initialize variables

src/machine/capdl.c
This fixes a potential memory corruption in `add_to_seen()` function,
=> machine/capdl.c: fix a corruption

src/kernel/cspace.c
The binary verification tools do not support `__builtin_unreachable`, and `resolveAddressBits` is in scope for binary verification.
=> Remove `UNREACHABLE()` from `resolveAddressBits`

src/model/statedata.c
The `TCB_PTR_CTE_PTR()` macro assumes that thread block aligns with `bit(seL4_TCBBits)`. However this is not true for the idle thread block, thus using the macro with idle thread leads to invalid results. This fixes the issue by apply same alignment to idle thread block so that the macro applies to all threads.
=> machine/statedata: align idle thread

manual/parts/objects.tex
This drops unnecessary `iz` text at chapter end.
=> manual/objects: clean garbage

libsel4/sel4_plat_include/imx93/sel4/plat/api/constants.h, src/drivers/serial/config.cmake, src/plat/imx93/config.cmake, src/plat/imx93/overlay-imx93.dts, tools/dts/imx93.dts, tools/hardware.yml
This generic support for any i.MX93 SoC based platform. It comes with up to two CPU cores and up to 2 GB of memory. Specific board differences can be resolved easily by using `KernelCustomDTSOverlay` to tweak the details.
~~One known issue is that there are some bogus device memory regions created, I will update the PR when I found out what causes that.~~
~~The board has an undocumented gap of 32 MB in its memory space at 0x96000000, I will ask NXP where it's coming from.~~
=> Add i.MX93 SoC support

.github/workflows/pr.yml
The default python version changes on ubuntu-24, which breaks the version of cmake-format we are currently using.
=> github: pin style check to ubuntu-22.04

CHANGES.md, src/plat/tqma8xqp1gb/config.cmake
Following on from the [discussion](https://github.com/seL4/seL4/pull/1356#discussion_r1865124949) in #1356, the settings `KernelArmVtimerUpdateVOffset` and
`KernelArmDisableWFIWFETraps` should be project settings, not platform settings for `tqma`. The values set here are not required for the platform to work -- they just provide a different default.
Setting these in platform configs could lead to inconsistent project builds when switching between platforms.
=> tqma: remove virtualisation project settings

src/arch/arm/32/kernel/vspace.c, src/arch/arm/64/kernel/vspace.c, src/arch/riscv/kernel/vspace.c, src/arch/x86/kernel/vspace.c
This existed for ARM32, but not for ARM64, RISCV-V, or X86.
I'm not too fussed on the error message or the existence of the comment, feel free to adjust if desired.
=> vspace: userError for no unallocated ASID pools

README.md
The GetttingStarted page was renamed and most of the page was not really about build  instructions. Point to the right section of the new page instead.
=> README: fix GettingStarted link for docsite update

gcc.cmake
The previous commit 05858be didn't actually add it to both instances of the if/else statement, and so doesn't actually work in all cases (e.g. with `../init-build.sh`).
=> cmake: add `riscv-none-elf-` as valid gcc prefix

include/drivers/irq/riscv_plic0.h, libsel4/sel4_plat_include/cheshire/sel4/plat/api/constants.h, src/plat/cheshire/config.cmake, src/plat/cheshire/overlay-cheshire.dts, tools/dts/cheshire.dts, tools/hardware.yml
This pull request adds support for the [Cheshire](https://github.com/pulp-platform/cheshire) platform - a system built around the CVA6 RISC-V APU design. This implementation specifically targets the Xilinx FPGA implementation of Cheshire for the Digilent Genesys 2 development board.
Cheshire is very similar to the extant Ariane CVA6 design supported by seL4, but is a system which is designed to have a stable interface and behaviour for 64 bit operating systems, as contrasted to a focus on 32 bit applications for Ariane.
Cheshire supports the RISC-V H-extension, but as of now it does not appear to work correctly under seL4 (apparently due to HW issues). As a result, this PR omits any H-extension related code.
=> Platform support for Cheshire (Digilent Genesys2)

src/arch/arm/platform_gen.h.in, src/arch/riscv/platform_gen.h.in
Presumably intended to be something like
typedef enum IRQConstants { ... } platform_interrupt_t;
this instead declares a symbol that is exported and kept in the binary, but is never used. Remove it.
Spotted as my kernel.elf binary contained a strange symbol:
ffffffff8401b7f0 g     O .bss	0000000000000004 platform_interrupt_t
cc @wom-bat
=> platform_gen.h.in: remove platform_interrupt_t symbol

include/arch/arm/arch/64/mode/machine/fpu.h
On aarch64, clang interprets the compile option `-mgeneral-regs-only` as disabling all FPU-related registers and instructions, which not only include those generated by the compiler (which is how gcc would interpret this option), but also those in (inline) assemblies written explicitly by the programmer, which gcc does not forbid with this option. This commit enables FPU-related registers and instruction explicitly in the FPU-context switching code, so the kernel will build under clang-18 on aarch64.
LLVM project's issue tracking the inconsistency of this option between clang and gcc: https://github.com/llvm/llvm-project/issues/30140 --- it remains an open issue as of this writing.
Similar commit in other projects: https://github.com/TF-RMM/tf-rmm/commit/ffcc90415364933dcd5670226a0b9c9573f …
=> aarch64: fix building with clang-18

src/arch/riscv/c_traps.c
=> riscv: traps coming from s-mode should not be treated as a u-mode trap

src/arch/arm/32/head.S, src/arch/arm/32/traps.S, src/arch/arm/common_arm.lds, src/arch/riscv/common_riscv.lds
For ARM:
Essentially, the `sp' register is banked between different PMODEs.
https://developer.arm.com/documentation/den0013/d/ARM-Processor-Modes-and-Registers/Registers
We initialise a stack that we will begin on when handling an exception.
For RISC-V:
Presumably this was copied from the ARM linker script without knowing why it was there, as no RISC-V code references it.
=> document&rename breakpoint_stack (arm32), remove it (riscv/arm64)

config.cmake, tools/hardware/outputs/c_header.py, tools/hardware/outputs/compat_strings.py, tools/hardware/outputs/elfloader.py, tools/hardware/outputs/json.py, tools/hardware/outputs/yaml.py, tools/hardware_gen.py
Right now the `platform_gen.json` and `platform_gen.yaml` files contain regions that are not actually used by the kernel. This is fine for `platform_gen.h` because they are guarded by #ifdefs with kernel config defines but the same approach does not work for YAML and JSON.
So, this patch changes the Python scripts that generate this files so that they only generate the regions that actually end up being used.
Based on @kent-mcleod's patch from https://github.com/seL4/seL4/issues/1197#issuecomment-1943692023.
Closes https://github.com/seL4/seL4/issues/1197.
=> platform_gen: only generate regions that are actually used

include/fastpath/fastpath.h, include/object/reply.h, src/fastpath/fastpath.c, src/kernel/thread.c, src/object/endpoint.c, src/object/reply.c
We no longer guarantee the invariant that the replyObject reference is `NULL` when the thread state is not `BlockedOnReceive` or `BlockedOnReply`.
It is likely that this invariant was true in the kernel so far, but proving it would require a new proof that the reference is already `NULL` for any `setThreadState` to a simple state such as `Running`, `Inactive`, `Restart`. This either means reasoning about the state the thread had before `setThreadSate`, or explicitly setting the reference to `NULL` more
often.
There are many of these `setThreadState` instances, and the benefit of maintaining the invariant is low. Not maintaining the invariant removes some state updates from low-level functions (called often) at the cost of adding some if-checks in higher-level functions (called less …
=> thread state: abandon replyObject NULL invariant

src/object/endpoint.c
The value of `replyObject` for a thread that is `BlockedOnSend` is unspecified by the design, and unset by the implementation, so `cancelIPC()` may not assume that it will be null when the thread is `BlockedOnSend`.
This PR is motivated by and required by https://github.com/seL4/l4v/pull/831.
=> Fix apparent potential bug in `cancelIPC` for MCS

libsel4/arch_include/riscv/interfaces/object-api-arch.xml
Nowhere else in the documentation uses the phrase
"Must be a depth of 32"
which also seems incorrect for 64-bit riscv.
Also, the index parameter had the same description as root, which is incorrect.
=> libsel4: fix riscv ASIDcontrol param descriptions

include/arch/riscv/arch/model/statedata.h, src/arch/riscv/kernel/vspace.c, src/arch/riscv/model/statedata.c
Since cdbae0b3b27c8a69f1b47074523177e428b0b95a, seL4 has used a 0-indexed naming for the levels of the page tables, starting from the root (0) and down to the lowest level (2), for CONFIG_PT_LEVELS=3.
However, the naming of the stored page table was never updated, leading to a variety of confusing code such as:
kernel_image_level2_dev_pt[RISCV_GET_PT_INDEX(vaddr, 1)] = \
pte_next(paddr, true);
When CONFIG_PT_LEVELS=4, the entries of the level 1 page table instead point to gigapages (1GiB) instead of megapages (2MiB). (Behaviour left unchanged).
=> riscv: rename incorrect level2_pt -> level1_pt

CHANGES.md, include/arch/arm/arch/32/mode/machine/registerset.h, include/arch/arm/arch/64/mode/machine/registerset.h, src/arch/arm/config.cmake
Make which user thread ID register used by the kernel for its TLS operations configurable. Either tpidru or tpidruro can be selected which map to architecture registers tpidru and tpidruro on aarch32 and tpidr_el0 and tpirrro_el0 on aarch64.
The default value of this option is tpidru to stay compatible with the kernel's current behaviour.
Addresses: #1216
=> arm,tls: Add config option KernelArmTLSReg

include/kernel/boot.h, src/kernel/boot.c
The clock sync test at boot keeps failing for the hifive board with time deltas as high as 5. We think this is because mmode might be taking a big lock for reading the time.
Add a macro for allowed delta and set it to a higher value for RISC-V.
Supersedes #1366. See also the comments/discussion there.
=> boot: make clock sync test delta conditional

CMakeLists.txt
Note for LLVM 20 a new compile error appears:
clang: error: argument unused during compilation: '-c' [-Werror,-Wunused-command-line-argument]. You'd need to add -Wno-unused-command-line-argument to the kernel compile options to build successfully.
Thanks to Chang Liu for mentioning the fix.
=> Ignore clang 20 warning that breaks the build

include/arch/arm/arch/machine/gic_v3.h, src/arch/arm/machine/gic_v3.c
Was an alias of GICD_CTLR_ENABLE_G0.
=> gic_v3: Remove non-existent register bit

CHANGES.md, src/arch/riscv/config.cmake
Change the default llvm configuration for riscv32 to disable floating point due to limited clang compiler support
=> riscv32,llvm: Disable floating point by default

include/arch/riscv/arch/32/mode/hardware.h, include/arch/riscv/arch/64/mode/hardware.h, src/arch/riscv/kernel/vspace.c, src/plat/ariane/overlay-ariane.dts, src/plat/cheshire/overlay-cheshire.dts, src/plat/hifive/overlay-hifive.dts, src/plat/polarfire/overlay-polarfire.dts, src/plat/qemu-riscv-virt/overlay-qemu-riscv-virt.dts, src/plat/rocketchip/overlay-rocketchip-base.dts, src/plat/rocketchip/overlay-rocketchip-zcu102.dts, src/plat/spike/overlay-spike.dts, src/plat/star64/overlay-star64.dts, tools/hardware/config.py, tools/hardware/utils/memory.py
Instead of special handling for the SBI region in the kernel, which can
be platform specific, treat it as a reserved memory region in the device
tree which is sufficient to prevent the kernel from turning the reserved
region into kernel untyped caps.
This is potentially an alternative approach to https://github.com/seL4/seL4/pull/365.  This approach doesn't prevent the kernel from creating device untypeds for SBI regions but prevents the kernel from using any of the memory regions itself. This treatment is similar to how firmware memory is treated on x86 and Arm.
Test with: seL4/seL4_tools#135
=> RISC-V: reserve memory for SBI in device tree

src/plat/qemu-riscv-virt/overlay-qemu-riscv-virt.dts
The last device tree overlay was overriding the cell widths to 64-bit, so change the first overlay to be compatible with this.
=> qemu-riscv-virt,dts: Fix cell size definitions

include/arch/arm/arch/machine/gic_v3.h, include/arch/arm/arch/smp/ipi.h, include/arch/arm/arch/smp/ipi_inline.h, include/machine/interrupt.h, src/arch/arm/machine/gic_v3.c, src/arch/arm/smp/ipi.c, src/object/interrupt.c
Separate priority drop from deactivation so that when the kernel
delegates interrupts to userlevel, they can be left in the active state
until user level performs the ack invocation which deactivates them.
This is more efficient than doing a disable and enable operation
for each handled interrupt as it is core local and doesn't require
sending operations to the GIC distributor.
=> gicv3: Use split EOI mode

src/plat/star64/overlay-star64.dts
Star64 already has a defined `address-cells` and `size-cells` in `star64.dts` so we should be consistent with that.
=> Fix Star64 cell size in DTS overlay

CMakeLists.txt
The source layout for arm_hyp configurations uses a symlink to redirect sel4_arch include paths back to aarch32 when KernelSel4Arch is set to arm_hyp. This case wasn't being handled by the CMake install target for installing libsel4 and kernel.elf when the project is used in a standalone context. The consequence is that the ARM_HYP verified configurations would fail to install even though they would build correctly.
We directly address this issue by accounting for the arm_hyp special case in the installation command where we manually resolve the symlink. If new arm_hyp symlinks are added in the future, this fix should still apply providing that the update to the CMake install target uses the same resolved sel4arch path variable introduced by this change.
There is a longer-term plan to …
=> Fixes #1334: install target fails arm_hyp configs

src/kernel/boot.c
During boot, all dynamic memory allocated by the kernel is precalculated and then allocated in one chunk. The precalculation is supposed to match the allocation logic precisely which means any left over objects indicated an inconsistency between the precalculation and reality. The kernel should print an error and potentially abort if it encounters this situation.
I noticed that there's a page table calculation error in vtd_get_n_paging for calculating page tables required to map iommu reserved regions that over estimates the number of page tables required quite significantly (for example 14337 extra tables on the haswell test machines we use).  This check should detect any other similar calculation errors in the startup paths that we test.
=> boot: Check that predicted page tables were used

src/plat/bcm2711/overlay-rpi4.dts, tools/hardware.yml
Attach the firmware node so that the elfloader can perform smp boots.
=> rpi4,elfloader: select firmware node for smp boot

CHANGES.md, include/arch/arm/armv/armv7-a/armv/vcpu.h, include/arch/arm/armv/armv8-a/64/armv/vcpu.h
The virtual timer registers managed within a VCPU context are not saved if written to, if the VCPU in question is disabled. This results in any updates to the virtual timer registers being lost/written over when that VCPU is next scheduled and context switched in.
=> arm: Save VCPU virt timer registers when disabled

include/arch/arm/arch/32/mode/model/statedata.h, include/model/statedata.h, src/arch/arm/32/model/statedata.c, src/arch/arm/armv/armv7-a/tlb.c, src/arch/arm/config.cmake, src/model/statedata.c
Again, variable was noticed in the objdump of a RISC-V build, despite only being used for a specific ARM CortexA8 platform.
Hopefully this one doesn't affect the proofs, it's not referenced in l4v so :)
=> statedata: only define tlbLockCount for cortex-a8

CHANGES.md, include/arch/arm/arch/object/vcpu.h, include/arch/arm/armv/armv7-a/armv/vcpu.h, libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/constants.h, src/drivers/timer/generic_timer.c
In aarch32 configurations with hypervisor support, CNTKCTL isn't saved/restored when saving/restoring the virtual timer. We address this by mirroring the aarch64 implementation.
=> aarch32/vcpu: save and restore CNTKCTL

include/util.h
Wrap the `config_set` macro in a static inline function so that verification automation does not simplify away dead code branches based on it, but the compiler still does.
In most parts of the proofs we want to pretend that we don't know the config value yet and consider both options. This makes the proofs more independent on the config value that is selected.
=> utils: wrap config_set for verification

configs/AARCH64_ultra96v2_verified.cmake
(Had forgotten to add this one in the last batch).
Expecting style check to fail for x bit as usual for the verified configs.
=> configs: mark Ultra96v2 as supported by the proofs

.github/workflows/preprocess-deploy.yml
Deploy the MCS verification manifest for versions that have no MCS preprocess differences. These may be different from non-MCS preprocess outcomes, and since the MCS verification is on a branch, we can deploy it separately.
C verification on MCS has progressed enough that we want to do this automatically now, as we do for the master branch.
=> github: deploy mcs verification manifest

include/kernel/thread.h, src/object/reply.c
The outermost if statement can be removed in reply_pop because reply_pop is called only in reply_remove, which includes an explicit check for this condition.
The new inline function setThreadStateBlockedOnReply is used within reply_push.
=> mcs: refactor reply functions to ease verification

tools/config_gen.py, tools/helpers.cmake
With the current implementation of add_config_library, the config_gen Python script is called on to regenerate the config header and json files every time CMake is configured. Since many targets rely on these files, it practically forces the entire project to be rebuilt whenever CMake is reconfigured, even if the project has already been configured and no settings have changed.
This change makes it so the generated header and json files get saved to temporary locations, and only override the final header and json files if the contents are different, thus avoiding a timestamp update and rebuild if they are the same. The temporary files are deleted after. This is all done at configure time (see #1105 for why).
=> CMake: Avoid rebuilds by diffing generated headers

CONTRIBUTING.md, LICENSE.md, README.md
For most of these redirects are in place, but it is better to use the correct ones directly.
Also replaces the blog link with the (now) official licensing page that summarises it.
=> Update links after seL4 website re-org

src/plat/qemu-arm-virt/config.cmake, src/plat/qemu-riscv-virt/config.cmake
The build currently fails for arm / riscv using qemu version 10, because the cmake script incorrectly skips the first digit - so it thinks qemu 10.0.0 is actually version 0.0.0:
```
$ ../init-build.sh -DPLATFORM=qemu-arm-virt -DSIMULATION=TRUE  -DCMAKE_TOOLCHAIN_FILE=~/gnu-aarch64.cmake
loading initial cache file /Users/seph/3rdparty/sel4test/projects/sel4test/settings.cmake
-- ARM_CPU not set, defaulting to cortex-a53
-- Extracting device tree from QEMU
-- qemu found at qemu-system-aarch64
CMake Error at /Users/seph/3rdparty/sel4test/kernel/src/plat/qemu-arm-virt/config.cmake:116 (message):
Error: need at least QEMU version 3.1.0, found '0.0.0'
```
See #1462 for more details.
This change to the version regex allows qemu version number fields to have multiple digits.
Fixes #1462.
=> Fix cmake regex to work with qemu version 10

gcc.cmake
Already registered for RISC-V so makes sense to do the same for ARM.
=> Detect 'aarch64-elf-' toolchain

include/object/schedcontext.h, src/object/objecttype.c, src/object/schedcontext.c
This is a continuation of https://github.com/seL4/seL4/pull/846 which explicitly left out `setConsumed` until MCS verification got there. (Which is now).
Before:
- invokeSchedContext_Consumed and invokeSchedContext_YieldTo clobber the message info field in the reply from kernel, which results in a length 0 message.
- invokeSchedContext_Consumed and invokeSchedContext_YieldTo may crash the kernel for read-only IPC buffers
- invokeSchedContext_Consumed and invokeSchedContext_YieldTo generate a reply from kernel for syscalls that should not generate replies
- completeYieldTo does not set the badge register, which will contain whatever that previous syscall returned and not correctly indicate success/failure.
Instead:
- look up the IPC buffer again and check for write authority
- follow the …
=> yieldTo: respect kernel reply protocol

src/object/tcb.c
This fixes the error message in decodeSetTimeoutEndpoint and correctly updates current_syscall_error.
=> mcs: fix error handling in decodeSetTimeoutEndpoint

.github/workflows/proof.yml
We're currently using AWS Arm VMs, and vanilla Isabelle2024 ships a Z3 version that does not work on Arm. Using the ts-2024 branch fixes this until we have upgraded everything to Isabelle2025.
=> github: point proof tests to Isabelle ts-2024

src/object/untyped.c
Non-functional change. This will probably affect verification, so definitely not expecting this to be merged anytime soon.
But it was very weird we had this rootSlot argument mark as UNUSED, and it took me a bit to realise exactly what excaprefs[0] was supposed to be.
=> cleanup: use rootSlot to give a name to excapref0

manual/README.md
Migrate documentation of the API docs generation process here from the docsite where it is too much out of view. Here it is closer to where it is needed and more likely to get updated when things change.
Compared to the docsite version, this has applied:
- standard wrap column
- markdown lints
- adjusted headings
- `object-api-sel4-arch.xml` etc renames
- include RISC-V in structure
=> manual/README.md: include API doc generation

.gitignore, manual/tools/parse_doxygen_xml.py
- fix python string escape warnings
- minor python lints and typos
- use non-breaking space for types in markdown tables
The latter avoids breaking `seL4_Word *` into two lines in tables. Uses unicode `0u000A`, because `&nbsp;` does not always get rendered correctly and `0u000A` is just passed through.
=> manual: markdown generation tweaks

manual/tools/parse_doxygen_xml.py
Recent doxygen versions generate references for constants that are named in the text. Since we do not produce a constant table in the manual (neither markdown nor tex), these references point to nowhere and produce a KeyError in the ref_dict on lookup.
The corresponding xml nodes are of this form:
```
<ref kindref="member" refid="include_2sel4_2constants_8h_1a9a3...">seL4_TCBFlag</ref>
```
Ignore such dangling references and return the content (seL4_TCBFlag in the example) instead. Run text escape on the content to cover underscores etc in LaTeX.
Does not produce a warning since we expect this to be normal behaviour.
=> manual: gracefully handle dangling references

include/kernel/boot.h, src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c, src/arch/x86/kernel/boot.c, src/kernel/boot.c
This would previously create regions that were off-by-1 on the upper end with addresses such as 0x40001. This seems to have been fine, and just created an extra unnecessary memory region covering the extra bootinfo memory. But at the same time this was inconsistent with e.g. calculate_rootserver_size() which contained the check:
size += extra_bi_size_bits > 0 ? BIT(extra_bi_size_bits) : 0;
and this created issues when I was experimenting with some boot code changes as the bootinfo size accounting was inconsistent.
=> boot: check for size_bits=0 before calculating BIT(size_bits)

libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/deprecated.h, libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/types.h
This was missed in cb8ee83f0cd2268b1d6b1cd5ca30b031db5896c4; their use was removed from syscall_stub_gen but their typedefs remained.
Fixes #1498.
=> aarch64,vspace: move PUD/PGD typedefs to deprecated code

src/arch/arm/kernel/boot.c, src/arch/riscv/kernel/boot.c, src/kernel/boot.c
Fixes #1008. The justification for printing [a..b) form is because we will print empty regions in the code that prints these reserved/available regions, and if we used [a..b-1] form then we'd see weirdness such as [0x1000..0x0fff] instead of [0x1000, 0x1000). An alternative would have been `a..<b`.
---
Memory regions in the boot code are represented as top-end-exclusive and so printing them as [a..b] is at best misleading (especially as the elfloader code that runs beforehand uses [a..b] for inclusive ranges). The boot log now looks like this (QEMU AArch64):
ELF-loading image 'rootserver' to 40239000
paddr=[40239000..4061efff]
vaddr=[400000..7e5fff]
virt_entry=40e3f8
Enabling MMU and paging
Jumping to kernel-image entry point...
Bootstrapping kernel
Warning: Could not infer GIC interrupt …
=> boot: print half-open regions as [a..b)

include/object/tcb.h
This is seemingly dead code leftover from: https://github.com/seL4/seL4/commit/c428f320b76dd271206711e6f6203d06f7b2c289.
=> thread_ctrl: Remove unused flags

include/arch/arm/arch/32/mode/model/statedata.h, include/arch/arm/arch/32/mode/object/structures.h, include/arch/arm/arch/64/mode/kernel/vspace.h, include/arch/arm/arch/64/mode/model/statedata.h, include/arch/arm/arch/64/mode/object/structures.h, include/arch/riscv/arch/model/statedata.h, include/arch/riscv/arch/object/structures.h, include/arch/x86/arch/32/mode/object/structures.h, include/arch/x86/arch/64/mode/object/structures.h, src/arch/arm/32/kernel/vspace.c, src/arch/arm/32/model/statedata.c, src/arch/arm/64/kernel/vspace.c, src/arch/arm/64/model/statedata.c, src/arch/riscv/kernel/vspace.c, src/arch/riscv/model/statedata.c, src/arch/x86/32/kernel/vspace_32paging.c, src/arch/x86/64/kernel/vspace.c, src/arch/x86/kernel/ept.c, src/arch/x86/kernel/vspace.c, src/arch/x86/model/statedata.c, src/kernel/boot.c
In theory, this shouldn't affect any of the proofs, as the preprocessor output should be almost identical to previous (This is part of the motivation for changing the definition of `ASID_HIGH` to be consistent with the users of the macro).
There's also a bug (lying in wait, so not actually a bug) with the initial thread asid pool cap where we weren't actually creating it as an "asid base", but it was fine since it was 0 anyway.
=> asidpools: macro consistency

include/arch/arm/arch/machine/gic_common.h, include/drivers/irq/am335x.h, include/drivers/irq/bcm2836-armctrl-ic.h, include/drivers/irq/omap3.h
The GIC platforms use `irq_t` for `irqInvalid` -- bring remaining AArch32 platforms in line with that.
`irq_t` is an unsigned type (when it is an integer) and enum constants are signed. For the proofs to treat these platforms uniformly, they need to be the same kind. They can't all be enums, because `irq_t` can be a more complex type for SMP platforms.
=> aarch32: make sure `irqInvalid` is `irq_t`

include/arch/arm/armv/armv7-a/armv/machine.h, include/arch/arm/armv/armv8-a/64/armv/machine.h, include/kernel/thread.h, src/arch/arm/32/config.cmake, src/arch/arm/32/idle.S, src/arch/arm/32/idle.c, src/arch/arm/64/config.cmake, src/arch/arm/64/idle.S, src/arch/arm/64/idle.c, src/arch/riscv/config.cmake, src/arch/riscv/idle.S, src/arch/riscv/idle.c, src/arch/x86/config.cmake, src/arch/x86/idle.S, src/arch/x86/idle.c
Create idle.S assembly files for each platform, as GCC seems to refuse
to obey `__attribute__((naked))` on AArch64 (GCC 13.2.0) and bails out;
so we can't use the same method as on x86.
Similar to #510 but for all other platforms. The idle_thread runs
without a stack and so cannot handle the stack prologue. This should
hopefully make the kernel rely less on FORCE_INLINE for this as well.
Fixes #519 
---
Before idle_thread (not identical compilers; from the microkit sdk)
```
board/maaxboard/release/elf/sel4.elf:   file format elf64-littleaarch64
Disassembly of section .text:
0000008040011250 <idle_thread>:
8040011250: d503207f    wfi
8040011254: 17ffffff    b       0x8040011250 <idle_thread>
8040011258: d503201f    nop
804001125c: d503201f    nop
```
```
board/maaxboard/debug/elf/sel4.elf: …
```
=> arm,riscv: eliminate idle_thread function prologue

include/kernel/traps.h, libsel4/include/sel4/benchmark_track_types.h, src/arch/x86/machine/breakpoint.c
There's a few cases in the kernel where the ksKernelEntry tracking is not perfect, such as in SError reporting (and various other arm traps), and (I believe) a few other places which I haven't tracked down to a cause - but some of e.g. the RISC-V trap code where the first entry faults and the 2nd proceeds can report stale information.
In these cases, the kernel says that the entry was via a certain syscall or interrupt (etc), even though that was clearly not the case because we know the kernel exited. Now we will print out this:
halting...
Kernel entry via Unknown (0)
The changes:
- When exiting the kernel, via `c_exit_hook()`, reset `ksKernelEntry.path` to "Unknown".
An alternative here would have been add a global "valid" boolean to the kernel state, but this requires modifying every …
=> debug: invalidate ksKernelEntry on kernel exit
