seL4/seL4

- src/arch/arm/machine/l2c_310.c
> Disable L2 cache during initialisation

- include/arch/arm/arch/32/mode/machine/timer.h
- include/arch/arm/arch/64/mode/machine/timer.h
A couple of fixes for the recently added ZynqMP support based on testing of the port by I-A-I.
> ZynqMP Fixes

- gcc.cmake
- libsel4/CMakeLists.txt
This also depends on fixes to seL4-tools and musllibc repos.
> Fix building on OS X

- tools/hardware/utils/rule.py
Signed-off-by: Axel Heider <axelheider@gmx.de>
> tools: fix brackets in format parameters

- src/kernel/sporadic.c
- src/object/endpoint.c
- src/object/notification.c
- src/object/objecttype.c
- src/object/schedcontrol.c
This PR splits https://github.com/seL4/seL4/pull/217 into changes we are happy to merge and https://github.com/seL4/seL4/pull/220 has changes that still need discussion
> MCS Systems changes (Reduction 1)

- manual/parts/objects.tex
**PR Purpose**: Ready to merge.
**Testing perfromed**: Built the manual and visually inspected it.
> trivial: manual: Document SchedContext size_bits meaning

- configs/seL4Config.cmake
- tools/helpers.cmake
- tools/internal.cmake
This needs https://github.com/seL4/seL4_tools/pull/48
> CMake: remove unused and obsolete things, reduce complexity

- configs/seL4Config.cmake
- libsel4/arch_include/arm/sel4/arch/simple_types.h
- libsel4/arch_include/riscv/sel4/arch/simple_types.h
- libsel4/include/sel4/simple_types.h
- libsel4/include/sel4/types.h
- libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/simple_types.h
- libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/types.h
- libsel4/sel4_arch_include/ia32/sel4/sel4_arch/simple_types.h
- libsel4/sel4_arch_include/ia32/sel4/sel4_arch/types.h
- libsel4/sel4_arch_include/riscv32/sel4/sel4_arch/simple_types.h
- libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/simple_types.h
- libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/types.h
- libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/simple_types.h
- libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/types.h
- src/plat/allwinnerA20/config.cmake
- src/plat/apq8064/config.cmake
- tools/helpers.cmake
This contains some trivial formatting changes and comment fixes from from my other pull request. Is there a chance to get these non-funktional changes merged, so there are noch blocked on the other PRs that change functionality?
> trivial formatting changes and comment fixes

- tools/helpers.cmake
Follow up on the work of https://github.com/seL4/seL4/pull/281
* Switch to pragma once include guards
> Switch to pragma once include guards

- libsel4/sel4_plat_include/zynqmp/sel4/plat/api/constants.h
- src/plat/zynqmp/config.cmake
Signed-off-by: Axel Heider <axelheider@gmx.de>
> zynqmp/ultra96: make build work again

- include/arch/riscv/arch/fastpath/fastpath.h
- include/arch/riscv/arch/kernel/traps.h
- src/arch/riscv/c_traps.c
- src/arch/riscv/traps.S
Inline fastpath functions and call out to them from traps.S.
Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>
> fastpath: some risc-v fastpath improvements

- src/kernel/sporadic.c
See: https://github.com/seL4/seL4/issues/262
Blocked by #256
> Fix MCS/SMP refill_order assertion

- src/arch/arm/object/vcpu.c
See: https://github.com/seL4/seL4/issues/346 for details.
VPPIEvent and VGICMaintenance handling is updated to first
check that the current thread has budget. If it does not
have budget the interrupts are ignored. As interrupts are
level-triggered this effectively just delays the interrupts.
The check for budget is based on determining if the current
thread is enqueued. This occurs if (and only if) the current
thread has had a budget check that is expired.
> Fix MCS / ARM64 VCPU interrupt interaction

- src/object/objecttype.c
- src/object/reply.c
These commits change the order of a couple of function calls but otherwise keep the same control flow. Overall, they make the code much closer to the specifications and verification a lot easier
> mcs: refactor functions to ease verification

- include/drivers/uart.h
- include/machine/io.h
- src/arch/arm/config.cmake
- src/arch/arm/machine/io.c
- src/arch/riscv/machine/io.c
- src/drivers/serial/bcm2835-aux-uart.c
- src/drivers/serial/exynos4210-uart.c
- src/drivers/serial/imx.c
- src/drivers/serial/meson-gx-uart.c
- src/drivers/serial/msm-uartdm.c
- src/drivers/serial/pl011.c
- src/drivers/serial/tegra_omap3_dwapb.c
- src/drivers/serial/xuartps.c
- src/machine/io.c
- src/plat/pc99/machine/io.c
OpenSBI does not need a CR before LF
> separate UART and SBI debug output

- include/arch/arm/arch/types.h
- include/arch/riscv/arch/types.h
- include/arch/x86/arch/types.h
- include/basic_types.h
- include/stdint.h
- src/arch/arm/32/kernel/vspace.c
- src/arch/arm/64/kernel/vspace.c
- src/drivers/timer/generic_timer.c
support PRIu64 and SEL4_PRIu_word in kernel and use it
> support PRIu64 and SEL4_PRIu_word in kernel

- src/kernel/boot.c
Cleanup boot code, check sanity for last region also. I also have more commits here to print the region data, but this needs https://github.com/seL4/seL4/pull/333 to be merged fist.
> Cleanup boot code, check sanity for last region also

- include/kernel/sporadic.h
- include/kernel/thread.h
- src/kernel/sporadic.c
- src/model/preemption.c
Replaces #348, #312, and is the final component of #256 to be merged as a smaller PR.
This is a rebased version of #348 with some commits squashed, so the change in logic should be equivalent.
> MCS verified budgeting

- include/arch/riscv/arch/machine.h
Signed-off-by: Axel Heider <axelheider@gmx.de>
> trivial: fix typo

- src/arch/riscv/config.cmake
> trivial: fix typos

- include/assert.h
- include/kernel/boot.h
- include/machine.h
- libsel4/include/sel4/macros.h
- src/arch/arm/kernel/boot.c
- src/arch/arm/platform_gen.h.in
- src/arch/riscv/kernel/boot.c
- src/arch/riscv/platform_gen.h.in
- src/arch/x86/kernel/boot.c
- src/kernel/boot.c
Cleanup kernel boot code, patches are preparing another upcoming PR
> Cleanup kernel code base

- include/arch/arm/arch/machine/timer.h
- include/util.h
This is another patch extracted from from a bigger change set, that aims at improving the code quality and readability. None of this is really necessary at a pure technical level, but it's supposed to make the code easier to understand and re-usable.
> Another round of code cleanup and readabity improvements

- .github/workflows/sel4test-hw.yml
The trigger event name needs to be adjusted to `pull_request_target`, and the testing trigger removed.
> fix up event trigger for hw build

- .github/workflows/sel4test-hw.yml
One more board looking stable again.
> github: enable hw test for imx8mm

- .github/workflows/sel4test-hw.yml
Another board ready to join the hardware test
> git hw test: enable zynqmp

- .github/workflows/compilation-checks.yml
- .github/workflows/sel4test-deploy.yml
- README.md
- fix concurrency groups
- better name for kernel compile action
- show badge for full sel4test run
> github workflow improvements

- src/arch/riscv/machine/hardware.c
- src/plat/polarfire/config.cmake
- tools/hardware/irq.py
* trivial changes from https://github.com/seL4/seL4/pull/468 that could be merged already
* contains the fix for https://github.com/seL4/seL4/issues/405
> Code cleanup, aviod warnings

- tools/hardware/config.py
- tools/hardware/irq.py
- tools/hardware/utils/memory.py
- tools/umm.py
Add memoization to umm.py.
Consolidate logic for risc-v and arm memory base.
Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>
> Some python improvments

- include/arch/arm/arch/machine.h
- include/arch/riscv/arch/machine.h
- include/bootinfo.h
- include/util.h
- src/arch/arm/c_traps.c
- src/arch/arm/kernel/boot.c
- src/arch/riscv/c_traps.c
- src/arch/x86/c_traps.c
- src/kernel/boot.c
- src/machine/io.c
collect some trivial things form the other PR that could be merged easily:
- trivial: improve style for code and comments
- add comment about empty Arch_finaliseInterrupt()
- add comment about handleUnknownSyscall()
> improve comments and style

- src/arch/arm/object/interrupt.c
**Disposition:** Ready to merge.
**Testing performed:** Checked that added code compiled (requires arm SMP configuration).
Fixes #529
Signed-off-by: Jimmy Brush <code@jimmah.com>
> Add missing error code in ARM IRQControlGetTrigger

- include/arch/riscv/arch/sbi.h
Describe origin of the constants.
> risc-v: add comment about SBI constants

- src/kernel/boot.c
Unify ARM and RISC-V behavior for `insert_region()`. Just print a message and return an error, but don't call `assert()`. The caller should decide what to do with the error.
I can't find a good reason why ARM and RISC-V should be handled differently here. This was added with https://github.com/seL4/seL4/commit/4a3685df33470396c3468f9b77360f2c97cae730 to catch error where the calculation of `MAX_NUM_FREEMEM_REG` does not result in a good value. For ARM there indeed a is a calculation, for RISC-V there is just a constant that seem fine also from a practical point of view. But if the caller does not check the result, we will never find any issues on release builds anyway. Unless there is a userland root task that check how much memory is there - and this one would be a pain to rest in debug …
> boot: assert() on RISC-V also if insert_region() fails

- tools/hardware/utils/memory.py
This is just the rebased version of #350 with the commit message shortened to appease gitlint.
> tools: merge adjacent memory regions

- src/kernel/boot.c
Print the available physical memory regions before printing the reserved virtual memory regions, because as this order is more intuitive. For the checks the order does not make any difference. Factor out the checks into separate function to improve code readability.
> boot: change order to improve debug output

- src/kernel/boot.c
Simplify code and add comments.
> boot: simplify create_untypeds_for_region()

- src/machine/io.c
There is no need to keep an option for potentially debugging the error.
> remove goto in printf_core() and return directly

- include/arch/riscv/arch/machine.h
- include/arch/riscv/arch/machine/plic.h
- include/drivers/irq/riscv_plic0.h
- include/drivers/irq/riscv_plic_dummy.h
- src/arch/riscv/machine/hardware.c
- src/arch/riscv/platform_gen.h.in
- src/plat/ariane/config.cmake
- src/plat/rocketchip/config.cmake
- src/plat/spike/config.cmake
- tools/hardware.yml
Improving the RISC-V code dealing with interrupt and PLIC handling.
> RISC-V interrupt handling and PLIC cleanup

- tools/hardware/memory.py
Commit was extracted from #572
- A region can't be created from an invalid range
- A region might be too small to support the change. There is no trivial way to fix this.
> python: raise exceptions on errors

- include/arch/arm/arch/32/mode/types.h
- include/arch/arm/arch/64/mode/types.h
- include/arch/arm/arch/types.h
- include/arch/riscv/arch/32/mode/types.h
- include/arch/riscv/arch/64/mode/types.h
- include/arch/riscv/arch/types.h
- include/arch/x86/arch/32/mode/types.h
- include/arch/x86/arch/64/mode/types.h
- include/arch/x86/arch/types.h
- include/assert.h
- include/compound_types.h
- include/machine.h
- include/object.h
- include/stdarg.h
- include/string.h
- include/types.h
- src/arch/riscv/machine/hardware.c
- src/kernel/boot.c
- trivial: remove superfluous empty lines
- fix typo in comment
- remove unnecessary brackets
- boot: improve error message
> code cleanup, comment fixed, debug output improvement

- tools/hardware/memory.py
Commit was extracted from https://github.com/seL4/seL4/pull/572
- Provide a nicer string for debugging purposes.
- improve comments about the purpose of `__repr__()` and `__str__()`
> python: add __str__() for Region

- src/kernel/sporadic.c
- src/kernel/thread.c
Signed-off-by: Indan Zupancic <Indan.Zupancic@mep-info.com>
Test with: seL4/sel4test#56
> budget >= MIN_BUDGET

- include/util.h
- Follow-up form https://github.com/seL4/seL4/pull/599
- adding the missing include
- adding comment to capture the result of the tests.
> Add missing include and improve comments

- src/plat/bcm2711/config.cmake
- src/plat/bcm2711/overlay-rpi4-address-mapping.dts
Signed-off-by: Lukas Graber <lukas.graber@hensoldt-cyber.de>
> rpi4: Add UART DTS support

- include/kernel/thread.h
- include/model/statedata.h
- src/kernel/boot.c
- src/kernel/thread.c
- src/model/statedata.c
Special case the idle thread SC budget handling in order to ensure that it always has sufficient budget to be scheduled.
Companion change to: https://github.com/michaelmcinerney/l4v/commit/8ed834b3778d4f09c0fbf999974837760a54e635
> Idle thread SC special casing

- src/kernel/boot.c
Some code cleanup:
- add brackets for if-body 
- use explicit field names when initializing element
> a bit of code cleanup

- .github/workflows/xml_lint.yml
Changes to the dtd can also invalidate the test, so must be part of the trigger.
(This should allow the test to run on e.g. #766)
> github: trigger xml-lint test on dtd changes

- CMakeLists.txt
- src/arch/riscv/common_riscv.lds
- src/arch/riscv/traps.S
Rebase of https://github.com/seL4/seL4/pull/224 ready for merge.
> Update of  riscv gp fixes #224 

- include/arch/riscv/arch/machine.h
Provide `get_sbi_mask_for_all_remote_harts()` helper to avoid redundant code
> risc-v: add SBI remote hart mask helper function

- include/arch/riscv/arch/machine.h
> trivial: add missing space character

- manual/parts/bootup.tex
Signed-off-by: Ahmed Charles <acharles@outlook.com>
> Fix incorrect type

- src/object/objecttype.c
> mcs: modify GHOST_UPD comment for verification

- src/arch/arm/machine/gic_v3.c
Signed-off-by: Jorge Pereira <jorgepereira89@gmail.com>
> gic_v3: fix EOImode bit number

- src/object/objecttype.c
> mcs: update AUXUPD comment for verification

- CHANGES
- libsel4/include/sel4/constants.h
The `seL4_MinSchedContextBits` size change in #938 is breaking and can be hard to debug. Provide some guidance.
> more seL4_MinSchedContextBits docs

- manual/parts/vspace.tex
Closes https://github.com/seL4/seL4/issues/1039.
> manual: fix VM attributes documentation

- src/model/smp.c
#1065 introduces a compilation error from refactoring. Also apply some missed feedback from #1065
> SMP: Fixup compilation error

- .github/workflows/sel4bench-pr.yml
> github: fix sel4bench trigger in GitHub workflow

- src/object/tcb.c
These changes ease verification of the two functions and should have minimal impacts on behaviour and performance.
> MCS: tweak validFaultHandler and installTCBCap for verification

- .github/workflows/sel4test-deploy.yml
This is missing in commit e6fbbbb0 from https://github.com/seL4/seL4/pull/1154
> CI: update deploy workflow also

- src/arch/arm/machine/debug.c
The implementation of single-stepping on ARMv7 relies on instruction breakpoint mismatches. In the implementation, it sets one of the breakpoint value registers (BVR) to the virtual address NULL and configures the corresponding breakpoint control register to generate a debug exception whenever an instruction that does not match this address is executed. I believe this is incorrect because it means that when single-stepping is enabled, no progress will ever be made and every instruction will mismatch with NULL and result in a debug exception being generated.
I believe the correct behavior is to instead set the debug value register to be the current LR. Then, what will happen instead is that once the thread is permitted to run again, the instruction that is returned to will be executed, and …
> Hardware Debug API: Single stepping on ARMv7

- .github/workflows/sel4bench-pr.yml
- .github/workflows/sel4test-deploy.yml
- .github/workflows/sel4test-hw.yml
See comment https://github.com/seL4/camkes-vm-examples/pull/60#discussion_r1468294658 and https://github.com/seL4/camkes-vm-examples/pull/61
> CI: the seL4/machine_queue repo is public now

- src/plat/qemu-arm-virt/config.cmake
Closes https://github.com/seL4/seL4/issues/1209.
> Fix USER_TOP config option being unconditional

- .cmake-format.yaml
Looking at the changes of https://github.com/seL4/seL4/pull/1210, it seem the cmake style file needs some fixes.
> style: fix cmake formatting spec

- include/arch/arm/arch/64/mode/model/statedata.h
Follow-up from https://github.com/seL4/seL4/pull/1179#discussion_r1557399818 for the PR from @Kswin01
> fix type, add missing 'extern' keyword

- manual/tools/parse_doxygen_xml.py
- tools/hardware_gen.py
- tools/invocation_header_gen.py
- tools/syscall_header_gen.py
See commit messages for details.
> Remove more Python deps

- CONTRIBUTORS.md
Based on the signed-off-by lines in commits since release tag 12.1.0.
> CONTRIBUTORS: add contributors since 12.1.0

- libsel4/arch_include/arm/interfaces/object-api-arch.xml
- libsel4/tools/sel4_idl.xsd
- manual/manual.tex
Cherry pick 2 commits from #27 that should go into the current release.
> cherry-pick smaller manual fixes

- src/arch/arm/64/kernel/vspace.c
Frame caps should be checked for stale mapping info before authorising any operation on them. In this particular case, the mapping may have become invalid.
See also #1281
> vspace: check for stale mapping on all flush types

- src/arch/riscv/kernel/vspace.c
Useful for debugging in my experience.
> Print virtual address already mapped in user error

- src/object/endpoint.c
This factors out code from cancelAllIPC and cancelBadgedSends by introducing the inline function restart_thread_if_no_fault
> mcs: refactor cancelAllIPC and cancelBadgedSends

- manual/parts/bootup.tex
This adds `seL4_CapSMC` to table 9.1 and updates section 9.1 as well.
> manual: update table 9.1

- include/arch/riscv/arch/machine/hardware.h
- src/arch/riscv/kernel/vspace.c
This contains comment revision and code simplification encountered when reading riscv vspace sources.
> riscv: some trivial fixes

- src/kernel/sporadic.c
This refactors refill_budget_check and schedule_used to ease verification by limiting heap access via refill_head and refill_tail, and providing (inlined) named functions for both the condition and bodies of the loops.
> mcs: refactor refill_budget_check to ease verification

- src/object/schedcontrol.c
This eases verification by using a local variable
which remains unchanged during execution of the
function.
This also makes use of the function sc_active.
> mcs: rephrase invokeSchedControl_ConfigureFlags

- include/kernel/faulthandler.h
- src/api/syscall.c
- src/kernel/faulthandler.c
- src/kernel/thread.c
Please see the commit messages. I can add some more information to these commit messages for how it is that these changes do ease verification, if people would like that.
> mcs: some small changes to ease verification

- README.md
These are going to be removed in the website reorg.
> README: remove outdated pages

- include/arch/arm/arch/api/types.h
- include/arch/riscv/arch/api/types.h
- include/arch/x86/arch/api/types.h
> cleanup: remove obselete pageType and asidMax

- src/api/faults.c
- src/kernel/thread.c
> mcs: refactor doReplyTransfer and setMRs_fault

- CHANGES.md
- README.md
README.md:
- avoid using non-extension URLs, because they depend on how the site is hosted
- update links to point into the new structure
CHANGES.md:
- update releases link
> README: update links for new docsite structure
